/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (POP)
- (id)pop_animationForKey:(id)fp8;
- (id)pop_animationKeys;
- (void)pop_removeAnimationForKey:(id)fp8;
- (void)pop_removeAllAnimations;
- (void)pop_addAnimation:(id)fp8 forKey:(id)fp12;
@end

