/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (MagicalRecordDeprecated)
+ (id)MR_newContextWithStoreCoordinator:(id)fp8;
+ (id)MR_newContextWithParent:(id)fp8;
+ (id)MR_newContext;
+ (id)MR_contextWithoutParent;
@end

