/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TLSwizzleProtocol-Protocol.h"

@interface _ABCreateStringWithAddressDictionary (TLPageViewController) <TLSwizzleProtocol>
+ (void)load;
- (id)tl_pendingVCs;
- (void)setTl_pendingVCs:(id)fp8;
- (void)setTl_currentIndex:(id)fp8;
- (id)tl_currentIndex;
- (void)tlsw_setDelegate:(id)fp8;
- (void)tlsw_setDataSource:(id)fp8;
- (void)tl_swizzleMethods:(id)fp8;
@end

