/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (MGProportionalFill)
- (id)imageScaledToFitSize:(struct CGSize)fp8;
- (id)imageCroppedToFitSize:(struct CGSize)fp8;
- (id)imageToFitSize:(struct CGSize)fp8 method:(int)fp16;
@end

