/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (TNDRCelebrityBadge)
+ (id)badgeImageFromBadgeType:(id)fp8 withOutline:(BOOL)fp12 mainColor:(id)fp16;
+ (id)peopleBadgeWithOutlineWithFillColor:(id)fp8;
+ (id)celebrityBadgeWithOutlineWithFillColor:(id)fp8;
+ (id)peopleBadgeWithFillColor:(id)fp8;
+ (id)celebrityBadgeWithFillColor:(id)fp8;
@end

