/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (Godzippa)
- (BOOL)GZipDecompressFile:(id)fp8 writingContentsToFile:(id)fp12 error:(id *)fp16;
- (BOOL)GZipCompressFile:(id)fp8 writingContentsToFile:(id)fp12 atLevel:(int)fp16 error:(id *)fp20;
- (BOOL)GZipCompressFile:(id)fp8 writingContentsToFile:(id)fp12 error:(id *)fp16;
@end

