/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (TinderNotificationProtocol)
- (void)_navigateToMatchesView;
- (void)_presentChatForNotification:(id)fp8;
- (void)dismissPresentedViewControllerTimes:(int)fp8 withCompletion:(id)fp(null);
- (void)dismissUntilMainNav:(id)fp(null);
- (void)performActionForNotification:(id)fp8;
- (void)didTapNotificationWindow:(id)fp8 notification:(id)fp12;
- (BOOL)notificationWindow:(id)fp8 shouldAllowInteractionForNotification:(id)fp12;
- (BOOL)notificationWindow:(id)fp8 shouldShowNotification:(id)fp12;
@end

