/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (TNDRMatch)
+ (id)addNewline:(id)fp8;
+ (id)buildContentDescriptionFromMatch:(id)fp8;
+ (id)descriptionForMatch:(id)fp8;
+ (id)tndr_searchableItemForMatch:(id)fp8 image:(id)fp12;
+ (id)tndr_searchableItemForMatch:(id)fp8;
@end

