/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (A2BlockDelegate)
+ (void)bk_registerDynamicDelegateNamed:(id)fp8 forProtocol:(id)fp12;
+ (void)bk_registerDynamicDelegateNamed:(id)fp8;
+ (void)bk_registerDynamicDataSourceNamed:(id)fp8;
+ (void)bk_registerDynamicDelegate;
+ (void)bk_registerDynamicDataSource;
+ (void)bk_linkProtocol:(id)fp8 methods:(id)fp12;
+ (void)bk_linkDelegateMethods:(id)fp8;
+ (void)bk_linkDataSourceMethods:(id)fp8;
+ (const CDAnonymousStruct12 *)bk_delegateInfoForProtocol:(id)fp8;
+ (id)bk_delegateInfoByProtocol:(BOOL)fp8;
- (id)bk_ensuredDynamicDelegateForProtocol:(id)fp8;
- (id)bk_ensuredDynamicDelegate;
@end

