/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (PureLayout)
+ (int)al_marginAxisForAxis:(int)fp8;
+ (int)al_marginForEdge:(int)fp8;
+ (int)al_constraintAxisForAxis:(int)fp8;
+ (int)al_layoutAttributeForAttribute:(int)fp8;
+ (void)al_applyGlobalStateToConstraint:(id)fp8;
+ (void)autoSetIdentifier:(id)fp8 forConstraints:(id)fp(null);
+ (id)al_currentGlobalConstraintIdentifier;
+ (id)al_globalConstraintIdentifiers;
+ (void)autoSetPriority:(float)fp8 forConstraints:(id)fp(null);
+ (BOOL)al_isExecutingPriorityConstraintsBlock;
+ (float)al_currentGlobalConstraintPriority;
+ (id)al_globalConstraintPriorities;
+ (id)autoCreateConstraintsWithoutInstalling:(id)fp(null);
+ (id)autoCreateAndInstallConstraints:(id)fp(null);
+ (BOOL)al_preventAutomaticConstraintInstallation;
+ (id)al_currentArrayOfCreatedConstraints;
+ (id)al_arraysOfCreatedConstraints;
- (void)autoRemove;
- (void)autoInstall;
- (id)autoIdentify:(id)fp8;
@end

