/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (PINDecodedImage)
+ (id)pin_decodedImageWithCGImageRef:(struct CGImage *)fp8 orientation:(int)fp12;
+ (id)pin_decodedImageWithCGImageRef:(struct CGImage *)fp8;
+ (id)pin_decodedImageWithData:(id)fp8 skipDecodeIfPossible:(BOOL)fp12;
+ (id)pin_decodedImageWithData:(id)fp8;
+ (void)load;
@end

