/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (A2DynamicDelegate)
- (id)bk_dynamicDelegateWithClass:(Class)fp8 forProtocol:(id)fp12;
- (id)bk_dynamicDelegateForProtocol:(id)fp8;
- (id)bk_dynamicDelegate;
- (id)bk_dynamicDataSource;
@end

