/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (BlocksKitPrivate)
- (void)bk_setResponseLength:(unsigned int)fp8;
- (unsigned int)bk_responseLength;
- (void)bk_setResponse:(id)fp8;
- (id)bk_response;
- (void)bk_setResponseData:(id)fp8;
- (id)bk_responseData;
@end

