/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (MagicalFinders)
+ (id)MR_fetchAllSortedBy:(id)fp8 ascending:(BOOL)fp12 withPredicate:(id)fp16 groupBy:(id)fp20 delegate:(id)fp24;
+ (id)MR_fetchAllSortedBy:(id)fp8 ascending:(BOOL)fp12 withPredicate:(id)fp16 groupBy:(id)fp20 delegate:(id)fp24 inContext:(id)fp28;
+ (id)MR_fetchAllSortedBy:(id)fp8 ascending:(BOOL)fp12 withPredicate:(id)fp16 groupBy:(id)fp20;
+ (id)MR_fetchAllSortedBy:(id)fp8 ascending:(BOOL)fp12 withPredicate:(id)fp16 groupBy:(id)fp20 inContext:(id)fp24;
+ (id)MR_fetchAllGroupedBy:(id)fp8 withPredicate:(id)fp12 sortedBy:(id)fp16 ascending:(BOOL)fp20;
+ (id)MR_fetchAllGroupedBy:(id)fp8 withPredicate:(id)fp12 sortedBy:(id)fp16 ascending:(BOOL)fp20 inContext:(id)fp24;
+ (id)MR_fetchAllGroupedBy:(id)fp8 withPredicate:(id)fp12 sortedBy:(id)fp16 ascending:(BOOL)fp20 delegate:(id)fp24;
+ (id)MR_fetchAllGroupedBy:(id)fp8 withPredicate:(id)fp12 sortedBy:(id)fp16 ascending:(BOOL)fp20 delegate:(id)fp24 inContext:(id)fp28;
+ (id)MR_fetchAllWithDelegate:(id)fp8 inContext:(id)fp12;
+ (id)MR_fetchAllWithDelegate:(id)fp8;
+ (id)MR_fetchController:(id)fp8 delegate:(id)fp12 useFileCache:(BOOL)fp16 groupedBy:(id)fp20 inContext:(id)fp24;
+ (id)MR_findByAttribute:(id)fp8 withValue:(id)fp12 andOrderBy:(id)fp16 ascending:(BOOL)fp20;
+ (id)MR_findByAttribute:(id)fp8 withValue:(id)fp12 andOrderBy:(id)fp16 ascending:(BOOL)fp20 inContext:(id)fp24;
+ (id)MR_findByAttribute:(id)fp8 withValue:(id)fp12;
+ (id)MR_findByAttribute:(id)fp8 withValue:(id)fp12 inContext:(id)fp16;
+ (id)MR_findFirstWithPredicate:(id)fp8 sortedBy:(id)fp12 ascending:(BOOL)fp16 andRetrieveAttributes:(id)fp20;
+ (id)MR_findFirstWithPredicate:(id)fp8 sortedBy:(id)fp12 ascending:(BOOL)fp16 inContext:(id)fp20 andRetrieveAttributes:(id)fp24;
+ (id)MR_findFirstWithPredicate:(id)fp8 andRetrieveAttributes:(id)fp12;
+ (id)MR_findFirstWithPredicate:(id)fp8 andRetrieveAttributes:(id)fp12 inContext:(id)fp16;
+ (id)MR_findFirstWithPredicate:(id)fp8 sortedBy:(id)fp12 ascending:(BOOL)fp16;
+ (id)MR_findFirstWithPredicate:(id)fp8 sortedBy:(id)fp12 ascending:(BOOL)fp16 inContext:(id)fp20;
+ (id)MR_findFirstWithPredicate:(id)fp8 inContext:(id)fp12;
+ (id)MR_findFirstWithPredicate:(id)fp8;
+ (id)MR_findFirstOrCreateByAttribute:(id)fp8 withValue:(id)fp12 inContext:(id)fp16;
+ (id)MR_findFirstOrCreateByAttribute:(id)fp8 withValue:(id)fp12;
+ (id)MR_findFirstOrderedByAttribute:(id)fp8 ascending:(BOOL)fp12;
+ (id)MR_findFirstOrderedByAttribute:(id)fp8 ascending:(BOOL)fp12 inContext:(id)fp16;
+ (id)MR_findFirstByAttribute:(id)fp8 withValue:(id)fp12;
+ (id)MR_findFirstByAttribute:(id)fp8 withValue:(id)fp12 inContext:(id)fp16;
+ (id)MR_findFirst;
+ (id)MR_findFirstInContext:(id)fp8;
+ (id)MR_findAllWithPredicate:(id)fp8;
+ (id)MR_findAllWithPredicate:(id)fp8 inContext:(id)fp12;
+ (id)MR_findAllSortedBy:(id)fp8 ascending:(BOOL)fp12 withPredicate:(id)fp16;
+ (id)MR_findAllSortedBy:(id)fp8 ascending:(BOOL)fp12 withPredicate:(id)fp16 inContext:(id)fp20;
+ (id)MR_findAllSortedBy:(id)fp8 ascending:(BOOL)fp12;
+ (id)MR_findAllSortedBy:(id)fp8 ascending:(BOOL)fp12 inContext:(id)fp16;
+ (id)MR_findAll;
+ (id)MR_findAllInContext:(id)fp8;
@end

