/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (TNDRAttributedString)
+ (id)tinderAttributedStringForRateLimitWarningDialogHeaderDetailText:(id)fp8;
+ (id)tinderAttributesForRateLimitWarningDialogHeaderDetailText;
+ (id)tinderAttributedStringForRateLimitWarningDialogHeaderTitle:(id)fp8;
+ (id)tinderAttributesForRateLimitWarningDialogHeaderTitle;
+ (id)tinderAttributesForUnmatchDialogHeaderDetailText;
+ (id)tinderAttributesForUnmatchDialogHeaderTitle;
+ (id)tinderAttributedStringForTimeRemainingText:(id)fp8;
+ (id)tinderAttributedStringForRoadblockDialogHeaderTitle:(id)fp8;
+ (id)tinderAttributedStringForReportingDialogHeaderDetailText:(id)fp8;
+ (id)tinderAttributesForReportingDialogHeaderDetailText;
+ (id)tinderAttributesForSuperLikeDialogHeaderDetailText;
+ (id)tinderAttributesForSuperLikeDialogHeaderTimeRemainingText;
+ (id)tinderAttributedStringForReportingDialogHeaderTitle:(id)fp8;
+ (id)tinderAttributesForSuperLikeDialogHeaderTitle;
+ (id)tinderAttributesForReportingDialogHeaderTitle;
+ (id)tinderAttributedStringForDialogFilledCustomTextFooterTitle:(id)fp8;
+ (id)tinderAttributesForDialogFilledCustomTextFooterTitle;
+ (id)tinderAttributedStringForDialogHeaderDetailText:(id)fp8;
+ (id)tinderAttributedStringForSuperLikeDialogHeaderTitle:(id)fp8;
+ (id)tinderAttributedStringForSuperLikeDialogTimeRemainingText:(id)fp8;
+ (id)tinderAttributedStringForSuperLikeDialogDetailText:(id)fp8;
+ (id)tinderAttributesForDialogHeaderDetailText;
+ (id)tinderAttributedStringForDialogHeaderTitle:(id)fp8;
+ (id)tinderAttributesForDialogHeaderTitle;
@end

