/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (TNDRButton)
+ (id)tinderButtonWithType:(int)fp8;
+ (id)tryBeforeYouBuyButtonWithTitle:(id)fp8 subtitle:(id)fp12;
+ (id)tinderRectangleCancelButton;
+ (id)tinderRectangleButton;
+ (id)tinderCancelButton;
+ (id)tinderButton;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (struct UIEdgeInsets)hitTestEdgeInsets;
- (void)setHitTestEdgeInsets:(struct UIEdgeInsets)fp8;
@end

