/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TLSwizzleProtocol-Protocol.h"

@interface _ABCreateStringWithAddressDictionary (TLSegmentedControl) <TLSwizzleProtocol>
- (void)tl_valueChanged:(id)fp8;
- (void)tl_addTouchTracking;
- (void)tl_swizzleMethods:(id)fp8;
@end

