/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (LPStringTools)
+ (BOOL)tl_isEmpty:(id)fp8;
- (id)tl_removeJSONEscaping;
- (int)tl_indexOf:(id)fp8;
- (id)tl_addURLParamsFromDic:(id)fp8;
- (id)getURLValuesFromArray:(id)fp8;
- (BOOL)tl_stringStartsWith:(id)fp8;
- (BOOL)tl_stringContainsString:(id)fp8;
- (id)tl_capitalizeFirstLetter;
@end

