/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (MagicalAggregation)
+ (id)MR_aggregateOperation:(id)fp8 onAttribute:(id)fp12 withPredicate:(id)fp16 groupBy:(id)fp20;
+ (id)MR_aggregateOperation:(id)fp8 onAttribute:(id)fp12 withPredicate:(id)fp16 groupBy:(id)fp20 inContext:(id)fp24;
+ (id)MR_aggregateOperation:(id)fp8 onAttribute:(id)fp12 withPredicate:(id)fp16;
+ (id)MR_aggregateOperation:(id)fp8 onAttribute:(id)fp12 withPredicate:(id)fp16 inContext:(id)fp20;
+ (BOOL)MR_hasAtLeastOneEntityInContext:(id)fp8;
+ (BOOL)MR_hasAtLeastOneEntity;
+ (unsigned int)MR_countOfEntitiesWithPredicate:(id)fp8 inContext:(id)fp12;
+ (unsigned int)MR_countOfEntitiesWithPredicate:(id)fp8;
+ (unsigned int)MR_countOfEntitiesWithContext:(id)fp8;
+ (unsigned int)MR_countOfEntities;
+ (id)MR_numberOfEntitiesWithPredicate:(id)fp8;
+ (id)MR_numberOfEntitiesWithPredicate:(id)fp8 inContext:(id)fp12;
+ (id)MR_numberOfEntities;
+ (id)MR_numberOfEntitiesWithContext:(id)fp8;
- (id)MR_objectWithMinValueFor:(id)fp8;
- (id)MR_objectWithMinValueFor:(id)fp8 inContext:(id)fp12;
- (id)MR_maxValueFor:(id)fp8;
- (id)MR_minValueFor:(id)fp8;
@end

