/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _ABCreateStringWithAddressDictionary (Base64)
+ (id)stringWithBase64EncodedString:(id)fp8;
- (id)base64DecodedData;
- (id)base64DecodedString;
- (id)base64EncodedString;
- (id)base64EncodedStringWithWrapWidth:(unsigned int)fp8;
@end

