/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSHashTable;

@interface _FBKVOSharedController : _ABCreateStringWithAddressDictionary
{
    NSHashTable *_infos;
    int _lock;
}

+ (id)sharedController;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)unobserve:(id)fp8 infos:(id)fp12;
- (void)unobserve:(id)fp8 info:(id)fp12;
- (void)observe:(id)fp8 info:(id)fp12;
- (id)debugDescription;
- (id)init;

@end

