/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class FBKVOController, NSString;

@interface _FBKVOInfo : _ABCreateStringWithAddressDictionary
{
    FBKVOController *_controller;
    NSString *_keyPath;
    unsigned int _options;
    SEL _action;
    void *_context;
    id _block;
}

- (void).cxx_destruct;
- (id)debugDescription;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (id)initWithController:(id)fp8 keyPath:(id)fp12;
- (id)initWithController:(id)fp8 keyPath:(id)fp12 options:(unsigned int)fp16 context:(void *)fp20;
- (id)initWithController:(id)fp8 keyPath:(id)fp12 options:(unsigned int)fp16 action:(SEL)fp20;
- (id)initWithController:(id)fp8 keyPath:(id)fp12 options:(unsigned int)fp16 block:(id)fp(null);
- (id)initWithController:(id)fp8 keyPath:(id)fp12 options:(unsigned int)fp16 block:(id)fp(null) action:(void)fp20 context:(SEL)fp24;

@end

