/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBSDKErrorRecoveryAttempter.h"

@interface _FBSDKTemporaryErrorRecoveryAttempter : FBSDKErrorRecoveryAttempter
{
}

- (void)attemptRecoveryFromError:(id)fp8 optionIndex:(unsigned int)fp12 delegate:(id)fp16 didRecoverSelector:(SEL)fp20 contextInfo:(void *)fp24;

@end

