/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _TNDRMatch : _ABCreateStringWithAddressDictionary
{
}

+ (id)fetchFetchRequest:(id)fp8 error:(id *)fp12;
+ (id)fetchFetchRequest:(id)fp8;
+ (id)keyPathsForValuesAffectingValueForKey:(id)fp8;
+ (id)entityInManagedObjectContext:(id)fp8;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)fp8;
- (id)messagesSet;
- (id)listsSet;
- (id)allMembersSet;
- (void)setPrimitiveViewedValue:(BOOL)fp8;
- (BOOL)primitiveViewedValue;
- (void)setViewedValue:(BOOL)fp8;
- (BOOL)viewedValue;
- (void)setPrimitiveSynchronizingValue:(BOOL)fp8;
- (BOOL)primitiveSynchronizingValue;
- (void)setSynchronizingValue:(BOOL)fp8;
- (BOOL)synchronizingValue;
- (void)setPrimitiveServerMessageCountValue:(short)fp8;
- (short)primitiveServerMessageCountValue;
- (void)setServerMessageCountValue:(short)fp8;
- (short)serverMessageCountValue;
- (void)setPrimitiveRequestedValue:(BOOL)fp8;
- (BOOL)primitiveRequestedValue;
- (void)setRequestedValue:(BOOL)fp8;
- (BOOL)requestedValue;
- (void)setPrimitiveNeedsSynchronizationValue:(BOOL)fp8;
- (BOOL)primitiveNeedsSynchronizationValue;
- (void)setNeedsSynchronizationValue:(BOOL)fp8;
- (BOOL)needsSynchronizationValue;
- (void)setPrimitiveMutedValue:(BOOL)fp8;
- (BOOL)primitiveMutedValue;
- (void)setMutedValue:(BOOL)fp8;
- (BOOL)mutedValue;
- (void)setPrimitiveMatchmakerPendingValue:(BOOL)fp8;
- (BOOL)primitiveMatchmakerPendingValue;
- (void)setMatchmakerPendingValue:(BOOL)fp8;
- (BOOL)matchmakerPendingValue;
- (void)setPrimitiveIsSuperLikeMatchValue:(BOOL)fp8;
- (BOOL)primitiveIsSuperLikeMatchValue;
- (void)setIsSuperLikeMatchValue:(BOOL)fp8;
- (BOOL)isSuperLikeMatchValue;
- (void)setPrimitiveIsIndexedInSpotlightValue:(BOOL)fp8;
- (BOOL)primitiveIsIndexedInSpotlightValue;
- (void)setIsIndexedInSpotlightValue:(BOOL)fp8;
- (BOOL)isIndexedInSpotlightValue;
- (void)setPrimitiveIsExpiredValue:(BOOL)fp8;
- (BOOL)primitiveIsExpiredValue;
- (void)setIsExpiredValue:(BOOL)fp8;
- (BOOL)isExpiredValue;
- (void)setPrimitiveGroupMatchValue:(BOOL)fp8;
- (BOOL)primitiveGroupMatchValue;
- (void)setGroupMatchValue:(BOOL)fp8;
- (BOOL)groupMatchValue;
- (void)setPrimitiveFollowingValue:(BOOL)fp8;
- (BOOL)primitiveFollowingValue;
- (void)setFollowingValue:(BOOL)fp8;
- (BOOL)followingValue;
- (id)objectID;

@end

