/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _TNDRMatchmakerMatch : _ABCreateStringWithAddressDictionary
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)fp8;
+ (id)entityInManagedObjectContext:(id)fp8;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)fp8;
- (id)friendsSet;
- (void)setPrimitivePendingValue:(BOOL)fp8;
- (BOOL)primitivePendingValue;
- (void)setPendingValue:(BOOL)fp8;
- (BOOL)pendingValue;
- (id)objectID;

@end

