/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface _TNDRMessage : _ABCreateStringWithAddressDictionary
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)fp8;
+ (id)entityInManagedObjectContext:(id)fp8;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)fp8;
- (void)setPrimitiveViewedValue:(BOOL)fp8;
- (BOOL)primitiveViewedValue;
- (void)setViewedValue:(BOOL)fp8;
- (BOOL)viewedValue;
- (void)setPrimitiveLikedValue:(BOOL)fp8;
- (BOOL)primitiveLikedValue;
- (void)setLikedValue:(BOOL)fp8;
- (BOOL)likedValue;
- (void)setPrimitiveHasErrorValue:(BOOL)fp8;
- (BOOL)primitiveHasErrorValue;
- (void)setHasErrorValue:(BOOL)fp8;
- (BOOL)hasErrorValue;
- (id)objectID;

@end

