/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMethodSignature;

@interface A2BlockInvocation : _ABCreateStringWithAddressDictionary
{
    NSMethodSignature *_methodSignature;
    id _block;
    NSMethodSignature *_blockSignature;
}

+ (id)methodSignatureForBlock:(id)fp8;
+ (id)methodSignatureForBlockSignature:(id)fp8;
+ (id)typeSignatureForBlock:(id)fp8;
+ (BOOL)isSignature:(id)fp8 compatibleWithSignature:(id)fp12;
- (id)blockSignature;
- (id)block;
- (id)methodSignature;
- (void).cxx_destruct;
- (BOOL)invokeWithInvocation:(id)fp8 returnValue:(out id *)fp12;
- (void)invokeWithInvocation:(id)fp8;
- (BOOL)invokeWithInvocation:(id)fp8 returnValue:(out id *)fp12 setOnInvocation:(BOOL)fp16;
- (id)initWithBlock:(id)fp8 methodSignature:(id)fp12;
- (id)initWithBlock:(id)fp8;
- (id)initWithBlock:(id)fp8 methodSignature:(id)fp12 blockSignature:(id)fp16;

@end

