/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "A2DynamicDelegate.h"

@interface A2DynamicUITextFieldDelegate : A2DynamicDelegate
{
}

- (BOOL)textFieldShouldReturn:(id)fp8;
- (BOOL)textFieldShouldClear:(id)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (void)textFieldDidEndEditing:(id)fp8;
- (BOOL)textFieldShouldEndEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;

@end

