/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "A2DynamicDelegate.h"

@interface A2DynamicClassDelegate : A2DynamicDelegate
{
    Class _proxiedClass;
}

- (void)setProxiedClass:(Class)fp8;
- (Class)proxiedClass;
- (void).cxx_destruct;
- (void)removeBlockImplementationForClassMethod:(SEL)fp8;
- (void)implementClassMethod:(SEL)fp8 withBlock:(id)fp12;
- (id)blockImplementationForClassMethod:(SEL)fp8;
- (void)forwardInvocation:(id)fp8;
- (unsigned int)hash;
- (id)description;
- (id)methodSignatureForSelector:(SEL)fp8;
- (Class)class;
- (BOOL)respondsToSelector:(SEL)fp8;
- (BOOL)isEqual:(id)fp8;
- (BOOL)isClassProxy;

@end

