/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "A2DynamicDelegate.h"

#import "MFMessageComposeViewControllerDelegate-Protocol.h"

@interface A2DynamicMFMessageComposeViewControllerDelegate : A2DynamicDelegate <MFMessageComposeViewControllerDelegate>
{
}

- (void)messageComposeViewController:(id)fp8 didFinishWithResult:(int)fp12;

@end

