/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABKButton.h"

@class NSString;

@interface ABKAppPurchaseButton : ABKButton
{
    BOOL _universal;
    float _price;
    NSString *_displayPrice;
}

- (id)displayPrice;
- (float)price;
- (BOOL)universal;
- (void).cxx_destruct;
- (void)setUniversal:(BOOL)fp8;
- (void)setPriceText:(id)fp8;
- (void)setDisplayPrice:(id)fp8;
- (void)setPrice:(float)fp8;
- (void)updateInsetsAndImage;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;

@end

