/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface ABKAttributionData : _ABCreateStringWithAddressDictionary
{
    NSString *_network;
    NSString *_campaign;
    NSString *_adGroup;
    NSString *_creative;
}

- (id)creative;
- (id)adGroup;
- (id)campaign;
- (id)network;
- (void).cxx_destruct;
- (id)proxyForJson;
- (id)initWithNetwork:(id)fp8 campaign:(id)fp12 adGroup:(id)fp16 creative:(id)fp20;

@end

