/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface ABKBaseLocationProvider : _ABCreateStringWithAddressDictionary
{
    BOOL _isAuthorizedToPromptLocationAuthorization;
}

+ (BOOL)isValidLocationAndAccurateEnough:(id)fp8;
+ (id)getLocationDictionaryWithLocation:(id)fp8;
+ (BOOL)isLocationLinkedAndEnabled;
+ (BOOL)isCoreLocationLinked;
+ (Class)getLocationManagerClass;
- (void)setIsAuthorizedToPromptLocationAuthorization:(BOOL)fp8;
- (BOOL)isAuthorizedToPromptLocationAuthorization;

@end

