/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface ABKBarButtonItem : _ABCreateStringWithAddressDictionary
{
}

- (void)checkAndApplyNUITheming;
- (id)initWithTitle:(id)fp8 style:(int)fp12 target:(id)fp16 action:(SEL)fp20;
- (id)initWithCoder:(id)fp8;
- (id)init;

@end

