/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABKCardCell.h"

@class ABKThemableCardBodyLabel, ABKThemableCardStaticLinkLabel, ABKThemableCardTitleBackgroundView, ABKThemableCardTitleLabel, UIImageView;

@interface ABKCaptionedMessageCardCell : ABKCardCell
{
    UIImageView *_cardImage;
    ABKThemableCardTitleBackgroundView *_backgroundGradient;
    ABKThemableCardTitleLabel *_title;
    ABKThemableCardBodyLabel *_cardDescription;
    ABKThemableCardStaticLinkLabel *_link;
}

- (void)setLink:(id)fp8;
- (id)link;
- (void)setCardDescription:(id)fp8;
- (id)cardDescription;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setBackgroundGradient:(id)fp8;
- (id)backgroundGradient;
- (void)setCardImage:(id)fp8;
- (id)cardImage;
- (void).cxx_destruct;
- (void)layoutSubviews;

@end

