/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABKEvent.h"

@class NSString;

@interface ABKCustomStringAttributeEvent : ABKEvent
{
    NSString *_customAttributeKey;
    NSString *_value;
}

- (void)setValue:(id)fp8;
- (id)value;
- (void)setCustomAttributeKey:(id)fp8;
- (id)customAttributeKey;
- (void).cxx_destruct;
- (id)getDataAsJson;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCustomAttributeKey:(id)fp8 value:(id)fp12;

@end

