/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABKEvent.h"

@class NSString;

@interface ABKCardImpressionEvent : ABKEvent
{
    NSString *_cardImpressionCardsId;
}

- (void)setCardImpressionCardsId:(id)fp8;
- (id)cardImpressionCardsId;
- (void).cxx_destruct;
- (id)getDataAsJson;
- (id)getType;
- (id)initWithCardId:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;

@end

