/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface ABKEmailValidator : _ABCreateStringWithAddressDictionary
{
    NSString *_emailAddress;
}

- (void)setEmailAddress:(id)fp8;
- (id)emailAddress;
- (void).cxx_destruct;
- (BOOL)valid;
- (id)initWithEmail:(id)fp8;

@end

