/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, NSDictionary;

@interface ABKFacebookUser : _ABCreateStringWithAddressDictionary
{
    NSDictionary *_facebookUserDictionary;
    int _numberOfFriends;
    NSArray *_likes;
}

- (id)likes;
- (int)numberOfFriends;
- (id)facebookUserDictionary;
- (void).cxx_destruct;
- (id)proxyForJson;
- (id)init;
- (id)initWithFacebookUserDictionary:(id)fp8 numberOfFriends:(int)fp12 likes:(id)fp16;

@end

