/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface ABKFileSystemUtilities : _ABCreateStringWithAddressDictionary
{
}

+ (id)createCleanDocumentDirectoryWithRelativePath:(id)fp8;
+ (BOOL)removeItemAtPath:(id)fp8;
+ (BOOL)createDirectoryPath:(id)fp8;
+ (BOOL)createWritableFileWithPath:(id)fp8;
+ (BOOL)directoryExistsAtPath:(id)fp8;
+ (BOOL)fileExistsAtPath:(id)fp8;

@end

