/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UINavigationControllerDelegate-Protocol.h"

@class ABKFeedViewController, NSString;

@interface ABKFeedViewControllerGenericContext : _ABCreateStringWithAddressDictionary <UINavigationControllerDelegate>
{
    ABKFeedViewController *_feedViewController;
    NSString *_retainedNavigationBarTitle;
}

- (void)setRetainedNavigationBarTitle:(id)fp8;
- (id)retainedNavigationBarTitle;
- (void)setFeedViewController:(id)fp8;
- (id)feedViewController;
- (void).cxx_destruct;
- (void)setDisableUnreadIndicator:(BOOL)fp8;
- (BOOL)disableUnreadIndicator;
- (void)setCategories:(unsigned int)fp8;
- (unsigned int)categories;
- (id)appboyDelegate;
- (void)setAppboyDelegate:(id)fp8;
- (float)minimumCardMarginForiPad;
- (float)minimumCardMarginForiPhone;
- (float)cardWidthForiPad;
- (float)cardWidthForiPhone;
- (void)setMinimumCardMarginForiPad:(float)fp8;
- (void)setMinimumCardMarginForiPhone:(float)fp8;
- (void)setCardWidthForiPad:(float)fp8;
- (void)setCardWidthForiPhone:(float)fp8;
- (id)navigationBarTitle;
- (void)setNavigationBarTitle:(id)fp8;
- (void)closeButtonPressed:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)navigationController:(id)fp8 willShowViewController:(id)fp12 animated:(BOOL)fp16;
- (void)viewDidLoad;
- (void)setupNavigationBarAndFeedViewController;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithCoder:(id)fp8;

@end

