/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class ABKFeedbackThemableIssueLabel, ABKFeedbackThemableMessageLabel, UIButton, UITextView;

@interface ABKFeedbackContentView : _ABCreateStringWithAddressDictionary
{
    UITextView *_feedbackTextView;
    UIButton *_issueButton;
    ABKFeedbackThemableMessageLabel *_messageLabel;
    ABKFeedbackThemableIssueLabel *_issueLabel;
}

- (void)setIssueLabel:(id)fp8;
- (id)issueLabel;
- (void)setMessageLabel:(id)fp8;
- (id)messageLabel;
- (void)setIssueButton:(id)fp8;
- (id)issueButton;
- (void)setFeedbackTextView:(id)fp8;
- (id)feedbackTextView;
- (void).cxx_destruct;
- (void)issueButtonTapped:(id)fp8;
- (void)startPositionY:(float)fp8 endPositionY:(float)fp12;
- (id)getNuiRendererClass;
- (void)awakeFromNib;
- (void)checkAndApplyNUITheming;
- (id)initWithCoder:(id)fp8;
- (id)init;
- (id)initWithFrame:(struct CGRect)fp8;

@end

