/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UITextFieldDelegate-Protocol.h"

@class ABKFeedbackContentView, ABKFeedbackThemableEmailAddressBarView, ABKSpinnerView;

@interface ABKFeedbackViewController : _ABCreateStringWithAddressDictionary <UITextFieldDelegate>
{
    id _delegate;
    ABKFeedbackContentView *_feedbackContentView;
    ABKFeedbackThemableEmailAddressBarView *_feedbackEmailAddressBar;
    ABKSpinnerView *_spinnerView;
    struct CGRect _keyboardRect;
}

- (void)setKeyboardRect:(struct CGRect)fp8;
- (struct CGRect)keyboardRect;
- (void)setSpinnerView:(id)fp8;
- (id)spinnerView;
- (void)setFeedbackEmailAddressBar:(id)fp8;
- (id)feedbackEmailAddressBar;
- (void)setFeedbackContentView:(id)fp8;
- (id)feedbackContentView;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)networkNotAvailable:(id)fp8;
- (void)performSelectorOnDelegate:(SEL)fp8;
- (void)feedbackWasSent:(id)fp8;
- (void)sendButtonTapped:(id)fp8;
- (void)cancelButtonTapped:(id)fp8;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardWillShow:(id)fp8;
- (void)relayoutSubViewsWithKeyboardHeight;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)dealloc;
- (void)setupEmailAddressBarView;
- (void)updateContentViewFrame;
- (void)viewDidLoad;
- (void)removeSpinner;
- (void)removeSpinner:(id)fp8;
- (void)putOnSpinnerWithTimer:(BOOL)fp8;
- (void)setDelegate:(id)fp8;

@end

