/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSURLConnectionDelegate-Protocol.h"

@class NSURL;

@interface ABKItunesStoreProduct : _ABCreateStringWithAddressDictionary <NSURLConnectionDelegate>
{
    NSURL *_referenceURL;
    NSURL *_iTunesURL;
    long long _identifier;
}

- (void)setITunesURL:(id)fp8;
- (id)iTunesURL;
- (void)setIdentifier:(long long)fp8;
- (long long)identifier;
- (void)setReferenceURL:(id)fp8;
- (id)referenceURL;
- (void).cxx_destruct;
- (void)connectionDidFinishLoading:(id)fp8;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)openInAppStoreUsingReferenceURL;
- (id)initWithReferenceURL:(id)fp8 andIdentifier:(long long)fp12;

@end

