/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABKInAppMessageImmersiveViewController.h"

@class ABKView, NSLayoutConstraint;

@interface ABKInAppMessageFullViewController : ABKInAppMessageImmersiveViewController
{
    ABKView *_textButtonView;
    NSLayoutConstraint *_imageTrailingConstraint;
    NSLayoutConstraint *_imageBottomConstraint;
    NSLayoutConstraint *_inAppMessageLabelLeadingConstraint;
    NSLayoutConstraint *_inAppMessageLabelTrailingConstraint;
}

- (void)setInAppMessageLabelTrailingConstraint:(id)fp8;
- (id)inAppMessageLabelTrailingConstraint;
- (void)setInAppMessageLabelLeadingConstraint:(id)fp8;
- (id)inAppMessageLabelLeadingConstraint;
- (void)setImageBottomConstraint:(id)fp8;
- (id)imageBottomConstraint;
- (void)setImageTrailingConstraint:(id)fp8;
- (id)imageTrailingConstraint;
- (void)setTextButtonView:(id)fp8;
- (id)textButtonView;
- (void).cxx_destruct;
- (void)moveInAppMessageViewOnScreen:(struct CGRect)fp8;
- (void)moveInAppMessageViewOffScreen:(struct CGRect)fp8;
- (void)updateConstraintsForOrientation:(int)fp8;
- (void)viewWillTransitionToSize:(struct CGSize)fp8 withTransitionCoordinator:(id)fp16;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)loadView;
- (void)viewDidLoad;
- (void)adjustInAppMessageLabelHeight;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLayoutSubviews;

@end

