/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class ABKWebViewController, NSURL;

@interface ABKModalWebViewController : _ABCreateStringWithAddressDictionary
{
    ABKWebViewController *_webViewController;
    NSURL *_url;
}

- (void)setUrl:(id)fp8;
- (id)url;
- (void)setWebViewController:(id)fp8;
- (id)webViewController;
- (void).cxx_destruct;
- (id)popViewControllerAnimated:(BOOL)fp8;
- (void)closeButtonPressed:(id)fp8;
- (void)viewDidLoad;

@end

