/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface ABKPushNotificationManager : _ABCreateStringWithAddressDictionary
{
}

- (void)registerForDataUpdateWithFetchCompletionHandler:(id)fp(null);
- (BOOL)pushNotificationWasSentFromAppboy:(id)fp8;
- (void)handleURIFromPushNotification:(id)fp8 completionHandler:(id)fp(null);
- (id)parseURIStringFromPushNotification:(id)fp8;
- (id)getCampaignIDIfOpenedByPushNotification:(id)fp8;
- (void)clearBadgeCount;

@end

