/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABKEvent.h"

@class NSDecimalNumber, NSDictionary, NSNumber, NSString;

@interface ABKPurchaseMade : ABKEvent
{
    NSString *_currencyCode;
    NSString *_productIdentifier;
    NSDecimalNumber *_price;
    NSNumber *_quantity;
    NSDictionary *_properties;
}

+ (id)performRounding:(id)fp8;
- (void)setProperties:(id)fp8;
- (id)properties;
- (void)setQuantity:(id)fp8;
- (id)quantity;
- (id)price;
- (void)setProductIdentifier:(id)fp8;
- (id)productIdentifier;
- (void)setCurrencyCode:(id)fp8;
- (id)currencyCode;
- (void).cxx_destruct;
- (id)getDataAsJson;
- (id)getType;
- (void)encodeWithCoder:(id)fp8;
- (void)setPrice:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithProductIdentifier:(id)fp8 inCurrency:(id)fp12 atPrice:(id)fp16 withQuantity:(id)fp20 andProperties:(id)fp24;

@end

