/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface ABKPlaceIQDeviceUtilities : _ABCreateStringWithAddressDictionary
{
}

+ (id)getDeviceIDHashWithDeviceID:(id)fp8;
+ (BOOL)hasPlaceIQDeviceIdChanged;
+ (void)savePlaceIQDeviceID:(id)fp8;
+ (id)getAppropriateDeviceIDForPlaceIQ;

@end

