/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableArray;

@interface ABKRequestQueue : _ABCreateStringWithAddressDictionary
{
    NSMutableArray *_queue;
}

- (id)queue;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)count;
- (BOOL)isEmpty;
- (void)clear;
- (id)take;
- (id)peek;
- (void)add:(id)fp8;
- (void)addToFront:(id)fp8;
- (id)init;
- (id)takeRequestForUser:(id)fp8;
- (void)removeRequest:(id)fp8;

@end

