/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface ABKResponseError : _ABCreateStringWithAddressDictionary
{
    NSString *_type;
    NSString *_message;
}

- (void)setMessage:(id)fp8;
- (id)message;
- (void)setType:(id)fp8;
- (id)type;
- (void).cxx_destruct;
- (void)setValue:(id)fp8 forUndefinedKey:(id)fp12;

@end

