/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABKBaseLocationProvider.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class ABKServerConfig, CLLocation, CLLocationManager;

@interface ABKSignificantChangeLocationProvider : ABKBaseLocationProvider <CLLocationManagerDelegate>
{
    BOOL _isCollectingLocation;
    BOOL _isLocationCollectionServerEnabled;
    ABKServerConfig *_serverConfig;
    CLLocationManager *_locationManager;
    CLLocation *_lastLocation;
    int _distanceFilter;
    double _timeFilter;
}

- (void)setTimeFilter:(double)fp8;
- (double)timeFilter;
- (void)setDistanceFilter:(int)fp8;
- (int)distanceFilter;
- (void)setIsLocationCollectionServerEnabled:(BOOL)fp8;
- (BOOL)isLocationCollectionServerEnabled;
- (void)setIsCollectingLocation:(BOOL)fp8;
- (BOOL)isCollectingLocation;
- (void)setLastLocation:(id)fp8;
- (id)lastLocation;
- (void)setLocationManager:(id)fp8;
- (id)locationManager;
- (void)setServerConfig:(id)fp8;
- (id)serverConfig;
- (void).cxx_destruct;
- (void)tryPromptForAlwaysAuthorization;
- (void)locationManager:(id)fp8 didChangeAuthorizationStatus:(int)fp12;
- (void)stopUpdatingLocationCollection;
- (void)startSignificantChangeCollection;
- (BOOL)shouldLogLocation:(id)fp8;
- (void)locationManager:(id)fp8 didUpdateLocations:(id)fp12;
- (void)setConfigValuesFromServerConfig;
- (void)locationServerConfigUpdated:(id)fp8;
- (void)updateConfigFromAppboyOptions:(id)fp8;
- (void)dealloc;
- (void)singleLocationLogged:(id)fp8;
- (id)initWithServerConfig:(id)fp8 andAppboyOptions:(id)fp12;

@end

