/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface ABKTwitterUser : _ABCreateStringWithAddressDictionary
{
    NSString *_userDescription;
    NSString *_twitterName;
    NSString *_profileImageUrl;
    NSString *_screenName;
    int _followersCount;
    int _friendsCount;
    int _statusesCount;
    int _twitterID;
}

- (void)setTwitterID:(int)fp8;
- (int)twitterID;
- (void)setStatusesCount:(int)fp8;
- (int)statusesCount;
- (void)setFriendsCount:(int)fp8;
- (int)friendsCount;
- (void)setFollowersCount:(int)fp8;
- (int)followersCount;
- (void)setScreenName:(id)fp8;
- (id)screenName;
- (void)setProfileImageUrl:(id)fp8;
- (id)profileImageUrl;
- (void)setTwitterName:(id)fp8;
- (id)twitterName;
- (void)setUserDescription:(id)fp8;
- (id)userDescription;
- (void).cxx_destruct;
- (id)proxyForJson;
- (id)init;

@end

