/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface ABKViewUtilities : _ABCreateStringWithAddressDictionary
{
}

+ (void)downloadImage:(id)fp8 intoView:(id)fp12 placeholderIfFail:(id)fp16 contenMode:(int)fp20;
+ (id)fetchImageIfCached:(id)fp8;
+ (BOOL)openProtocolURL:(id)fp8;
+ (BOOL)isAProtocolURL:(id)fp8;
+ (void)stackViews:(id)fp8 startYPosition:(float)fp12 padding:(float)fp16 spacing:(float)fp20 maxTotalHeight:(float)fp24;
+ (void)setViewCenterX:(id)fp8 centerX:(float)fp12;
+ (void)setViewCenterY:(id)fp8 centerY:(float)fp12;
+ (void)setViewWidth:(id)fp8 width:(float)fp12;
+ (void)setViewHeight:(id)fp8 height:(float)fp12;
+ (void)setViewOriginX:(id)fp8 originX:(float)fp12;
+ (void)setViewOriginY:(id)fp8 originY:(float)fp12;

@end

