/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface ABKZAMain : _ABCreateStringWithAddressDictionary
{
    NSString *_path;
    NSString *_fileName;
    void *_zip;
}

+ (id)dateWithMicrosoftDOSFormat:(unsigned long)fp8;
+ (BOOL)createZipFileAtPath:(id)fp8 withContentsOfDirectory:(id)fp12 keepParentDirectory:(BOOL)fp16;
+ (BOOL)createZipFileAtPath:(id)fp8 withContentsOfDirectory:(id)fp12;
+ (BOOL)createZipFileAtPath:(id)fp8 withFilesAtPaths:(id)fp12;
+ (BOOL)unzipFileAtPath:(id)fp8 toDestination:(id)fp12 overwrite:(BOOL)fp16 password:(id)fp20 error:(id)fp24 delegate:(id)fp28 progressHandler:(id)fp(null) completionHandler:(void)fp32;
+ (BOOL)unzipFileAtPath:(id)fp8 toDestination:(id)fp12 progressHandler:(id)fp(null) completionHandler:(void)fp16;
+ (BOOL)unzipFileAtPath:(id)fp8 toDestination:(id)fp12 overwrite:(BOOL)fp16 password:(id)fp20 progressHandler:(id)fp(null) completionHandler:(void)fp24;
+ (BOOL)unzipFileAtPath:(id)fp8 toDestination:(id)fp12 overwrite:(BOOL)fp16 password:(id)fp20 error:(id)fp24 delegate:(id)fp28;
+ (BOOL)unzipFileAtPath:(id)fp8 toDestination:(id)fp12 delegate:(id)fp16;
+ (BOOL)unzipFileAtPath:(id)fp8 toDestination:(id)fp12 overwrite:(BOOL)fp16 password:(id)fp20 error:(id)fp24;
+ (BOOL)unzipFileAtPath:(id)fp8 toDestination:(id)fp12;
- (void).cxx_destruct;
- (BOOL)close;
- (BOOL)writeData:(id)fp8 fileName:(id)fp12;
- (BOOL)writeFileAtPath:(id)fp8 withFileName:(id)fp12;
- (BOOL)writeFile:(id)fp8;
- (BOOL)writeFolderAtPath:(id)fp8 withFolderName:(id)fp12;
- (void)zipInformation:(CDAnonymousStruct5 *)fp8 setDate:(id)fp12;
- (BOOL)open;
- (id)initWithPath:(id)fp8;

@end

