/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AFHTTPResponseSerializer.h"

@class NSArray;

@interface AFCompoundResponseSerializer : AFHTTPResponseSerializer
{
    NSArray *_responseSerializers;
}

+ (id)compoundSerializerWithResponseSerializers:(id)fp8;
- (void)setResponseSerializers:(id)fp8;
- (id)responseSerializers;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)responseObjectForResponse:(id)fp8 data:(id)fp12 error:(id *)fp16;

@end

