/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "AFURLResponseSerialization-Protocol.h"

@class NSIndexSet, NSSet;

@interface AFHTTPResponseSerializer : _ABCreateStringWithAddressDictionary <AFURLResponseSerialization>
{
    unsigned int _stringEncoding;
    NSIndexSet *_acceptableStatusCodes;
    NSSet *_acceptableContentTypes;
}

+ (BOOL)supportsSecureCoding;
+ (id)serializer;
- (void)setAcceptableContentTypes:(id)fp8;
- (id)acceptableContentTypes;
- (void)setAcceptableStatusCodes:(id)fp8;
- (id)acceptableStatusCodes;
- (void)setStringEncoding:(unsigned int)fp8;
- (unsigned int)stringEncoding;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)responseObjectForResponse:(id)fp8 data:(id)fp12 error:(id *)fp16;
- (BOOL)validateResponse:(id)fp8 data:(id)fp12 error:(id *)fp16;
- (id)init;

@end

