/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AFHTTPRequestSerializer.h"

@interface AFPropertyListRequestSerializer : AFHTTPRequestSerializer
{
    unsigned int _format;
    unsigned int _writeOptions;
}

+ (id)serializerWithFormat:(unsigned int)fp8 writeOptions:(unsigned int)fp12;
+ (id)serializer;
- (void)setWriteOptions:(unsigned int)fp8;
- (unsigned int)writeOptions;
- (void)setFormat:(unsigned int)fp8;
- (unsigned int)format;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)requestBySerializingRequest:(id)fp8 withParameters:(id)fp12 error:(id *)fp16;

@end

