/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "AFMultipartFormData-Protocol.h"

@class AFMultipartBodyStream, NSMutableURLRequest, NSString;

@interface AFStreamingMultipartFormData : _ABCreateStringWithAddressDictionary <AFMultipartFormData>
{
    NSMutableURLRequest *_request;
    unsigned int _stringEncoding;
    NSString *_boundary;
    AFMultipartBodyStream *_bodyStream;
}

- (void)setBodyStream:(id)fp8;
- (id)bodyStream;
- (void)setBoundary:(id)fp8;
- (id)boundary;
- (void)setStringEncoding:(unsigned int)fp8;
- (unsigned int)stringEncoding;
- (void)setRequest:(id)fp8;
- (id)request;
- (void).cxx_destruct;
- (id)requestByFinalizingMultipartFormData;
- (void)throttleBandwidthWithPacketSize:(unsigned int)fp8 delay:(double)fp12;
- (void)appendPartWithHeaders:(id)fp8 body:(id)fp12;
- (void)appendPartWithFormData:(id)fp8 name:(id)fp12;
- (void)appendPartWithFileData:(id)fp8 name:(id)fp12 fileName:(id)fp16 mimeType:(id)fp20;
- (void)appendPartWithInputStream:(id)fp8 name:(id)fp12 fileName:(id)fp16 length:(long long)fp20 mimeType:(id)fp28;
- (BOOL)appendPartWithFileURL:(id)fp8 name:(id)fp12 fileName:(id)fp16 mimeType:(id)fp20 error:(id *)fp24;
- (BOOL)appendPartWithFileURL:(id)fp8 name:(id)fp12 error:(id *)fp16;
- (id)initWithURLRequest:(id)fp8 stringEncoding:(unsigned int)fp12;

@end

