/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@protocol AFURLRequestSerialization <NSObject, NSSecureCoding, NSCopying>
- (id)requestBySerializingRequest:(id)fp8 withParameters:(id)fp12 error:(id *)fp16;
@end

