/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableArray, NSObject;

@interface BFCancellationToken : _ABCreateStringWithAddressDictionary
{
    BOOL _cancellationRequested;
    BOOL _disposed;
    NSMutableArray *_registrations;
    NSObject *_lock;
}

- (void)setDisposed:(BOOL)fp8;
- (BOOL)disposed;
- (void)setLock:(id)fp8;
- (id)lock;
- (void)setRegistrations:(id)fp8;
- (id)registrations;
- (void).cxx_destruct;
- (void)throwIfDisposed;
- (void)dispose;
- (void)cancelAfterDelay:(int)fp8;
- (void)cancelPrivate;
- (void)unregisterRegistration:(id)fp8;
- (id)registerCancellationObserverWithBlock:(id)fp(null);
- (void)notifyCancellation:(id)fp8;
- (void)cancel;
- (BOOL)isCancellationRequested;
- (id)init;

@end

