/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSCondition, NSError, NSException, NSMutableArray, NSObject;

@interface BFTask : _ABCreateStringWithAddressDictionary
{
    id _result;
    NSError *_error;
    NSException *_exception;
    BOOL _cancelled;
    BOOL _faulted;
    BOOL _completed;
    NSObject *_lock;
    NSCondition *_condition;
    NSMutableArray *_callbacks;
}

+ (id)taskFromExecutor:(id)fp8 withBlock:(id)fp(null);
+ (id)taskWithDelay:(int)fp8 cancellationToken:(id)fp12;
+ (id)taskWithDelay:(int)fp8;
+ (id)taskForCompletionOfAnyTask:(id)fp8;
+ (id)taskForCompletionOfAllTasksWithResults:(id)fp8;
+ (id)taskForCompletionOfAllTasks:(id)fp8;
+ (id)cancelledTask;
+ (id)taskWithException:(id)fp8;
+ (id)taskWithError:(id)fp8;
+ (id)taskWithResult:(id)fp8;
- (void)setCallbacks:(id)fp8;
- (id)callbacks;
- (void)setCondition:(id)fp8;
- (id)condition;
- (void)setLock:(id)fp8;
- (id)lock;
- (void)setCompleted:(BOOL)fp8;
- (void)setFaulted:(BOOL)fp8;
- (void)setCancelled:(BOOL)fp8;
- (void).cxx_destruct;
- (id)description;
- (void)waitUntilFinished;
- (void)warnOperationOnMainThread;
- (id)continueWithSuccessBlock:(id)fp(null) cancellationToken:(void)fp8;
- (id)continueWithSuccessBlock:(id)fp(null);
- (id)continueWithExecutor:(id)fp8 successBlock:(id)fp(null) cancellationToken:(void)fp12;
- (id)continueWithExecutor:(id)fp8 withSuccessBlock:(id)fp(null);
- (id)continueWithBlock:(id)fp(null) cancellationToken:(void)fp8;
- (id)continueWithBlock:(id)fp(null);
- (id)continueWithExecutor:(id)fp8 block:(id)fp(null) cancellationToken:(void)fp12;
- (id)continueWithExecutor:(id)fp8 withBlock:(id)fp(null);
- (void)runContinuations;
- (BOOL)isCompleted;
- (BOOL)trySetCancelled;
- (BOOL)isFaulted;
- (BOOL)isCancelled;
- (BOOL)trySetException:(id)fp8;
- (id)exception;
- (BOOL)trySetError:(id)fp8;
- (id)error;
- (BOOL)trySetResult:(id)fp8;
- (id)result;
- (id)initCancelled;
- (id)initWithException:(id)fp8;
- (id)initWithError:(id)fp8;
- (id)initWithResult:(id)fp8;
- (id)init;

@end

