/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "BFAppLinkResolving-Protocol.h"

@interface BFWebViewAppLinkResolver : _ABCreateStringWithAddressDictionary <BFAppLinkResolving>
{
}

+ (id)sharedInstance;
- (id)appLinkFromALData:(id)fp8 destination:(id)fp12;
- (id)getALDataFromLoadedPage:(id)fp8;
- (id)parseALData:(id)fp8;
- (id)appLinkFromURLInBackground:(id)fp8;
- (id)followRedirects:(id)fp8;

@end

