/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CLSAnswersPredefinedEvent.h"

@interface CLSAnswersStartCheckoutEvent : CLSAnswersPredefinedEvent
{
}

- (id)initWithPrice:(id)fp8 currency:(id)fp12 itemCount:(id)fp16 customAttributes:(id)fp20;

@end

