/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CLSAnswersPredefinedEvent.h"

@interface CLSAnswersContentViewEvent : CLSAnswersPredefinedEvent
{
}

- (id)initWithContentName:(id)fp8 contentType:(id)fp12 contentId:(id)fp16 customAttributes:(id)fp20;

@end

