/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CLSAnswersEvent.h"

@interface CLSAnswersCustomEvent : CLSAnswersEvent
{
}

- (id)description;
- (id)initWithName:(id)fp8;
- (id)initWithName:(id)fp8 customAttributes:(id)fp12;
- (id)initWithKey:(id)fp8 metadataDictionary:(id)fp12 customAttributes:(id)fp16;

@end

