/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableSet;

@interface CLSAnalyticsViewControllerTrackingController : _ABCreateStringWithAddressDictionary
{
    BOOL _isTracking;
    id <CLSAnalyticsViewControllerTrackingDelegate> _delegate;
    NSMutableSet *_blackListViewControllerClasses;
}

+ (BOOL)replaceMethodImplementationForClass:(Class)fp8 selector:(SEL)fp12 withImplementation:(void *)fp16 storingOldImplementation:(void **)fp20;
+ (id)sharedInstance;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)cleanUpUIViewControllerSwizzle;
- (void)setUpUIViewControllerSwizzle;
- (BOOL)shouldLogViewController:(id)fp8;
- (BOOL)isBlacklistedViewControllerClass:(Class)fp8;
- (void)removeBlackListViewControllerClass:(Class)fp8;
- (void)addBlackListViewControllerClass:(Class)fp8;
- (void)startTracking;
- (void)disposeSharedInstance;
- (id)init;
- (void)dealloc;

@end

