/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CLSEventLogEvent.h"

@interface CLSAnalyticsMetadataEvent : CLSEventLogEvent
{
}

- (id)metadataJSONData;
- (id)initWithPriority:(unsigned int)fp8 timestamp:(unsigned long long)fp12 key:(id)fp20 payload:(id)fp24;
- (id)initWithPriority:(unsigned int)fp8 timestamp:(unsigned long long)fp12 metadataJSONData:(id)fp20;

@end

