/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CLSAnswersPredefinedEvent.h"

@interface CLSAnswersLoginEvent : CLSAnswersPredefinedEvent
{
}

- (id)initWithLoginMethod:(id)fp8 success:(id)fp12 customAttributes:(id)fp16;

@end

