/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CLSAnswersPredefinedEvent.h"

@interface CLSAnswersPurchaseEvent : CLSAnswersPredefinedEvent
{
}

- (id)initWithPrice:(id)fp8 currency:(id)fp12 success:(id)fp16 itemName:(id)fp20 itemId:(id)fp24 itemType:(id)fp28 customAttributes:(id)fp32;

@end

