/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CLSAnswersPredefinedEvent.h"

@interface CLSAnswersRateEvent : CLSAnswersPredefinedEvent
{
}

- (id)initWithRating:(id)fp8 contentName:(id)fp12 contentType:(id)fp16 contentId:(id)fp20 customAttributes:(id)fp24;

@end

