/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSURLSessionDelegate-Protocol.h"

@class CLSBetaUpdate, FABNetworkClient, NSObject<OS_dispatch_queue>, NSString, NSTimer;

@interface CLSBetaController : _ABCreateStringWithAddressDictionary <NSURLSessionDelegate>
{
    NSString *_betaToken;
    BOOL _checksSuspended;
    BOOL _retrying;
    id <CLSBetaControllerDelegate> _delegate;
    FABNetworkClient *_networkClient;
    CLSBetaUpdate *_activeUpdate;
    NSTimer *_checkSuspensionTimer;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)pinnnedCertificates;
+ (BOOL)isBetaSupported;
- (id)queue;
- (void)setRetrying:(BOOL)fp8;
- (BOOL)retrying;
- (void)setChecksSuspended:(BOOL)fp8;
- (BOOL)checksSuspended;
- (void)setCheckSuspensionTimer:(id)fp8;
- (id)checkSuspensionTimer;
- (void)setActiveUpdate:(id)fp8;
- (id)activeUpdate;
- (id)networkClient;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)applicationWillEnterForeground:(id)fp8;
- (void)fabricSettingsDownloaded:(id)fp8;
- (void)showBetaAlertForUpdate:(id)fp8;
- (void)didGetUpdate:(id)fp8;
- (BOOL)shouldGetUpdates;
- (void)applicationWillEnterForeground;
- (void)allowChecks;
- (void)temporarilySuspendChecks;
- (id)updateWithData:(id)fp8 error:(id *)fp12;
- (void)handledCompletedBetaRequestWithData:(id)fp8 error:(id)fp12 completionBlock:(id)fp(null);
- (void)loadUpdateWithCompletionBlock:(id)fp(null);
- (void)maybeGetUpdate:(id)fp(null);
- (void)checkForUpdate;
- (id)betaUpdateURL;
- (id)APIKey;
- (id)appInstallationSource;
- (id)appInstanceIdentifier;
- (id)appDisplayVersion;
- (id)appBuildVersion;
- (id)appBundleIdentifier;
- (id)betaEndpoint;
- (id)betaUpdateSuspendDurationSecs;
- (id)settings;
- (id)betaToken;
- (void)dealloc;
- (BOOL)start;
- (id)initWithDelegate:(id)fp8;

@end

