/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString, NSURL;

@interface CLSCodeMapping : _ABCreateStringWithAddressDictionary
{
    int _source;
    NSURL *_URL;
    NSString *_sourceName;
}

+ (id)mappingWithURL:(id)fp8;
- (id)sourceName;
- (void)setSource:(int)fp8;
- (int)source;
- (id)URL;
- (void).cxx_destruct;
- (id)initWithURL:(id)fp8;

@end

