/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class CLSMachOBinary, NSBundle;

@interface CLSdSYM : _ABCreateStringWithAddressDictionary
{
    CLSMachOBinary *_binary;
    NSBundle *_bundle;
}

+ (id)dSYMWithURL:(id)fp8;
- (id)bundle;
- (id)binary;
- (void).cxx_destruct;
- (void)enumerateUUIDs:(id)fp(null);
- (id)shortBundleVersion;
- (id)bundleVersion;
- (id)executablePath;
- (id)executableURL;
- (id)bundleIdentifier;
- (id)initWithURL:(id)fp8;

@end

