/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSFileHandle, NSURL;

@interface CLSEventLogFile : _ABCreateStringWithAddressDictionary
{
    NSURL *_fileURL;
    unsigned int _fileSize;
    NSFileHandle *_fileHandle;
}

- (unsigned int)fileSize;
- (id)fileURL;
- (id)readFromFile:(id *)fp8;
- (BOOL)resetFile:(id *)fp8;
- (BOOL)appendData:(id)fp8 error:(id *)fp12;
- (void)closeFileHandle;
- (BOOL)openFileHandleForReading:(id *)fp8;
- (BOOL)openFileHandleForWriting:(id *)fp8;
- (id)init;
- (id)initWithName:(id)fp8 inDirectoryWithURL:(id)fp12;
- (id)initWithURL:(id)fp8;
- (void)dealloc;

@end

