/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSFileManager, NSURL;

@interface CLSEventLogSessionRepository : _ABCreateStringWithAddressDictionary
{
    NSURL *_rootDirectoryURL;
    NSFileManager *_fileManager;
}

+ (id)sessionFragmentDirectoryURLForLogFileURL:(id)fp8;
+ (id)sessionDirectoryURLForSessionFragmentDirectoryURL:(id)fp8;
+ (id)stateDirectoryURLForSessionDirectoryURL:(id)fp8;
+ (BOOL)isPrepDirectoryURL:(id)fp8;
+ (id)prepDirectoryForDirectoryURL:(id)fp8;
+ (id)sessionFragmentDirectoryNameWithIdentifier:(id)fp8 timestamp:(unsigned long long)fp12;
+ (id)sessionDirectoryNameWithIdentifier:(id)fp8 timestamp:(unsigned long long)fp12;
+ (unsigned int)priorityForEventLogFileWithName:(id)fp8;
+ (id)activeEventLogFileNameForPriority:(unsigned int)fp8;
- (BOOL)cleanUpEventLogRepositoryIgnorningSessionFragmentDirectoryURL:(id)fp8 error:(id *)fp12;
- (BOOL)cleanUpStateDirectoryURL:(id)fp8 ignoringSessionFragmentDirectoryURL:(id)fp12 shouldDelete:(char *)fp16 error:(id *)fp20;
- (BOOL)cleanUpSessionDirectoryURL:(id)fp8 ignoringSessionFragmentDirectoryURL:(id)fp12 shouldDelete:(char *)fp16 error:(id *)fp20;
- (BOOL)cleanUpSessionFragmentDirectoryURL:(id)fp8 shouldDelete:(char *)fp12 error:(id *)fp16;
- (BOOL)cleanUpDirectoryURL:(id)fp8 shouldDelete:(char *)fp12 error:(id *)fp16 withCleanUpBlock:(id)fp(null);
- (BOOL)cleanUpLogFileURL:(id)fp8 shouldDelete:(char *)fp12 error:(id *)fp16;
- (id)contentsOfDirectoryURL:(id)fp8 error:(id *)fp12;
- (BOOL)itemURL:(id)fp8 hasPathExtensionMatching:(id)fp12;
- (BOOL)itemURL:(id)fp8 hasNameMatching:(id)fp12;
- (BOOL)isDirectoryURL:(id)fp8;
- (BOOL)deleteItemAtURL:(id)fp8 error:(id *)fp12;
- (BOOL)removeLogFile:(id)fp8 error:(id *)fp12;
- (id)logFileURLsForAllStates:(id *)fp8;
- (id)logFileURLsForSessionFragmentDirectory:(id)fp8 error:(id *)fp12;
- (id)eventLogFileURLForStateName:(id)fp8 sessionIdentifier:(id)fp12 sessionTimestamp:(unsigned long long)fp16 sessionFragmentIdentifier:(id)fp24 sessionFragmentTimestamp:(unsigned long long)fp28 eventPriority:(unsigned int)fp36 error:(id *)fp40;
- (BOOL)removeSessionFragmentDirectory:(id)fp8 error:(id *)fp12;
- (id)sessionFragmentDirectoryURLForStateName:(id)fp8 sessionIdentifier:(id)fp12 sessionTimestamp:(unsigned long long)fp16 sessionFragmentIdentifier:(id)fp24 sessionFragmentTimestamp:(unsigned long long)fp28 error:(id *)fp36;
- (id)sessionFragmentDirectoryURLsForSessionDirectory:(id)fp8 error:(id *)fp12;
- (BOOL)purgePrepSessionFragmentDirectoriesForStateName:(id)fp8 error:(id *)fp12;
- (id)removePrepStatusFromSessionFragmentDirectoryURL:(id)fp8 error:(id *)fp12;
- (id)prepSessionFragmentDirectoryURLForStateName:(id)fp8 sessionFragmentDirectoryURL:(id)fp12 error:(id *)fp16;
- (id)sessionDirectoryURLForStateName:(id)fp8 sessionIdentifier:(id)fp12 sessionTimestamp:(unsigned long long)fp16 error:(id *)fp24;
- (id)sessionDirectoryURLsForStateName:(id)fp8 error:(id *)fp12;
- (id)arrayByFilteringNonDirectoriesFromURLs:(id)fp8;
- (id)stateDirectoryURLForStateName:(id)fp8 error:(id *)fp12;
- (id)statesDirectoryURL:(id *)fp8;
- (BOOL)createDirectoryWithURL:(id)fp8 error:(id *)fp12;
- (BOOL)createFileWithURL:(id)fp8 error:(id *)fp12;
- (BOOL)deleteItemAtPath:(id)fp8 ifNotOfType:(int)fp12 error:(id *)fp16;
- (id)versionDirectoryName;
- (id)init;
- (id)initWithRootDirectoryPath:(id)fp8;
- (id)initWithRootDirectoryURL:(id)fp8;
- (void)dealloc;

@end

