/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableArray, NSString, NSURL;

@interface CLSMachOBinary : _ABCreateStringWithAddressDictionary
{
    NSURL *_url;
    struct CLSMachOFile _file;
    NSMutableArray *_slices;
    NSString *_instanceIdentifier;
}

+ (id)hashNSString:(id)fp8;
+ (id)MachOBinaryWithPath:(id)fp8;
- (id)slices;
- (void).cxx_destruct;
- (id)sliceForArchitecture:(id)fp8;
- (void)enumerateUUIDs:(id)fp(null);
- (id)instanceIdentifier;
- (id)path;
- (id)URL;
- (void)dealloc;
- (id)initWithURL:(id)fp8;

@end

