/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSURLSessionDelegate-Protocol.h"

@class CLSFileManager, FABCertificatePinner, NSOperationQueue, NSURLSession;

@interface CLSNetworkClient : _ABCreateStringWithAddressDictionary <NSURLSessionDelegate>
{
    NSURLSession *_session;
    BOOL _canUseBackgroundSession;
    id <CLSNetworkClientDelegate> _delegate;
    NSOperationQueue *_operationQueue;
    FABCertificatePinner *_certPinner;
    id _backgroundCompletionHandler;
    CLSFileManager *_fileManager;
}

+ (id)pinner;
- (void)setFileManager:(id)fp8;
- (id)fileManager;
- (void)setCanUseBackgroundSession:(BOOL)fp8;
- (BOOL)canUseBackgroundSession;
- (void)setBackgroundCompletionHandler:(id)fp(null);
- (id)backgroundCompletionHandler;
- (id)certPinner;
- (id)operationQueue;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)URLSession:(id)fp8 task:(id)fp12 didCompleteWithError:(id)fp16;
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(id)fp8;
- (void)URLSession:(id)fp8 didReceiveChallenge:(id)fp12 completionHandler:(id)fp(null);
- (void)URLSession:(id)fp8 didBecomeInvalidWithError:(id)fp12;
- (void)handleTaskDescription:(id)fp8 completedWithError:(id)fp12;
- (void)handleTask:(id)fp8 completedWithError:(id)fp12;
- (void)restartTask:(id)fp8;
- (void)runAfterRetryValueFromResponse:(id)fp8 block:(id)fp(null);
- (void)checkForExistingTaskMatchingDescription:(id)fp8 completionBlock:(id)fp(null);
- (void)checkSession:(id)fp8 forTasksMatchingDescription:(id)fp12 completionBlock:(id)fp(null);
- (BOOL)taskArray:(id)fp8 hasTaskMatchingDescription:(id)fp12;
- (id)relativeTaskPathForAbsolutePath:(id)fp8;
- (id)absolutePathForRelativeTaskPath:(id)fp8;
- (id)rootPath;
- (void)startNewUploadRequest:(id)fp8 filePath:(id)fp12;
- (void)startImmediateUploadRequest:(id)fp8 filePath:(id)fp12;
- (void)startUploadRequest:(id)fp8 filePath:(id)fp12 immediately:(BOOL)fp16;
- (void)attemptToReconnectBackgroundSessionWithCompletionBlock:(id)fp(null);
- (BOOL)supportsBackgroundRequests;
- (BOOL)NSURLSessionAvailable;
- (id)session;
- (id)initWithQueue:(id)fp8 fileManager:(id)fp12 delegate:(id)fp16;

@end

