/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "CLSCrashReport-Protocol.h"

@class CLSInternalReport, NSString;

@interface CLSReport : _ABCreateStringWithAddressDictionary <CLSCrashReport>
{
    CLSInternalReport *_internalReport;
    unsigned int _internalKVCounter;
    unsigned int _userKVCounter;
    NSString *_internalCompactedKVFile;
    NSString *_internalIncrementalKVFile;
    NSString *_userCompactedKVFile;
    NSString *_userIncrementalKVFile;
}

- (id)internalReport;
- (void).cxx_destruct;
- (void)setUserEmail:(id)fp8;
- (id)userEmail;
- (void)setUserName:(id)fp8;
- (id)userName;
- (void)setUserIdentifier:(id)fp8;
- (id)userIdentifier;
- (void)setObjectValue:(id)fp8 forKey:(id)fp12;
- (BOOL)isCrash;
- (id)OSBuildVersion;
- (id)OSVersion;
- (id)crashedOnDate;
- (id)dateCreated;
- (id)bundleShortVersionString;
- (id)bundleVersion;
- (id)customKeys;
- (id)identifier;
- (void)recordValue:(id)fp8 forUserKey:(id)fp12;
- (void)recordValue:(id)fp8 forInternalKey:(id)fp12;
- (CDAnonymousStruct9)userKVStorage;
- (CDAnonymousStruct9)internalKVStorage;
- (id)initWithInternalReport:(id)fp8;

@end

