/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class CLSFileManager, CLSNetworkClient, NSOperationQueue;

@interface CLSReportsController : _ABCreateStringWithAddressDictionary
{
    id <CLSReportsControllerDelegate> _delegate;
    NSOperationQueue *_operationQueue;
    CLSNetworkClient *_networkClient;
    CLSFileManager *_fileManager;
}

- (id)fileManager;
- (id)networkClient;
- (id)operationQueue;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)reportUploadAtPath:(id)fp8 completedWithError:(id)fp12;
- (BOOL)cleanUpSubmittedReportAtPath:(id)fp8;
- (BOOL)uploadPackagedReportAtPath:(id)fp8 asUrgent:(BOOL)fp12;
- (BOOL)submitPackageMultipartMimeAtPath:(id)fp8 synchronously:(BOOL)fp12;
- (BOOL)prepareAndSubmitReport:(id)fp8 asUrgent:(BOOL)fp12 withProcessing:(BOOL)fp16;
- (BOOL)fillInRequest:(id)fp8 forMultipartMimeDataAtPath:(id)fp12;
- (id)mutableRequestWithURL:(id)fp8 timeout:(double)fp12;
- (id)APIKey;
- (id)localeIdentifier;
- (BOOL)packagingEnabled;
- (BOOL)submissionEnabled;
- (id)reportURL;
- (id)reportEndpoint;
- (id)appBundleIdentifier;
- (id)settings;
- (id)initWithQueue:(id)fp8 delegate:(id)fp12 client:(id)fp16 fileManager:(id)fp20;

@end

