/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSCopying-Protocol.h"

@class NSDictionary, NSURLCache;

@interface CLSURLSessionConfiguration : _ABCreateStringWithAddressDictionary <NSCopying>
{
    NSDictionary *_additionalHeaders;
    NSURLCache *_URLCache;
    unsigned int _cookiePolicy;
}

+ (id)backgroundSessionConfigurationWithIdentifier:(id)fp8;
+ (id)backgroundSessionConfiguration:(id)fp8;
+ (id)ephemeralSessionConfiguration;
+ (id)defaultSessionConfiguration;
- (void)setHTTPCookieAcceptPolicy:(unsigned int)fp8;
- (unsigned int)HTTPCookieAcceptPolicy;
- (void)setHTTPAdditionalHeaders:(id)fp8;
- (id)HTTPAdditionalHeaders;
- (void)setURLCache:(id)fp8;
- (id)URLCache;
- (void).cxx_destruct;
- (void)setSessionSendsLaunchEvents:(BOOL)fp8;
- (BOOL)sessionSendsLaunchEvents;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

