/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSURL;

@interface CLSUserDefaults : _ABCreateStringWithAddressDictionary
{
    NSURL *_directoryURL;
    NSURL *_fileURL;
    NSMutableDictionary *_dataDictionary;
    NSObject<OS_dispatch_queue> *_serialDictionaryQueue;
    NSObject<OS_dispatch_queue> *_synchronizationQueue;
}

+ (id)standardUserDefaults;
- (id)synchronizationQueue;
- (id)serialDictionaryQueue;
- (id)dataDictionary;
- (id)fileURL;
- (id)directoryURL;
- (void).cxx_destruct;
- (id)objectForKeyByMigratingFromNSUserDefaults:(id)fp8;
- (void)migrateFromNSUserDefaults:(id)fp8;
- (id)loadDefaults;
- (void)synchronize;
- (id)dictionaryRepresentation;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)fp8;
- (void)setBool:(BOOL)fp8 forKey:(id)fp12;
- (void)setString:(id)fp8 forKey:(id)fp12;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (BOOL)boolForKey:(id)fp8;
- (id)stringForKey:(id)fp8;
- (id)objectForKey:(id)fp8;
- (id)getEscapedAppBundleIdentifier;
- (id)generateDirectoryURLForBaseURL:(id)fp8 hostAppBundleIdentifier:(id)fp12;
- (id)generateDirectoryURL;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

