/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSData;

@interface CocoaSecurityResult : _ABCreateStringWithAddressDictionary
{
    NSData *_data;
}

- (id)data;
- (void).cxx_destruct;
- (id)base64;
- (id)hexLower;
- (id)hex;
- (id)utf8String;
- (id)initWithBytes:(char *)fp8 length:(unsigned int)fp12;

@end

