/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "DDLogFileManager-Protocol.h"

@class NSString;

@interface DDLogFileManagerDefault : _ABCreateStringWithAddressDictionary <DDLogFileManager>
{
    unsigned int _maximumNumberOfLogFiles;
    unsigned long long _logFilesDiskQuota;
    NSString *_logsDirectory;
    NSString *_defaultFileProtectionLevel;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)fp8;
- (void)setLogFilesDiskQuota:(unsigned long long)fp8;
- (unsigned long long)logFilesDiskQuota;
- (void)setMaximumNumberOfLogFiles:(unsigned int)fp8;
- (unsigned int)maximumNumberOfLogFiles;
- (void).cxx_destruct;
- (id)applicationName;
- (id)createNewLogFile;
- (id)newLogFileName;
- (id)sortedLogFileInfos;
- (id)sortedLogFileNames;
- (id)sortedLogFilePaths;
- (id)unsortedLogFileInfos;
- (id)unsortedLogFileNames;
- (id)unsortedLogFilePaths;
- (id)logFileDateFormatter;
- (BOOL)isLogFile:(id)fp8;
- (id)logsDirectory;
- (id)defaultLogsDirectory;
- (void)deleteOldLogFiles;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)dealloc;
- (id)initWithLogsDirectory:(id)fp8 defaultFileProtectionLevel:(id)fp12;
- (id)initWithLogsDirectory:(id)fp8;
- (id)init;

@end

