/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol DDLogFileManager <NSObject>
- (void)setLogFilesDiskQuota:(unsigned long long)fp8;
- (unsigned long long)logFilesDiskQuota;
- (void)setMaximumNumberOfLogFiles:(unsigned int)fp8;
- (unsigned int)maximumNumberOfLogFiles;
- (id)createNewLogFile;
- (id)sortedLogFileInfos;
- (id)sortedLogFileNames;
- (id)sortedLogFilePaths;
- (id)unsortedLogFileInfos;
- (id)unsortedLogFileNames;
- (id)unsortedLogFilePaths;
- (id)logsDirectory;
@end

