/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSDate, NSDictionary, NSString;

@interface DDLogFileInfo : _ABCreateStringWithAddressDictionary
{
    NSString *_filePath;
    NSString *_fileName;
    NSDictionary *_fileAttributes;
    NSDate *_creationDate;
    NSDate *_modificationDate;
    unsigned long long _fileSize;
    NSString *filePath;
}

+ (id)logFileWithPath:(id)fp8;
- (id)filePath;
- (void).cxx_destruct;
- (int)reverseCompareByModificationDate:(id)fp8;
- (int)reverseCompareByCreationDate:(id)fp8;
- (BOOL)isEqual:(id)fp8;
- (void)removeExtendedAttributeWithName:(id)fp8;
- (void)addExtendedAttributeWithName:(id)fp8;
- (BOOL)hasExtendedAttributeWithName:(id)fp8;
- (void)renameFile:(id)fp8;
- (void)reset;
- (void)setIsArchived:(BOOL)fp8;
- (BOOL)isArchived;
- (id)description;
- (double)age;
- (unsigned long long)fileSize;
- (id)creationDate;
- (id)modificationDate;
- (id)fileName;
- (id)fileAttributes;
- (id)initWithFilePath:(id)fp8;

@end

