/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface DDLoggerNode : _ABCreateStringWithAddressDictionary
{
    id <DDLogger> _logger;
    unsigned int _level;
    struct dispatch_queue_s *_loggerQueue;
}

+ (id)nodeWithLogger:(id)fp8 loggerQueue:(struct dispatch_queue_s *)fp12 level:(unsigned int)fp16;
- (struct dispatch_queue_s *)loggerQueue;
- (unsigned int)level;
- (id)logger;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithLogger:(id)fp8 loggerQueue:(struct dispatch_queue_s *)fp12 level:(unsigned int)fp16;

@end

