/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSCopying-Protocol.h"

@interface DDXMLNode : _ABCreateStringWithAddressDictionary <NSCopying>
{
    struct _xmlKind *genericPtr;
    DDXMLNode *owner;
}

+ (id)lastError;
+ (void)removeAllChildrenFromNode:(struct _xmlNode *)fp8;
+ (void)removeChild:(struct _xmlNode *)fp8;
+ (void)detachChild:(struct _xmlNode *)fp8;
+ (void)detachChild:(struct _xmlNode *)fp8 andClean:(BOOL)fp12 andFixNamespaces:(BOOL)fp16;
+ (void)removeAllAttributesFromNode:(struct _xmlNode *)fp8;
+ (void)removeAttribute:(struct _xmlAttr *)fp8;
+ (void)detachAttribute:(struct _xmlAttr *)fp8;
+ (void)detachAttribute:(struct _xmlAttr *)fp8 andClean:(BOOL)fp12;
+ (void)removeAllNamespacesFromNode:(struct _xmlNode *)fp8;
+ (void)removeNamespace:(struct _xmlNs *)fp8 fromNode:(struct _xmlNode *)fp12;
+ (void)detachNamespace:(struct _xmlNs *)fp8 fromNode:(struct _xmlNode *)fp12;
+ (void)recursiveFixDefaultNamespacesInNode:(struct _xmlNode *)fp8 withNewRoot:(struct _xmlNode *)fp12;
+ (void)recursiveMigrateNamespace:(struct _xmlNs *)fp8 to:(struct _xmlNs *)fp12 node:(struct _xmlNode *)fp16;
+ (void)recursiveStripNamespace:(struct _xmlNs *)fp8 fromNode:(struct _xmlNode *)fp12;
+ (void)recursiveStripDocPointersFromNode:(struct _xmlNode *)fp8;
+ (void)stripDocPointersFromAttr:(struct _xmlAttr *)fp8;
+ (id)prefixForName:(id)fp8;
+ (id)localNameForName:(id)fp8;
+ (void)getPrefix:(id *)fp8 localName:(id *)fp12 forName:(id)fp16;
+ (void)getHasPrefix:(char *)fp8 localName:(id *)fp12 forName:(id)fp16;
+ (id)nodeWithPrimitive:(struct _xmlKind *)fp8 owner:(id)fp12;
+ (id)nodeWithUnknownPrimitive:(struct _xmlKind *)fp8 owner:(id)fp12;
+ (id)textWithStringValue:(id)fp8;
+ (id)commentWithStringValue:(id)fp8;
+ (id)processingInstructionWithName:(id)fp8 stringValue:(id)fp12;
+ (id)namespaceWithName:(id)fp8 stringValue:(id)fp12;
+ (id)attributeWithName:(id)fp8 URI:(id)fp12 stringValue:(id)fp16;
+ (id)attributeWithName:(id)fp8 stringValue:(id)fp12;
+ (id)elementWithName:(id)fp8 URI:(id)fp12;
+ (id)elementWithName:(id)fp8 children:(id)fp12 attributes:(id)fp16;
+ (id)elementWithName:(id)fp8 stringValue:(id)fp12;
+ (id)elementWithName:(id)fp8;
+ (void)initialize;
- (void).cxx_destruct;
- (BOOL)_hasParent;
- (id)nodesForXPath:(id)fp8 error:(id *)fp12;
- (id)XMLStringWithOptions:(unsigned int)fp8;
- (id)XMLString;
- (id)description;
- (id)URI;
- (void)setURI:(id)fp8;
- (id)prefix;
- (id)localName;
- (id)XPath;
- (struct _xmlStd *)_XPathPreProcess:(id)fp8;
- (void)detach;
- (id)nextNode;
- (id)previousNode;
- (id)nextSibling;
- (id)previousSibling;
- (id)childAtIndex:(unsigned int)fp8;
- (id)children;
- (unsigned int)childCount;
- (id)parent;
- (id)rootDocument;
- (unsigned int)level;
- (unsigned int)index;
- (id)stringValue;
- (void)setStringValue:(id)fp8;
- (id)name;
- (void)setName:(id)fp8;
- (unsigned int)kind;
- (BOOL)isEqual:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)init;
- (id)initWithPrimitive:(struct _xmlKind *)fp8 owner:(id)fp12;

@end

