/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class FABIcon, NSDictionary, NSString;

@interface FABApplicationIdentiferModel : _ABCreateStringWithAddressDictionary
{
    NSDictionary *_architectureUUIDMap;
    NSString *_installID;
    FABIcon *_icon;
    NSString *_bundleIdentifier;
    NSString *_instanceIdentifier;
    CDAnonymousStruct7 _builtSDK;
    CDAnonymousStruct7 _minimumSDK;
}

- (CDAnonymousStruct7)minimumSDK;
- (CDAnonymousStruct7)builtSDK;
- (void)setInstanceIdentifier:(id)fp8;
- (id)instanceIdentifier;
- (id)bundleIdentifier;
- (id)icon;
- (id)installID;
- (void)setArchitectureUUIDMap:(id)fp8;
- (id)architectureUUIDMap;
- (void).cxx_destruct;
- (BOOL)computeInstanceIdentifier;
- (BOOL)computeExecutableInfo;
- (id)minimumSDKString;
- (id)builtSDKString;
- (id)initWithInstallID:(id)fp8;

@end

