/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FABAsyncOperation.h"

@class NSArray, NSMutableArray, NSObject<OS_dispatch_queue>, NSOperationQueue;

@interface FABCompoundOperation : FABAsyncOperation
{
    NSArray *_operations;
    NSOperationQueue *_compoundQueue;
    unsigned int _completedOperations;
    NSMutableArray *_errors;
    NSObject<OS_dispatch_queue> *_countingQueue;
}

- (void)setCountingQueue:(id)fp8;
- (id)countingQueue;
- (void)setErrors:(id)fp8;
- (id)errors;
- (void)setCompletedOperations:(unsigned int)fp8;
- (unsigned int)completedOperations;
- (void)setCompoundQueue:(id)fp8;
- (id)compoundQueue;
- (void)setOperations:(id)fp8;
- (id)operations;
- (void).cxx_destruct;
- (void)attemptCompoundCompletionWithCompletedOperations:(unsigned int)fp8;
- (unsigned int)updateCompletionCountsWithError:(id)fp8;
- (void)addCompoundCompletionCheckToOriginalCompletion:(id)fp(null) operation:(void)fp8;
- (void)cancel;
- (void)main;
- (id)init;

@end

