/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FABNetworkOperation.h"

@class FABNetworkClient, NSError, NSFileManager, NSString, NSURL;

@interface FABDownloadAndSaveSettingsOperation : FABNetworkOperation
{
    id <FABDownloadAndSaveSettingsOperationDelegate> _delegate;
    NSError *_error;
    NSURL *_settingsURL;
    NSFileManager *_fileManager;
    NSString *_settingsDirectoryPath;
    NSString *_settingsFilePath;
    NSString *_installIdentifier;
    NSString *_advertisingToken;
    FABNetworkClient *_networkClient;
}

- (id)networkClient;
- (id)advertisingToken;
- (id)installIdentifier;
- (id)settingsFilePath;
- (id)settingsDirectoryPath;
- (id)fileManager;
- (id)settingsURL;
- (id)error;
- (id)delegate;
- (void).cxx_destruct;
- (void)main;
- (id)mutableRequestWithDefaultHTTPHeaderFieldsAndTimeoutForURL:(id)fp8;
- (id)initWithAPIKey:(id)fp8 delegate:(id)fp12 settingsURL:(id)fp16 settingsDirectoryPath:(id)fp20 settingsFilePath:(id)fp24 fileManager:(id)fp28 installIdentifier:(id)fp32 advertisingToken:(id)fp36 networkClient:(id)fp40;
- (id)initWithAPIKey:(id)fp8;

@end

