/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class FABApplicationIdentiferModel, FABSettingsOnboardingManager, NSArray, NSDictionary, NSString;

@interface Fabric : _ABCreateStringWithAddressDictionary
{
    BOOL _debug;
    BOOL _isFirstInstall;
    NSArray *_kitClasses;
    NSDictionary *_fabricConfig;
    FABSettingsOnboardingManager *_settingsAndOnboardingManager;
    FABApplicationIdentiferModel *_applicationIdentifierModel;
    NSString *_APIKey;
    NSString *_installID;
    NSString *_executionIdentifier;
    NSString *_advertisingToken;
}

+ (id)configurationDictionaryForKitClass:(Class)fp8;
+ (void)initializeKit:(Class)fp8;
+ (id)kitClassesByEnsuringAppseeIsFirst:(id)fp8;
+ (id)kitClassesByAddingAnswersIfFound:(id)fp8;
+ (id)kitClassesByAddingDigitsIfFound:(id)fp8;
+ (void)validateFABKitConformance:(id)fp8;
+ (id)convertToKitClassesIfNeeded:(id)fp8;
+ (id)with:(id)fp8;
+ (id)sharedSDK;
- (void)setAdvertisingToken:(id)fp8;
- (id)advertisingToken;
- (id)executionIdentifier;
- (BOOL)isFirstInstall;
- (id)installID;
- (void)setAPIKey:(id)fp8;
- (id)applicationIdentifierModel;
- (void)setSettingsAndOnboardingManager:(id)fp8;
- (id)settingsAndOnboardingManager;
- (void)setFabricConfig:(id)fp8;
- (void)setKitClasses:(id)fp8;
- (id)kitClasses;
- (void)setDebug:(BOOL)fp8;
- (BOOL)debug;
- (void).cxx_destruct;
- (id)instanceIdentifier;
- (id)settings;
- (id)configurationDictionaryForKit:(id)fp8;
- (id)validFabricConfigFromInfoPlist:(id)fp8;
- (id)APIKey;
- (id)fabricConfig;
- (id)generateInstallationUUID;
- (id)readInstallationUUID;
- (id)kitVersionsByKitBundleIdentifier;
- (void)onboardAppAndDownloadSettings;
- (id)init;

@end

