/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableString;

@interface FABURLBuilder : _ABCreateStringWithAddressDictionary
{
    NSMutableString *_URLString;
    unsigned int _queryParams;
}

+ (id)URLWithBase:(id)fp8;
- (void)setQueryParams:(unsigned int)fp8;
- (unsigned int)queryParams;
- (void)setURLString:(id)fp8;
- (id)URLString;
- (void).cxx_destruct;
- (id)URL;
- (void)appendValue:(id)fp8 forQueryParam:(id)fp12;
- (void)escapeAndAppendComponent:(id)fp8;
- (void)appendComponent:(id)fp8;
- (id)escapeString:(id)fp8;
- (id)init;

@end

