/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBSDKButton.h"

#import "FBSDKButtonImpressionTracking-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class FBSDKLoginManager, NSArray, NSString;

@interface FBSDKLoginButton : FBSDKButton <FBSDKButtonImpressionTracking, UIActionSheetDelegate>
{
    BOOL _hasShownTooltipBubble;
    FBSDKLoginManager *_loginManager;
    NSString *_userID;
    NSString *_userName;
    id <FBSDKLoginButtonDelegate> _delegate;
    NSArray *_publishPermissions;
    NSArray *_readPermissions;
    unsigned int _tooltipBehavior;
    unsigned int _tooltipColorStyle;
}

- (void)setTooltipColorStyle:(unsigned int)fp8;
- (unsigned int)tooltipColorStyle;
- (void)setTooltipBehavior:(unsigned int)fp8;
- (unsigned int)tooltipBehavior;
- (void)setReadPermissions:(id)fp8;
- (id)readPermissions;
- (void)setPublishPermissions:(id)fp8;
- (id)publishPermissions;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)_updateContent;
- (void)_showTooltipIfNeeded;
- (id)_shortLogInTitle;
- (id)_longLogInTitle;
- (id)_logOutTitle;
- (void)_buttonPressed:(id)fp8;
- (void)_acessTokenDidChangeNotification:(id)fp8;
- (void)configureButton;
- (id)impressionTrackingIdentifier;
- (id)impressionTrackingEventName;
- (id)analyticsParameters;
- (void)actionSheet:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)setLoginBehavior:(unsigned int)fp8;
- (unsigned int)loginBehavior;
- (void)setDefaultAudience:(unsigned int)fp8;
- (unsigned int)defaultAudience;
- (void)dealloc;

@end

