/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class FBSDKAccessToken, NSMutableDictionary, NSSet;

@interface FBSDKLoginManagerLoginResult : _ABCreateStringWithAddressDictionary
{
    NSMutableDictionary *_mutableLoggingExtras;
    BOOL _isCancelled;
    BOOL _isSkipped;
    FBSDKAccessToken *_token;
    NSSet *_grantedPermissions;
    NSSet *_declinedPermissions;
}

- (void)setIsSkipped:(BOOL)fp8;
- (BOOL)isSkipped;
- (void)setDeclinedPermissions:(id)fp8;
- (id)declinedPermissions;
- (void)setGrantedPermissions:(id)fp8;
- (id)grantedPermissions;
- (BOOL)isCancelled;
- (void)setToken:(id)fp8;
- (id)token;
- (void).cxx_destruct;
- (id)loggingExtras;
- (void)addLoggingExtra:(id)fp8 forKey:(id)fp12;
- (id)initWithToken:(id)fp8 isCancelled:(BOOL)fp12 grantedPermissions:(id)fp16 declinedPermissions:(id)fp20;
- (id)init;

@end

