/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface FBSDKGraphRequestPiggybackManager : _ABCreateStringWithAddressDictionary
{
}

+ (void)addServerConfigurationPiggyback:(id)fp8;
+ (void)addRefreshPiggybackIfStale:(id)fp8;
+ (void)addRefreshPiggyback:(id)fp8 permissionHandler:(id)fp(null);
+ (void)addPiggybackRequests:(id)fp8;

@end

