/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "FBSDKCopying-Protocol.h"

@class NSDictionary, NSString;

@interface FBSDKBridgeAPIRequest : _ABCreateStringWithAddressDictionary <FBSDKCopying>
{
    NSString *_actionID;
    NSString *_methodName;
    NSString *_methodVersion;
    NSDictionary *_parameters;
    unsigned int _protocolType;
    NSString *_scheme;
    NSDictionary *_userInfo;
    id <FBSDKBridgeAPIProtocol> _protocol;
}

+ (id)_protocolForType:(unsigned int)fp8 scheme:(id)fp12;
+ (id)protocolMap;
+ (id)bridgeAPIRequestWithProtocolType:(unsigned int)fp8 scheme:(id)fp12 methodName:(id)fp16 methodVersion:(id)fp20 parameters:(id)fp24 userInfo:(id)fp28;
- (id)protocol;
- (id)userInfo;
- (id)scheme;
- (unsigned int)protocolType;
- (id)parameters;
- (id)methodVersion;
- (id)methodName;
- (id)actionID;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)requestURL:(id *)fp8;
- (id)init;
- (id)initWithProtocol:(id)fp8 protocolType:(unsigned int)fp12 scheme:(id)fp16 methodName:(id)fp20 methodVersion:(id)fp24 parameters:(id)fp28 userInfo:(id)fp32;

@end

