/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "FBSDKBridgeAPIProtocol-Protocol.h"

@class NSString, UIPasteboard;

@interface FBSDKBridgeAPIProtocolNativeV1 : _ABCreateStringWithAddressDictionary <FBSDKBridgeAPIProtocol>
{
    BOOL _includeAppIcon;
    NSString *_appScheme;
    unsigned int _dataLengthThreshold;
    UIPasteboard *_pasteboard;
}

+ (void)clearData:(id)fp8 fromPasteboardOnApplicationDidBecomeActive:(id)fp12;
- (id)pasteboard;
- (BOOL)includeAppIcon;
- (unsigned int)dataLengthThreshold;
- (id)appScheme;
- (void).cxx_destruct;
- (id)_JSONStringForObject:(id)fp8 enablePasteboard:(BOOL)fp12 error:(id *)fp16;
- (id)_errorWithDictionary:(id)fp8;
- (id)_bridgeParametersWithActionID:(id)fp8 error:(id *)fp12;
- (id)_appIcon;
- (id)responseParametersForActionID:(id)fp8 queryParameters:(id)fp12 cancelled:(char *)fp16 error:(id *)fp20;
- (id)requestURLWithActionID:(id)fp8 scheme:(id)fp12 methodName:(id)fp16 methodVersion:(id)fp20 parameters:(id)fp24 error:(id *)fp28;
- (id)init;
- (id)initWithAppScheme:(id)fp8 pasteboard:(id)fp12 dataLengthThreshold:(unsigned int)fp16 includeAppIcon:(BOOL)fp20;
- (id)initWithAppScheme:(id)fp8;

@end

