/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSDate, NSString, NSURL;

@interface FBSDKProfile : _ABCreateStringWithAddressDictionary <NSCopying, NSSecureCoding>
{
    NSString *_userID;
    NSString *_firstName;
    NSString *_middleName;
    NSString *_lastName;
    NSString *_name;
    NSURL *_linkURL;
    NSDate *_refreshDate;
}

+ (void)observeChangeAccessTokenChange:(id)fp8;
+ (void)loadProfileWithToken:(id)fp8 completion:(id)fp(null);
+ (BOOL)supportsSecureCoding;
+ (void)loadCurrentProfileWithCompletion:(id)fp(null);
+ (void)enableUpdatesOnAccessTokenChange:(BOOL)fp8;
+ (void)setCurrentProfile:(id)fp8;
+ (id)currentProfile;
+ (id)fetchCachedProfile;
+ (void)cacheProfile:(id)fp8;
- (id)refreshDate;
- (id)linkURL;
- (id)name;
- (id)lastName;
- (id)middleName;
- (id)firstName;
- (id)userID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (BOOL)isEqualToProfile:(id)fp8;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)imagePathForPictureMode:(unsigned int)fp8 size:(struct CGSize)fp12;
- (id)imageURLForPictureMode:(unsigned int)fp8 size:(struct CGSize)fp12;
- (id)initWithUserID:(id)fp8 firstName:(id)fp12 middleName:(id)fp16 lastName:(id)fp20 name:(id)fp24 linkURL:(id)fp28 refreshDate:(id)fp32;
- (id)init;

@end

