/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIColor;

@interface FBSDKIcon : _ABCreateStringWithAddressDictionary
{
    UIColor *_color;
}

- (id)color;
- (void).cxx_destruct;
- (struct CGPath *)pathWithSize:(struct CGSize)fp8;
- (id)imageWithSize:(struct CGSize)fp8;
- (id)init;
- (id)initWithColor:(id)fp8;

@end

