/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface FBSDKSettings : _ABCreateStringWithAddressDictionary
{
}

+ (id)graphAPIDebugParamValue;
+ (void)updateGraphAPIDebugBehavior;
+ (void)setUserAgentSuffix:(id)fp8;
+ (id)userAgentSuffix;
+ (id)accessTokenCache;
+ (id)sdkVersion;
+ (id)legacyUserDefaultTokenInformationKeyName;
+ (void)setLegacyUserDefaultTokenInformationKeyName:(id)fp8;
+ (void)disableLoggingBehavior:(id)fp8;
+ (void)enableLoggingBehavior:(id)fp8;
+ (void)setLoggingBehavior:(id)fp8;
+ (id)loggingBehavior;
+ (void)setLimitEventAndDataUsage:(BOOL)fp8;
+ (BOOL)limitEventAndDataUsage;
+ (void)setJPEGCompressionQuality:(float)fp8;
+ (float)JPEGCompressionQuality;
+ (BOOL)isGraphErrorRecoveryDisabled;
+ (void)setGraphErrorRecoveryDisabled:(BOOL)fp8;
+ (void)_setJPEGCompressionQualityNumber:(id)fp8;
+ (id)_JPEGCompressionQualityNumber;
+ (void)setFacebookDomainPart:(id)fp8;
+ (id)facebookDomainPart;
+ (void)setDisplayName:(id)fp8;
+ (id)displayName;
+ (void)setClientToken:(id)fp8;
+ (id)clientToken;
+ (void)setAppURLSchemeSuffix:(id)fp8;
+ (id)appURLSchemeSuffix;
+ (void)setAppID:(id)fp8;
+ (id)appID;
+ (void)initialize;
- (void)setAccessTokenCache:(id)fp8;
- (id)init;

@end

