/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "SKPaymentTransactionObserver-Protocol.h"

@interface FBSDKPaymentObserver : _ABCreateStringWithAddressDictionary <SKPaymentTransactionObserver>
{
    BOOL _observingTransactions;
}

+ (id)singleton;
+ (void)stopObservingTransactions;
+ (void)startObservingTransactions;
- (void)handleTransaction:(id)fp8;
- (void)paymentQueue:(id)fp8 updatedTransactions:(id)fp12;
- (void)stopObservingTransactions;
- (void)startObservingTransactions;
- (id)init;

@end

