/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, NSString, UIColor, UILabel, UITapGestureRecognizer;

@interface FBSDKTooltipView : _ABCreateStringWithAddressDictionary
{
    struct CGPoint _positionInView;
    double _displayTime;
    double _minimumDisplayDuration;
    UILabel *_textLabel;
    UITapGestureRecognizer *_insideTapGestureRecognizer;
    float _leftWidth;
    float _rightWidth;
    float _arrowMidpoint;
    BOOL _pointingUp;
    BOOL _isFadingOut;
    UIColor *_innerStrokeColor;
    float _arrowHeight;
    float _textPadding;
    float _maximumTextWidth;
    float _verticalTextOffset;
    float _verticalCrossOffset;
    unsigned int _colorStyle;
    NSArray *_gradientColors;
    UIColor *_crossCloseGlyphColor;
    NSString *_message;
    NSString *_tagline;
    double _displayDuration;
}

- (id)tagline;
- (id)message;
- (void)setDisplayDuration:(double)fp8;
- (double)displayDuration;
- (void).cxx_destruct;
- (void)cancelAllScheduledFadeOutMethods;
- (void)scheduleFadeoutRespectingMinimumDisplayDuration;
- (void)scheduleAutomaticFadeout;
- (void)setMessage:(id)fp8 tagline:(id)fp12;
- (struct CGRect)layoutSubviewsAndDetermineFrame;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)fp8;
- (void)onTapInTooltip:(id)fp8;
- (void)animateFadeOutWithCompletion:(id)fp(null);
- (void)animateFadeIn;
- (void)setColorStyle:(unsigned int)fp8;
- (unsigned int)colorStyle;
- (void)dismiss;
- (void)presentInView:(id)fp8 withArrowPosition:(struct CGPoint)fp12 direction:(unsigned int)fp20;
- (void)presentFromView:(id)fp8;
- (void)setTagline:(id)fp8;
- (void)setMessage:(id)fp8;
- (void)dealloc;
- (id)initWithTagline:(id)fp8 message:(id)fp12 colorStyle:(unsigned int)fp16;

@end

