/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface FBSDKTypeUtility : _ABCreateStringWithAddressDictionary
{
}

+ (id)_objectValue:(id)fp8 ofClass:(Class)fp12;
+ (id)URLValue:(id)fp8;
+ (unsigned int)unsignedIntegerValue:(id)fp8;
+ (double)timeIntervalValue:(id)fp8;
+ (id)stringValue:(id)fp8;
+ (id)objectValue:(id)fp8;
+ (int)integerValue:(id)fp8;
+ (id)dictionaryValue:(id)fp8;
+ (BOOL)boolValue:(id)fp8;
+ (id)arrayValue:(id)fp8;
- (id)init;

@end

