/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface FBSDKMath : _ABCreateStringWithAddressDictionary
{
}

+ (unsigned int)hashWithPointer:(const void *)fp8;
+ (unsigned int)hashWithLong:(unsigned long long)fp8;
+ (unsigned int)hashWithIntegerArray:(unsigned int *)fp8 count:(unsigned int)fp12;
+ (unsigned int)hashWithInteger:(unsigned int)fp8 andInteger:(unsigned int)fp12;
+ (unsigned int)hashWithInteger:(unsigned int)fp8;
+ (unsigned int)hashWithFloat:(float)fp8;
+ (unsigned int)hashWithDouble:(double)fp8;
+ (unsigned int)hashWithCString:(const char *)fp8;
+ (unsigned int)hashWithCGFloat:(float)fp8;
+ (struct CGSize)floorForSize:(struct CGSize)fp8;
+ (struct CGPoint)floorForPoint:(struct CGPoint)fp8;
+ (struct CGSize)ceilForSize:(struct CGSize)fp8;
+ (struct CGPoint)ceilForPoint:(struct CGPoint)fp8;
- (id)init;

@end

