/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface JLBBouncyButton : _ABCreateStringWithAddressDictionary
{
}

- (void)reset:(id)fp8;
- (void)bounceBack:(id)fp8;
- (void)shrink:(id)fp8;
- (void)setupAnimationActions;
- (id)initWithFrame:(struct CGRect)fp8;

@end

