/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableArray, NSString;

@interface NBNumberFormat : _ABCreateStringWithAddressDictionary
{
    BOOL _nationalPrefixOptionalWhenFormatting;
    NSString *_pattern;
    NSString *_format;
    NSMutableArray *_leadingDigitsPatterns;
    NSString *_nationalPrefixFormattingRule;
    NSString *_domesticCarrierCodeFormattingRule;
}

- (void)setDomesticCarrierCodeFormattingRule:(id)fp8;
- (id)domesticCarrierCodeFormattingRule;
- (void)setNationalPrefixOptionalWhenFormatting:(BOOL)fp8;
- (BOOL)nationalPrefixOptionalWhenFormatting;
- (void)setNationalPrefixFormattingRule:(id)fp8;
- (id)nationalPrefixFormattingRule;
- (void)setLeadingDigitsPatterns:(id)fp8;
- (id)leadingDigitsPatterns;
- (void)setFormat:(id)fp8;
- (id)format;
- (void)setPattern:(id)fp8;
- (id)pattern;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)description;
- (id)init;
- (id)initWithPattern:(id)fp8 withFormat:(id)fp12 withLeadingDigitsPatterns:(id)fp16 withNationalPrefixFormattingRule:(id)fp20 whenFormatting:(BOOL)fp24 withDomesticCarrierCodeFormattingRule:(id)fp28;

@end

