/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface NBPhoneNumberDesc : _ABCreateStringWithAddressDictionary
{
    NSString *_nationalNumberPattern;
    NSString *_possibleNumberPattern;
    NSString *_exampleNumber;
}

- (void)setExampleNumber:(id)fp8;
- (id)exampleNumber;
- (void)setPossibleNumberPattern:(id)fp8;
- (id)possibleNumberPattern;
- (void)setNationalNumberPattern:(id)fp8;
- (id)nationalNumberPattern;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)description;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)init;
- (id)initWithNationalNumberPattern:(id)fp8 withPossibleNumberPattern:(id)fp12 withExample:(id)fp16;
- (id)initWithData:(id)fp8;

@end

