/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableDictionary;

@interface PINMemoryCache : _ABCreateStringWithAddressDictionary
{
    BOOL _ttlCache;
    BOOL _removeAllObjectsOnMemoryWarning;
    BOOL _removeAllObjectsOnEnteringBackground;
    unsigned int _costLimit;
    unsigned int _totalCost;
    id _willAddObjectBlock;
    id _willRemoveObjectBlock;
    id _willRemoveAllObjectsBlock;
    id _didAddObjectBlock;
    id _didRemoveObjectBlock;
    id _didRemoveAllObjectsBlock;
    id _didReceiveMemoryWarningBlock;
    id _didEnterBackgroundBlock;
    struct dispatch_queue_s *_concurrentQueue;
    struct dispatch_semaphore_s *_lockSemaphore;
    NSMutableDictionary *_dictionary;
    NSMutableDictionary *_dates;
    NSMutableDictionary *_costs;
    double _ageLimit;
}

+ (id)sharedCache;
- (void)setCosts:(id)fp8;
- (id)costs;
- (void)setDates:(id)fp8;
- (id)dates;
- (void)setDictionary:(id)fp8;
- (id)dictionary;
- (void)setLockSemaphore:(struct dispatch_semaphore_s *)fp8;
- (struct dispatch_semaphore_s *)lockSemaphore;
- (void)setRemoveAllObjectsOnEnteringBackground:(BOOL)fp8;
- (BOOL)removeAllObjectsOnEnteringBackground;
- (void)setRemoveAllObjectsOnMemoryWarning:(BOOL)fp8;
- (BOOL)removeAllObjectsOnMemoryWarning;
- (void)setConcurrentQueue:(struct dispatch_queue_s *)fp8;
- (struct dispatch_queue_s *)concurrentQueue;
- (void).cxx_destruct;
- (void)unlock;
- (void)lock;
- (void)setTtlCache:(BOOL)fp8;
- (BOOL)isTTLCache;
- (unsigned int)totalCost;
- (void)setCostLimit:(unsigned int)fp8;
- (unsigned int)costLimit;
- (void)setAgeLimit:(double)fp8;
- (double)ageLimit;
- (void)setDidEnterBackgroundBlock:(id)fp(null);
- (id)didEnterBackgroundBlock;
- (void)setDidReceiveMemoryWarningBlock:(id)fp(null);
- (id)didReceiveMemoryWarningBlock;
- (void)setDidRemoveAllObjectsBlock:(id)fp(null);
- (id)didRemoveAllObjectsBlock;
- (void)setDidRemoveObjectBlock:(id)fp(null);
- (id)didRemoveObjectBlock;
- (void)setDidAddObjectBlock:(id)fp(null);
- (id)didAddObjectBlock;
- (void)setWillRemoveAllObjectsBlock:(id)fp(null);
- (id)willRemoveAllObjectsBlock;
- (void)setWillRemoveObjectBlock:(id)fp(null);
- (id)willRemoveObjectBlock;
- (void)setWillAddObjectBlock:(id)fp(null);
- (id)willAddObjectBlock;
- (void)enumerateObjectsWithBlock:(id)fp(null);
- (void)removeAllObjects;
- (void)trimToCostByDate:(unsigned int)fp8;
- (void)trimToCost:(unsigned int)fp8;
- (void)trimToDate:(id)fp8;
- (void)removeObjectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12 withCost:(unsigned int)fp16;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)objectForKey:(id)fp8;
- (void)enumerateObjectsWithBlock:(id)fp(null) completionBlock:(void)fp8;
- (void)removeAllObjects:(id)fp(null);
- (void)trimToCostByDate:(unsigned int)fp8 block:(id)fp(null);
- (void)trimToCost:(unsigned int)fp8 block:(id)fp(null);
- (void)trimToDate:(id)fp8 block:(id)fp(null);
- (void)removeObjectForKey:(id)fp8 block:(id)fp(null);
- (void)setObject:(id)fp8 forKey:(id)fp12 withCost:(unsigned int)fp16 block:(id)fp(null);
- (void)setObject:(id)fp8 forKey:(id)fp12 block:(id)fp(null);
- (void)objectForKey:(id)fp8 block:(id)fp(null);
- (void)trimToAgeLimitRecursively;
- (void)trimToCostLimitByDate:(unsigned int)fp8;
- (void)trimToCostLimit:(unsigned int)fp8;
- (void)trimMemoryToDate:(id)fp8;
- (void)removeObjectAndExecuteBlocksForKey:(id)fp8;
- (void)didReceiveEnterBackgroundNotification:(id)fp8;
- (void)didReceiveMemoryWarningNotification:(id)fp8;
- (id)init;
- (void)dealloc;

@end

