/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PINRemoteImageTask.h"

@class PINDataTaskOperation, PINProgressiveImage;

@interface PINRemoteImageDownloadTask : PINRemoteImageTask
{
    BOOL _canSetDataTaskPriority;
    BOOL _hasProgressBlocks;
    PINDataTaskOperation *_urlSessionTaskOperation;
    PINProgressiveImage *_progressImage;
    double _sessionTaskStartTime;
    double _sessionTaskEndTime;
}

- (void)setProgressImage:(id)fp8;
- (id)progressImage;
- (void)setHasProgressBlocks:(BOOL)fp8;
- (void)setSessionTaskEndTime:(double)fp8;
- (double)sessionTaskEndTime;
- (void)setSessionTaskStartTime:(double)fp8;
- (double)sessionTaskStartTime;
- (void)setUrlSessionTaskOperation:(id)fp8;
- (id)urlSessionTaskOperation;
- (void).cxx_destruct;
- (void)setPriority:(unsigned int)fp8;
- (BOOL)cancelWithUUID:(id)fp8 manager:(id)fp12;
- (void)callProgressImageWithQueue:(id)fp8 withImage:(id)fp12;
- (void)callProgressDownloadWithQueue:(id)fp8 completedBytes:(long long)fp12 totalBytes:(long long)fp20;
- (BOOL)hasProgressBlocks;
- (id)init;

@end

