/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableDictionary;

@interface PINRemoteImageTask : _ABCreateStringWithAddressDictionary
{
    NSMutableDictionary *_callbackBlocks;
}

- (void)setCallbackBlocks:(id)fp8;
- (id)callbackBlocks;
- (void).cxx_destruct;
- (void)setPriority:(unsigned int)fp8;
- (BOOL)cancelWithUUID:(id)fp8 manager:(id)fp12;
- (void)callCompletionsWithQueue:(id)fp8 remove:(BOOL)fp12 withImage:(id)fp16 animatedImage:(id)fp20 cached:(BOOL)fp24 error:(id)fp28;
- (void)removeCallbackWithUUID:(id)fp8;
- (void)addCallbacksWithCompletionBlock:(id)fp(null) progressImageBlock:(void)fp8 progressDownloadBlock:(id)fp(null) withUUID:(void)fp12;
- (id)description;
- (id)init;

@end

