/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableArray, POPAnimation;

@interface POPAnimationTracer : _ABCreateStringWithAddressDictionary
{
    POPAnimation *_animation;
    struct _POPAnimationState *_animationState;
    NSMutableArray *_events;
    BOOL _animationHasVelocity;
    BOOL _shouldLogAndResetOnCompletion;
}

- (void)setShouldLogAndResetOnCompletion:(BOOL)fp8;
- (BOOL)shouldLogAndResetOnCompletion;
- (void).cxx_destruct;
- (id)eventsWithType:(unsigned int)fp8;
- (id)writeEvents;
- (id)allEvents;
- (void)reset;
- (void)stop;
- (void)start;
- (void)autoreversed;
- (void)didReachToValue:(id)fp8;
- (void)didStop:(BOOL)fp8;
- (void)didStart;
- (void)updateTension:(float)fp8;
- (void)updateMass:(float)fp8;
- (void)updateFriction:(float)fp8;
- (void)updateBounciness:(float)fp8;
- (void)updateSpeed:(float)fp8;
- (void)updateVelocity:(id)fp8;
- (void)updateFromValue:(id)fp8;
- (void)updateToValue:(id)fp8;
- (void)writePropertyValue:(id)fp8;
- (void)readPropertyValue:(id)fp8;
- (id)initWithAnimation:(id)fp8;

@end

