/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface POPAnimationEvent : _ABCreateStringWithAddressDictionary
{
    unsigned int _type;
    NSString *_animationDescription;
    double _time;
}

- (void)setAnimationDescription:(id)fp8;
- (id)animationDescription;
- (double)time;
- (unsigned int)type;
- (void).cxx_destruct;
- (void)_appendDescription:(id)fp8;
- (id)description;
- (id)initWithType:(unsigned int)fp8 time:(double)fp12;

@end

