/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class CADisplayLink, NSMutableArray;

@interface POPAnimator : _ABCreateStringWithAddressDictionary
{
    CADisplayLink *_displayLink;
    struct list<std::__1::shared_ptr<POPAnimatorItem>, std::__1::allocator<std::__1::shared_ptr<POPAnimatorItem>>> _list;
    struct __CFDictionary *_dict;
    NSMutableArray *_observers;
    struct list<std::__1::shared_ptr<POPAnimatorItem>, std::__1::allocator<std::__1::shared_ptr<POPAnimatorItem>>> _pendingList;
    struct __CFRunLoopObserver *_pendingListObserver;
    double _slowMotionStartTime;
    double _slowMotionLastTime;
    double _slowMotionAccumulator;
    double _beginTime;
    int _lock;
    BOOL _disableDisplayLink;
    id <POPAnimatorDelegate> _delegate;
}

+ (void)setDisableBackgroundThread:(BOOL)fp8;
+ (BOOL)disableBackgroundThread;
+ (id)sharedAnimator;
- (void)setBeginTime:(double)fp8;
- (double)beginTime;
- (void)setDisableDisplayLink:(BOOL)fp8;
- (BOOL)disableDisplayLink;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (void)renderTime:(double)fp8;
- (void)render;
- (double)_currentRenderTime;
- (id)animationForObject:(id)fp8 key:(id)fp12;
- (id)animationKeysForObject:(id)fp8;
- (void)removeAnimationForObject:(id)fp8 key:(id)fp12;
- (void)removeAnimationForObject:(id)fp8 key:(id)fp12 cleanupDict:(BOOL)fp16;
- (void)removeAllAnimationsForObject:(id)fp8;
- (void)addAnimation:(id)fp8 forObject:(id)fp12 key:(id)fp16;
- (id)observers;
- (void)_renderTime:(double)fp8 item:(struct shared_ptr<POPAnimatorItem>)fp16;
- (void)_renderTime:(double)fp8 items:(struct list<std::__1::shared_ptr<POPAnimatorItem>, std::__1::allocator<std::__1::shared_ptr<POPAnimatorItem>>>)fp16;
- (void)_scheduleProcessPendingList;
- (void)_clearPendingListObserver;
- (void)_processPendingList;
- (void)dealloc;
- (id)init;

@end

