/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "POPAnimation.h"

@interface POPCustomAnimation : POPAnimation
{
    id _animate;
    double _currentTime;
    double _elapsedTime;
}

+ (id)animationWithBlock:(id)fp(null);
- (void)setAnimate:(id)fp(null);
- (id)animate;
- (double)elapsedTime;
- (double)currentTime;
- (void).cxx_destruct;
- (void)_appendDescription:(id)fp8 debug:(BOOL)fp12;
- (BOOL)_advance:(id)fp8 currentTime:(double)fp12 elapsedTime:(double)fp20;
- (double)beginTime;
- (id)_init;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

