/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "POPAnimation.h"

@interface POPPropertyAnimation : POPAnimation
{
}

- (void)_appendDescription:(id)fp8 debug:(BOOL)fp12;
- (id)currentValue;
- (void)setToValue:(id)fp8;
- (id)toValue;
- (void)setFromValue:(id)fp8;
- (id)fromValue;
- (void)setProgressMarkers:(id)fp8;
- (id)progressMarkers;
- (void)setProperty:(id)fp8;
- (id)property;
- (void)setClampMode:(unsigned int)fp8;
- (unsigned int)clampMode;
- (void)setRoundingFactor:(float)fp8;
- (float)roundingFactor;
- (void)setAdditive:(BOOL)fp8;
- (BOOL)isAdditive;
- (void)_initState;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

