/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "POPPropertyAnimation.h"

@interface POPSpringAnimation : POPPropertyAnimation
{
}

+ (id)animationWithPropertyNamed:(id)fp8;
+ (id)animation;
+ (void)convertTension:(float)fp8 friction:(float)fp12 toBounciness:(float *)fp16 speed:(float *)fp20;
+ (void)convertBounciness:(float)fp8 speed:(float)fp12 toTension:(float *)fp16 friction:(float *)fp20 mass:(float *)fp24;
- (void)_appendDescription:(id)fp8 debug:(BOOL)fp12;
- (void)_updatedDynamicsMass;
- (void)_updatedDynamicsFriction;
- (void)_updatedDynamicsTension;
- (void)setSolver:(struct SpringSolver<POP::Vector4<double>> *)fp8;
- (struct SpringSolver<POP::Vector4<double>> *)solver;
- (void)setSpringBounciness:(float)fp8;
- (float)springBounciness;
- (void)setSpringSpeed:(float)fp8;
- (float)springSpeed;
- (void)setDynamicsMass:(float)fp8;
- (float)dynamicsMass;
- (void)setDynamicsFriction:(float)fp8;
- (float)dynamicsFriction;
- (void)setDynamicsTension:(float)fp8;
- (float)dynamicsTension;
- (void)setVelocity:(id)fp8;
- (id)velocity;
- (void)dealloc;
- (id)init;
- (void)_initState;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

