/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UITextViewDelegate-Protocol.h"

@interface PSPDFTextView : _ABCreateStringWithAddressDictionary <UITextViewDelegate>
{
    BOOL _settingText;
    BOOL _settingSelection;
    id <UITextViewDelegate> _realDelegate;
}

- (void)setRealDelegate:(id)fp8;
- (id)realDelegate;
- (void).cxx_destruct;
- (id)forwardingTargetForSelector:(SEL)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (BOOL)respondsToSelector:(SEL)fp8;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (void)textViewDidChange:(id)fp8;
- (void)textViewDidChangeSelection:(id)fp8;
- (void)scrollToVisibleCaret;
- (void)scrollToVisibleCaretAnimated:(BOOL)fp8;
- (void)scheduleScrollToVisibleCaretWithDelay:(double)fp8;
- (void)ensureCaretIsVisibleWithReplacementText:(id)fp8;
- (void)scrollRangeToVisibleConsideringInsets:(struct _NSRange)fp8 animated:(BOOL)fp16;
- (void)scrollRectToVisibleConsideringInsets:(struct CGRect)fp8 animated:(BOOL)fp24;
- (void)setSelectedRange:(struct _NSRange)fp8;
- (void)setAttributedText:(id)fp8;
- (void)setText:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (void)customInit;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8 textContainer:(id)fp24;

@end

