/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface RMAddPaymentParameters : _ABCreateStringWithAddressDictionary
{
    id _successBlock;
    id _failureBlock;
}

- (void)setFailureBlock:(id)fp(null);
- (id)failureBlock;
- (void)setSuccessBlock:(id)fp(null);
- (id)successBlock;
- (void).cxx_destruct;

@end

