/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "SKProductsRequestDelegate-Protocol.h"

@class RMStore;

@interface RMProductsRequestDelegate : _ABCreateStringWithAddressDictionary <SKProductsRequestDelegate>
{
    id _successBlock;
    id _failureBlock;
    RMStore *_store;
}

- (void)setStore:(id)fp8;
- (id)store;
- (void)setFailureBlock:(id)fp(null);
- (id)failureBlock;
- (void)setSuccessBlock:(id)fp(null);
- (id)successBlock;
- (void).cxx_destruct;
- (void)request:(id)fp8 didFailWithError:(id)fp12;
- (void)requestDidFinish:(id)fp8;
- (void)productsRequest:(id)fp8 didReceiveResponse:(id)fp12;

@end

