/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSThread, UIWebView;

@interface SIOSocket : _ABCreateStringWithAddressDictionary
{
    id _onConnect;
    id _onConnectError;
    id _onDisconnect;
    id _onError;
    id _onReconnect;
    id _onReconnectionAttempt;
    id _onReconnectionError;
    NSThread *_thread;
    UIWebView *_javascriptWebView;
}

+ (void)socketWithHost:(id)fp8 reconnectAutomatically:(BOOL)fp12 attemptLimit:(int)fp16 withDelay:(double)fp20 maximumDelay:(double)fp28 timeout:(double)fp36 response:(id)fp(null);
+ (void)socketWithHost:(id)fp8 response:(id)fp(null);
- (void)setJavascriptWebView:(id)fp8;
- (id)javascriptWebView;
- (void)setThread:(id)fp8;
- (id)thread;
- (void)setOnReconnectionError:(id)fp(null);
- (id)onReconnectionError;
- (void)setOnReconnectionAttempt:(id)fp(null);
- (id)onReconnectionAttempt;
- (void)setOnReconnect:(id)fp(null);
- (id)onReconnect;
- (void)setOnError:(id)fp(null);
- (id)onError;
- (void)setOnDisconnect:(id)fp(null);
- (id)onDisconnect;
- (void)setOnConnectError:(id)fp(null);
- (id)onConnectError;
- (void)setOnConnect:(id)fp(null);
- (id)onConnect;
- (void).cxx_destruct;
- (void)close;
- (void)evaluateScript:(id)fp8;
- (void)emit:(id)fp8 args:(struct NSArray *)fp12;
- (void)emit:(id)fp8;
- (void)on:(id)fp8 callback:(id)fp(null);
- (id)javascriptContext;
- (void)dealloc;

@end

