/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIView;

@interface SLKInputAccessoryView : _ABCreateStringWithAddressDictionary
{
    UIView *_keyboardViewProxy;
}

- (id)keyboardViewProxy;
- (void).cxx_destruct;
- (void)willMoveToSuperview:(id)fp8;

@end

