/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SMCalloutBackgroundView.h"

@class UIImageView, UIView;

@interface SMCalloutMaskedBackgroundView : SMCalloutBackgroundView
{
    UIView *_containerView;
    UIView *_containerBorderView;
    UIView *_arrowView;
    UIImageView *_arrowImageView;
    UIImageView *_arrowHighlightedImageView;
    UIImageView *_arrowBorderView;
}

- (void)setArrowBorderView:(id)fp8;
- (id)arrowBorderView;
- (void)setArrowHighlightedImageView:(id)fp8;
- (id)arrowHighlightedImageView;
- (void)setArrowImageView:(id)fp8;
- (id)arrowImageView;
- (void)setArrowView:(id)fp8;
- (id)arrowView;
- (void)setContainerBorderView:(id)fp8;
- (id)containerBorderView;
- (void)setContainerView:(id)fp8;
- (id)containerView;
- (void).cxx_destruct;
- (id)contentMask;
- (void)layoutSubviews;
- (id)image:(id)fp8 withColor:(id)fp12;
- (void)setHighlighted:(BOOL)fp8;
- (void)setArrowPoint:(struct CGPoint)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

