/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SMCalloutBackgroundView.h"

@class UIImage, UIImageView;

@interface SMCalloutImageBackgroundView : SMCalloutBackgroundView
{
    UIImageView *leftCap;
    UIImageView *rightCap;
    UIImageView *topAnchor;
    UIImageView *bottomAnchor;
    UIImageView *leftBackground;
    UIImageView *rightBackground;
    UIImage *_leftCapImage;
    UIImage *_rightCapImage;
    UIImage *_topAnchorImage;
    UIImage *_bottomAnchorImage;
    UIImage *_backgroundImage;
}

- (void)setBackgroundImage:(id)fp8;
- (void)setBottomAnchorImage:(id)fp8;
- (void)setTopAnchorImage:(id)fp8;
- (void)setRightCapImage:(id)fp8;
- (void)setLeftCapImage:(id)fp8;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setArrowPoint:(struct CGPoint)fp8;
- (id)backgroundImage;
- (id)bottomAnchorImage;
- (id)topAnchorImage;
- (id)rightCapImage;
- (id)leftCapImage;
- (id)initWithFrame:(struct CGRect)fp8;

@end

