/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableDictionary, UIColor, UIImage;

@interface StyledPageControl : _ABCreateStringWithAddressDictionary
{
    BOOL _hidesForSinglePage;
    UIColor *_coreNormalColor;
    UIColor *_coreSelectedColor;
    UIColor *_strokeNormalColor;
    UIColor *_strokeSelectedColor;
    int _currentPage;
    int _numberOfPages;
    int _pageControlStyle;
    int _strokeWidth;
    int _diameter;
    int _gapWidth;
    UIImage *_thumbImage;
    UIImage *_selectedThumbImage;
    NSMutableDictionary *_thumbImageForIndex;
    NSMutableDictionary *_selectedThumbImageForIndex;
}

- (void)setSelectedThumbImageForIndex:(id)fp8;
- (id)selectedThumbImageForIndex;
- (void)setThumbImageForIndex:(id)fp8;
- (id)thumbImageForIndex;
- (void)setSelectedThumbImage:(id)fp8;
- (id)selectedThumbImage;
- (void)setThumbImage:(id)fp8;
- (id)thumbImage;
- (void)setGapWidth:(int)fp8;
- (int)gapWidth;
- (void)setDiameter:(int)fp8;
- (int)diameter;
- (void)setStrokeWidth:(int)fp8;
- (int)strokeWidth;
- (int)pageControlStyle;
- (void)setHidesForSinglePage:(BOOL)fp8;
- (BOOL)hidesForSinglePage;
- (int)numberOfPages;
- (int)currentPage;
- (void)setStrokeSelectedColor:(id)fp8;
- (id)strokeSelectedColor;
- (void)setStrokeNormalColor:(id)fp8;
- (id)strokeNormalColor;
- (void)setCoreSelectedColor:(id)fp8;
- (id)coreSelectedColor;
- (void)setCoreNormalColor:(id)fp8;
- (id)coreNormalColor;
- (void).cxx_destruct;
- (id)selectedThumbImageForIndex:(int)fp8;
- (void)setSelectedThumbImage:(id)fp8 forIndex:(int)fp12;
- (id)thumbImageForIndex:(int)fp8;
- (void)setThumbImage:(id)fp8 forIndex:(int)fp12;
- (void)setNumberOfPages:(int)fp8;
- (void)setCurrentPage:(int)fp8;
- (void)setPageControlStyle:(int)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)onTapped:(id)fp8;
- (void)setup;
- (id)initWithCoder:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

