/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TLAnalyticsSource-Protocol.h"

@interface TLAdobeSource : _ABCreateStringWithAddressDictionary <TLAnalyticsSource>
{
}

+ (void)tlsw_trackLocation:(id)fp8 data:(id)fp12;
+ (void)tlsw_trackActionFromBackground:(id)fp8 data:(id)fp12;
+ (void)tlsw_trackAction:(id)fp8 data:(id)fp12;
+ (void)tlsw_trackState:(id)fp8 data:(id)fp12;
+ (void)tlsw_setUserIdentifier:(id)fp8;
+ (void)swizzle;
- (BOOL)trackEvent:(id)fp8 value:(id)fp12 metaData:(id)fp16;

@end

