/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSDate, NSNumber;

@interface TLApplicationLifeCycle : _ABCreateStringWithAddressDictionary
{
    NSNumber *_maxBackgroundTime;
    NSDate *_backgroundedDate;
}

- (void)setBackgroundedDate:(id)fp8;
- (id)backgroundedDate;
- (void)setMaxBackgroundTime:(id)fp8;
- (id)maxBackgroundTime;
- (void).cxx_destruct;
- (void)appDidTakeScreenShot:(id)fp8;
- (void)appOrientationChanged:(id)fp8;
- (void)appDidReceiveMemoryWarning:(id)fp8;
- (void)appWillTerminate:(id)fp8;
- (void)appWillReturnFromBackground:(id)fp8;
- (void)appEnteredBackground:(id)fp8;
- (void)appBecameActive:(id)fp8;
- (void)addAppLifeCycleNotifications;
- (void)checkForNewSession;
- (void)dealloc;
- (id)init;

@end

