/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableArray;

@interface TLCodeExperimentManager : _ABCreateStringWithAddressDictionary
{
    NSMutableArray *_pendingCodeExperiments;
    NSMutableArray *_pendingGetExpNames;
}

+ (id)sharedManager;
- (void)setPendingGetExpNames:(id)fp8;
- (id)pendingGetExpNames;
- (void)setPendingCodeExperiments:(id)fp8;
- (id)pendingCodeExperiments;
- (void).cxx_destruct;
- (id)checkVariablesForNumbers:(id)fp8 variableNames:(id)fp12;
- (id)getVariableNamesForIDs:(id)fp8;
- (void)getRunningExperiments:(id)fp(null);
- (void)performPendingGetRunningExperiments;
- (void)runCodeExperimentWithName:(id)fp8 withBaseline:(id)fp(null) variations:(void)fp12 variationBlock:(id)fp16;
- (void)performPendingCodeExperiments;
- (id)init;

@end

