/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TLCodeBlockManager : _ABCreateStringWithAddressDictionary
{
}

+ (id)sharedManager;
- (void)socketPushWithName:(id)fp8;
- (void)checkSocketRoomAndPushWithName:(id)fp8;
- (BOOL)performRunWithName:(id)fp8 withCodeBlock:(id)fp(null);
- (void)getPropertiesThenRun:(id)fp8 withCodeBlock:(id)fp(null);
- (void)runCodeBlockWithName:(id)fp8 withCodeBlock:(id)fp(null);
- (id)init;

@end

