/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TLDataSetter : _ABCreateStringWithAddressDictionary
{
}

+ (void)setValuesInAppearanceElement:(id)fp8 elementClass:(Class)fp12 forPropertiesDic:(id)fp16;
+ (void)setStatusBarFromProperties:(id)fp8;
+ (void)setValuesInViewController:(id)fp8 forViewKey:(id)fp12;
+ (void)setImageAtIndexesForElement:(id)fp8 fromDic:(id)fp12 key:(id)fp16;
+ (void)setNumberAtIndexesForElement:(id)fp8 fromDic:(id)fp12 key:(id)fp16;
+ (void)setSizeAtIndexesForElement:(id)fp8 fromDic:(id)fp12 key:(id)fp16;
+ (void)setStringsAtIndexesForElement:(id)fp8 fromDic:(id)fp12 key:(id)fp16;
+ (BOOL)setValuesForControlStateProperty:(id)fp8 fromDic:(id)fp12 key:(id)fp16;
+ (void)setModifiedConstraintsForElement:(id)fp8 fromArray:(id)fp12;
+ (id)createStateDicFromValue:(id)fp8 state:(int)fp12;
+ (void)resetValuesInElement:(id)fp8;
+ (void)resetValuesInSubViewElements:(id)fp8;
+ (void)setOrigValueForElement:(id)fp8 key:(id)fp12;
+ (void)setOrigValue:(id)fp8 state:(int)fp12 forElement:(id)fp16 key:(id)fp20;
+ (BOOL)setValueInElement:(id)fp8 lpElement:(id)fp12 fromValue:(id)fp16 key:(id)fp20;
+ (void)setValuesInElement:(id)fp8 propertiesDic:(id)fp12;

@end

