/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface TLDeviceInfo : _ABCreateStringWithAddressDictionary
{
    BOOL _hasStarted;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_waitForNetworkBlocks;
}

- (void)setHasStarted:(BOOL)fp8;
- (BOOL)hasStarted;
- (void)setWaitForNetworkBlocks:(id)fp8;
- (id)waitForNetworkBlocks;
- (void)setQueue:(id)fp8;
- (id)queue;
- (void).cxx_destruct;
- (id)getAdvertizingID;
- (id)tlUUID;
- (id)getDeviceCarrier;
- (id)deviceModel;
- (void)getDevicePropertiesReturnBlock:(id)fp(null);
- (void)waitForNetworkChange:(id)fp(null);
- (void)networkStatusChanged;
- (id)init;

@end

