/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TLElementProtocol <NSObject>
- (void)setTl_isSettingUP:(BOOL)fp8;
- (BOOL)tl_isSettingUP;
- (void)setTl_isSettingProperties:(BOOL)fp8;
- (BOOL)tl_isSettingProperties;
- (void)setTl_classInitProperties:(id)fp8;
- (id)tl_classInitProperties;
- (void)setTl_initProperties:(id)fp8;
- (id)tl_initProperties;
- (void)setTl_origProperties:(id)fp8;
- (id)tl_origProperties;
- (void)setTl_stateName:(id)fp8;
- (id)tl_stateName;
- (void)setTl_styleKey:(id)fp8;
- (id)tl_styleKey;
- (void)setTl_elementKey:(id)fp8;
- (id)tl_elementKey;
- (void)tl_setOrigPropertyValue:(id)fp8 forKey:(id)fp12;
- (id)tl_getOrigPropertyValueForKey:(id)fp8;
@end

