/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UIAlertViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, TLImageDownloader;

@interface TLImagesManager : _ABCreateStringWithAddressDictionary <UIAlertViewDelegate>
{
    id <TLImagesManagerDelegate> _delegate;
    NSMutableArray *_localImageAssets;
    NSMutableDictionary *_loadingImageBlocks;
    TLImageDownloader *_imageDownloader;
    NSMutableArray *_currentImgPaths;
    NSMutableArray *_currentTempImgPaths;
}

+ (id)sharedManager;
- (void)setCurrentTempImgPaths:(id)fp8;
- (id)currentTempImgPaths;
- (void)setCurrentImgPaths:(id)fp8;
- (id)currentImgPaths;
- (void)setImageDownloader:(id)fp8;
- (id)imageDownloader;
- (void)setLoadingImageBlocks:(id)fp8;
- (id)loadingImageBlocks;
- (void)setLocalImageAssets:(id)fp8;
- (id)localImageAssets;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (id)saveInBackgroundTempImg:(id)fp8 fileName:(id)fp12 saveLargeAsJPEG:(BOOL)fp16 async:(BOOL)fp20 returnBlock:(id)fp(null);
- (int)screenSize;
- (id)saveTempImg:(id)fp8 fileName:(id)fp12;
- (id)getTempImageDirectory;
- (id)getScreenShotOfView:(id)fp8;
- (void)getScreenShot;
- (void)uploadScreenShot;
- (BOOL)localImageFileExistsForPath:(id)fp8 scale:(float)fp12;
- (void)getLocalImage:(id)fp8 scale:(float)fp12 returnBlock:(id)fp(null);
- (void)cleanupOldImages;
- (float)imageScaleFromDeviceTags:(id)fp8;
- (void)checkAllLocalImagesOldProperties:(id)fp8 returnBlock:(id)fp(null);
- (void)getAllLocalImageAssets;
- (void)getLocalImageForImgDic:(id)fp8 returnBlock:(id)fp(null);
- (id)init;

@end

