/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSDate, UIImageView, UIView;

@interface TLLaunchImage : _ABCreateStringWithAddressDictionary
{
    BOOL _showingLaunchImage;
    UIImageView *_launchImageView;
    UIView *_launchView;
    NSDate *_launchDate;
}

+ (void)showLaunchImageInWindow:(id)fp8;
- (void)setLaunchDate:(id)fp8;
- (id)launchDate;
- (void)setLaunchView:(id)fp8;
- (id)launchView;
- (void)setLaunchImageView:(id)fp8;
- (id)launchImageView;
- (void)setShowingLaunchImage:(BOOL)fp8;
- (BOOL)showingLaunchImage;
- (void).cxx_destruct;
- (void)removeLaunchImage;
- (void)showBlackScreenMaxTime:(id)fp8;
- (void)showLaunchImage:(id)fp8 maxTime:(id)fp12;
- (BOOL)showLaunchStoryboard:(id)fp8 maxTime:(id)fp12;
- (void)findLaunchImageMaxTime:(id)fp8;
- (id)init;

@end

