/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface TLLocationManagerDelegate : _ABCreateStringWithAddressDictionary
{
    NSString *_className;
}

+ (void)tlsw_locationManager:(id)fp8 didExitRegion:(id)fp12;
+ (void)tlsw_locationManager:(id)fp8 didEnterRegion:(id)fp12;
+ (void)tlsw_locationManager:(id)fp8 didUpdateLocations:(id)fp12;
+ (void)tlsw_locationManager:(id)fp8 didChangeAuthorizationStatus:(int)fp12;
- (void)setClassName:(id)fp8;
- (id)className;
- (void).cxx_destruct;
- (void)tl_swizzle:(id)fp8;
- (id)initWithDelegate:(id)fp8;

@end

