/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TLLocationSource : _ABCreateStringWithAddressDictionary
{
}

+ (void)tlsw_stopMonitoringForRegion:(id)fp8;
+ (void)tlsw_startMonitoringForRegion:(id)fp8;
+ (void)tlsw_setDelegate:(id)fp8;
+ (void)swizzle;

@end

