/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TLAnalyticsManagerDelegate-Protocol.h"
#import "TLImagesManagerDelegate-Protocol.h"
#import "TLPropertiesDelegate-Protocol.h"
#import "TLSocketConnectionDelegate-Protocol.h"
#import "TLTapViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSNumber, NSString, TLApplicationLifeCycle, TLLaunchImage, TLProperties, TLTapView, UIActionSheet, UIViewController;

@interface TLManager : _ABCreateStringWithAddressDictionary <TLImagesManagerDelegate, TLSocketConnectionDelegate, TLPropertiesDelegate, TLAnalyticsManagerDelegate, TLTapViewDelegate, UIActionSheetDelegate>
{
    BOOL _isFuzzyMatchingEnabled;
    BOOL _isLoadingProperties;
    BOOL _liveUpdate;
    BOOL _isLiveUpdateSetByDev;
    BOOL _isDebug;
    BOOL _isActive;
    BOOL _tlLoggingEnabled;
    BOOL _seenFirstWindow;
    BOOL _shownLaunchImage;
    BOOL _showProdChanges;
    BOOL _userDisableShakeMenu;
    BOOL _loadedInitialProperties;
    BOOL _isBorderDisabled;
    BOOL _isInit;
    NSString *_deviceToken;
    id <TaplyticsDelegate> _delegate;
    NSString *_apiKey;
    NSNumber *_userShowLaunchImageTime;
    NSNumber *_userPushSandbox;
    TLLaunchImage *_tlLaunchImage;
    UIViewController *_pushingFromVC;
    NSMutableDictionary *_tapElements;
    NSMutableDictionary *_swClasses;
    TLProperties *_tlProperties;
    int _server;
    NSString *_hostName;
    NSString *_httpPath;
    NSDate *_startupTime;
    NSDate *_lastLoadPropertiesDate;
    NSDate *_lastGetPropertiesDate;
    UIActionSheet *_tlActionSheet;
    TLApplicationLifeCycle *_tlAppLifecycle;
    NSMutableArray *_loadTLPropertiesCallbacks;
    NSDictionary *_experimentDic;
    TLTapView *_experimentHighlightView;
    NSDictionary *_chooseElementDic;
    NSMutableDictionary *_highlightedViews;
    NSMutableDictionary *_actionSheetVariations;
    NSDictionary *_flowDic;
    NSMutableDictionary *_viewFlowDic;
    NSDictionary *_chooseViewDic;
}

+ (void)startTaplyticsAPIKey:(id)fp8 options:(id)fp12;
+ (int)getServerFromOptions:(id)fp8;
+ (void)resetSharedManager;
+ (id)sharedManager;
- (void)setIsInit:(BOOL)fp8;
- (BOOL)isInit;
- (void)setIsBorderDisabled:(BOOL)fp8;
- (BOOL)isBorderDisabled;
- (void)setChooseViewDic:(id)fp8;
- (id)chooseViewDic;
- (void)setViewFlowDic:(id)fp8;
- (id)viewFlowDic;
- (void)setFlowDic:(id)fp8;
- (id)flowDic;
- (void)setActionSheetVariations:(id)fp8;
- (id)actionSheetVariations;
- (void)setHighlightedViews:(id)fp8;
- (id)highlightedViews;
- (void)setChooseElementDic:(id)fp8;
- (id)chooseElementDic;
- (void)setExperimentHighlightView:(id)fp8;
- (id)experimentHighlightView;
- (void)setExperimentDic:(id)fp8;
- (id)experimentDic;
- (void)setLoadedInitialProperties:(BOOL)fp8;
- (BOOL)loadedInitialProperties;
- (void)setLoadTLPropertiesCallbacks:(id)fp8;
- (id)loadTLPropertiesCallbacks;
- (void)setTlAppLifecycle:(id)fp8;
- (id)tlAppLifecycle;
- (void)setTlActionSheet:(id)fp8;
- (id)tlActionSheet;
- (void)setLastGetPropertiesDate:(id)fp8;
- (id)lastGetPropertiesDate;
- (void)setLastLoadPropertiesDate:(id)fp8;
- (id)lastLoadPropertiesDate;
- (void)setStartupTime:(id)fp8;
- (id)startupTime;
- (void)setHttpPath:(id)fp8;
- (id)httpPath;
- (void)setHostName:(id)fp8;
- (id)hostName;
- (void)setServer:(int)fp8;
- (int)server;
- (void)setTlProperties:(id)fp8;
- (id)tlProperties;
- (void)setSwClasses:(id)fp8;
- (id)swClasses;
- (void)setTapElements:(id)fp8;
- (id)tapElements;
- (void)setPushingFromVC:(id)fp8;
- (id)pushingFromVC;
- (void)setTlLaunchImage:(id)fp8;
- (id)tlLaunchImage;
- (void)setUserDisableShakeMenu:(BOOL)fp8;
- (BOOL)userDisableShakeMenu;
- (void)setShowProdChanges:(BOOL)fp8;
- (BOOL)showProdChanges;
- (void)setShownLaunchImage:(BOOL)fp8;
- (BOOL)shownLaunchImage;
- (void)setSeenFirstWindow:(BOOL)fp8;
- (BOOL)seenFirstWindow;
- (void)setTlLoggingEnabled:(BOOL)fp8;
- (BOOL)tlLoggingEnabled;
- (void)setUserPushSandbox:(id)fp8;
- (id)userPushSandbox;
- (void)setIsActive:(BOOL)fp8;
- (BOOL)isActive;
- (void)setIsDebug:(BOOL)fp8;
- (BOOL)isDebug;
- (void)setIsLiveUpdateSetByDev:(BOOL)fp8;
- (BOOL)isLiveUpdateSetByDev;
- (void)setLiveUpdate:(BOOL)fp8;
- (BOOL)liveUpdate;
- (void)setIsLoadingProperties:(BOOL)fp8;
- (BOOL)isLoadingProperties;
- (void)setUserShowLaunchImageTime:(id)fp8;
- (id)userShowLaunchImageTime;
- (void)setApiKey:(id)fp8;
- (id)apiKey;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setIsFuzzyMatchingEnabled:(BOOL)fp8;
- (void).cxx_destruct;
- (BOOL)isFuzzyMatchingEnabled;
- (void)setDeviceToken:(id)fp8;
- (id)deviceToken;
- (void)uploadScreenShotImage:(id)fp8 thumbnial:(id)fp12;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)showTLActionSheetTitle:(id)fp8 buttons:(id)fp12 tag:(int)fp16;
- (void)showTLVariationActionSheet:(id)fp8;
- (void)showTLHotfixActionSheet;
- (void)showTLExperimentActionSheet;
- (void)showTLActionSheet;
- (void)presentAlertController:(id)fp8;
- (void)showUIAlertTitle:(id)fp8 msg:(id)fp12 cancel:(BOOL)fp16;
- (void)bringBorderToFront;
- (void)deviceShook;
- (void)animateHightlightView:(id)fp8 duration:(id)fp12 time:(id)fp16 finishedBlock:(id)fp(null);
- (void)highlightTLElement:(id)fp8 showBackground:(BOOL)fp12 forDuration:(id)fp16;
- (void)highlightElementforKey:(id)fp8 styleKey:(id)fp12 showBackground:(BOOL)fp16 duration:(id)fp20;
- (void)removeAllHighlightTapViews;
- (void)highlightTapView:(id)fp8 showBackground:(BOOL)fp12 key:(id)fp16;
- (void)hideHighlightViewFinishedBlock:(id)fp(null);
- (void)longPressLabel:(id)fp8;
- (void)checkFuzzyIsEnabled;
- (void)highlightScreenForTitle:(id)fp8 type:(int)fp12 animate:(BOOL)fp16;
- (void)uploadExperimentElements:(id)fp8;
- (id)getNewInitElementKey:(Class)fp8 frame:(struct CGRect)fp12 index:(int)fp28;
- (void)getViewScreenShots:(id)fp8 returnBlock:(id)fp(null);
- (BOOL)emitViewFromScreenShots:(id)fp8;
- (void)tapViewTouches:(id)fp8;
- (void)postNewTapElement:(id)fp8 finishBlock:(id)fp(null);
- (void)saveNewTapElement:(id)fp8 tapElementDic:(id)fp12;
- (void)postChosenView:(id)fp8 screenShots:(id)fp12;
- (void)getFoundView;
- (id)viewDicFromVC:(id)fp8;
- (void)pairTokenSuccessful;
- (void)foundView:(id)fp8;
- (void)chooseView:(id)fp8;
- (void)foundNewFlowView:(id)fp8;
- (void)getNewFlowView:(id)fp8;
- (void)getFlowButton:(id)fp8;
- (void)selectedTapElement:(id)fp8;
- (void)highlightTapElement:(id)fp8;
- (void)setBorderPickText:(id)fp8;
- (void)setPickElementsMode:(id)fp8;
- (void)userPickElements:(id)fp8;
- (void)elementStatusUpdate;
- (void)reconnectionStatusWithAttempt:(int)fp8;
- (void)hideExperiment;
- (void)experimentUpdated:(id)fp8;
- (void)showExperiment:(id)fp8 sendSocket:(BOOL)fp12;
- (id)getTitle;
- (void)reloadDataSocketEvent;
- (void)postFlowView:(id)fp8 imageDic:(id)fp12;
- (void)postFlowDestViewImage:(id)fp8;
- (void)postFlowButtonImages:(id)fp8;
- (void)foundFlowToView:(id)fp8;
- (void)foundViewFlowButton:(id)fp8;
- (void)viewAppeared:(id)fp8;
- (id)getServerPath:(id)fp8;
- (void)performBackgroundFetch:(id)fp(null);
- (void)changeLiveUpdate:(BOOL)fp8;
- (void)checkForLiveUpdateOverride:(id)fp8;
- (void)checkLiveUpdate:(BOOL)fp8 withProperties:(id)fp12;
- (void)getPropertiesFromServer:(id)fp8 returnBlock:(id)fp(null);
- (void)performLoadPropertiesFromServer:(id)fp8 returnBlock:(id)fp(null);
- (void)tlPropertiesLoadedCallback:(id)fp(null);
- (void)loadPropertiesFromServer;
- (void)setTLServer:(int)fp8;
- (void)startTaplyticsAPIKey:(id)fp8 server:(int)fp12 liveUpdate:(BOOL)fp16;
- (void)startTaplyticsAPIKey:(id)fp8 server:(int)fp12 options:(id)fp16;
- (void)startTaplyticsAPIKey:(id)fp8 server:(int)fp12;
- (void)uploadAppIcon;
- (BOOL)checkIsActive;
- (id)init;

@end

