/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TLAnalyticsSource-Protocol.h"

@interface TLMixpanelSource : _ABCreateStringWithAddressDictionary <TLAnalyticsSource>
{
}

+ (void)tlsw_deleteUser;
+ (void)tlsw_clearCharges;
+ (void)tlsw_trackCharge:(id)fp8 withProperties:(id)fp12;
+ (void)tlsw_union:(id)fp8;
+ (void)tlsw_append:(id)fp8;
+ (void)tlsw_increment:(id)fp8 by:(id)fp12;
+ (void)tlsw_increment:(id)fp8;
+ (void)tlsw_setOnce:(id)fp8;
+ (void)tlsw_set:(id)fp8 to:(id)fp12;
+ (void)tlsw_set:(id)fp8;
+ (void)tlsw_showNotification;
+ (void)tlsw_showNotificationWithType:(id)fp8;
+ (void)tlsw_showNotificationWithID:(unsigned int)fp8;
+ (void)tlsw_showSurvey;
+ (void)tlsw_showSurveyWithID:(unsigned int)fp8;
+ (void)tlsw_trackPushNotification:(id)fp8;
+ (void)tlsw_track:(id)fp8 properties:(id)fp12;
+ (id)getSuperPropertiesExistProperties:(id)fp8;
+ (void)swizzle;
- (BOOL)useCachedData;
- (BOOL)trackEvent:(id)fp8 value:(id)fp12 metaData:(id)fp16;

@end

