/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSData, NSString;

@interface TLPushManager : _ABCreateStringWithAddressDictionary
{
    NSData *_pushToken;
    NSString *_pushString;
}

+ (id)sharedManager;
- (void)setPushString:(id)fp8;
- (id)pushString;
- (void)setPushToken:(id)fp8;
- (id)pushToken;
- (void).cxx_destruct;
- (void)disablePushForUser;
- (BOOL)hasPlatformCert:(id)fp8;
- (BOOL)hasProjectPushCert;
- (BOOL)isUserRegisteredForPush;
- (void)performSaveToken;
- (void)saveToken;
- (void)trackPushToken:(id)fp8;
- (void)registerPushNotifications:(int)fp8 catetories:(id)fp12;
- (void)checkHasPushToken;
- (id)init;

@end

