/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TLSwizzleTypeMethods : _ABCreateStringWithAddressDictionary
{
}

+ (void)swizzle_Void_CGSize_Index_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_CGFloat_Index_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIImage_Index_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSString_Index_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UITextAttributes_State_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIImage_State_BarMetrics_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIImage_State_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIColor_State_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSAttributedString_State_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSString_State_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIProgressViewStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIWebPaginationMode_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIWebPaginationBreakingMode_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIDataDetectorTypes_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UITableViewCellSeparatorStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIControlContentVerticalAlignment_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIControlContentHorizontalAlignment_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UISearchBarStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIDatePickerMode_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UITableViewCellSelectionStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIScrollViewKeyboardDismissMode_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIScrollViewIndicatorStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UICollectionViewScrollDirection_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIAlertViewStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIActionSheetStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UITabBarItemPositioning_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIBarStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIActivityIndicatorViewStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIOffset_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UITextBorderStyle_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIBaselineAdjustment_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSLineBreakMode_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSTextAlignment_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UITextAttributes_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIEdgeInsets_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIImage_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_BOOL_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSNumber_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_CGSize_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_CGPoint_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_CGRect_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_CGFloat_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_Float_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSTimeInterval_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_Double_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSInteger_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIColor_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_UIFont_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSAttributedString_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_NSString_obj:(id)fp8 selector:(SEL)fp12 propertyKey:(id)fp16;
+ (void)swizzle_Void_Block_obj:(id)fp8 selector:(SEL)fp12 block:(id)fp(null);

@end

