/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableArray, NSMutableDictionary, UIViewController;

@interface TLViewHierarchyTool : _ABCreateStringWithAddressDictionary
{
    NSMutableDictionary *_elements;
    NSMutableDictionary *_styles;
    id _finishedBlock;
    id _topVCBlock;
    id _viewCheckBlock;
    NSMutableArray *_hierarchy;
    UIViewController *_stopVC;
}

+ (int)fuzzyCheckView:(id)fp8 frame:(struct CGRect)fp12 fuzzyFrame:(int)fp28 properties:(id)fp32;
+ (id)getViewOrigProperties:(id)fp8;
+ (id)createUniqueId:(id)fp8;
+ (id)getConstraintProperties:(id)fp8 isIncludeConstraint:(BOOL)fp12;
+ (id)getViewConstraints:(id)fp8 isIncludeConstraint:(BOOL)fp12;
+ (void)checkUIViewController:(id)fp8 subViews:(id)fp(null);
+ (void)checkUIView:(id)fp8 block:(id)fp(null);
+ (id)getCellViewInfo:(id)fp8 view:(id)fp12;
+ (BOOL)compareSuperViewHierarchy:(id)fp8 with:(id)fp12 verbose:(BOOL)fp16 checkCellBlock:(id)fp(null);
+ (id)getSuperViewControllerForView:(id)fp8;
+ (id)getSuperViewControllerHierarchyForView:(id)fp8;
+ (id)getAllViewControllers;
+ (id)checkSubviewsForVC:(id)fp8;
+ (id)getCurrentTopNavViewController;
+ (id)getCurrentTopViewController;
+ (id)getTopViewControllerFrom:(id)fp8;
+ (id)getIndexPathForCell:(id)fp8;
+ (id)getIndexPathForCellSubView:(id)fp8;
+ (id)getViewHierarchy:(id)fp8;
+ (id)viewHierarchyToolViewCheckBlock:(id)fp(null) finishedBlock:(void)fp8;
+ (id)viewHierarchyWithTopVC:(id)fp8 finishedBlock:(id)fp(null);
+ (id)viewHierarchyToolWithNewElements:(id)fp8 newStyles:(id)fp12 finishedBlock:(id)fp(null);
+ (void)load;
- (void)setStopVC:(id)fp8;
- (id)stopVC;
- (void)setHierarchy:(id)fp8;
- (id)hierarchy;
- (void)setViewCheckBlock:(id)fp(null);
- (id)viewCheckBlock;
- (void)setTopVCBlock:(id)fp(null);
- (id)topVCBlock;
- (void)setFinishedBlock:(id)fp(null);
- (id)finishedBlock;
- (void)setStyles:(id)fp8;
- (id)styles;
- (void)setElements:(id)fp8;
- (id)elements;
- (void).cxx_destruct;
- (void)checkUISplitViewController:(id)fp8;
- (void)checkUIPopoverController:(id)fp8;
- (void)checkUITabBarController:(id)fp8;
- (void)checkUINavigationController:(id)fp8;
- (void)checkUIViewController:(id)fp8 performOtherChecksBlock:(id)fp(null);
- (void)checkUIViewControllerType:(id)fp8;
- (void)checkUIBarItems:(id)fp8;
- (void)checkUIView:(id)fp8;
- (BOOL)checkIfLPClass:(id)fp8;
- (void)findViewHierarchies;
- (void)checkWindowView:(id)fp8;
- (void)addToHierarchy:(id)fp8;
- (id)initWithViewCheckBlock:(id)fp(null) finishedBlock:(void)fp8;
- (id)initWithViewHierarchyWithTopVC:(id)fp8 finishedBlock:(id)fp(null);
- (id)initWithNewElements:(id)fp8 newStyles:(id)fp12 finishedBlock:(id)fp(null);

@end

