/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TNDRLabel : _ABCreateStringWithAddressDictionary
{
    struct UIEdgeInsets _tndr_textInsets;
}

- (struct UIEdgeInsets)tndr_textInsets;
- (void)drawTextInRect:(struct CGRect)fp8;
- (void)setTndr_textInsets:(struct UIEdgeInsets)fp8;

@end

