/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class TNDRGroupFriend, UIButton, UIImageView;

@interface TNDRGroupCreateAvatar : _ABCreateStringWithAddressDictionary
{
    BOOL _avatarIsMe;
    TNDRGroupFriend *_selectedFriend;
    UIImageView *_avatarPlaceholder;
    UIImageView *_avatarImageView;
    UIButton *_deleteButton;
}

+ (BOOL)requiresConstraintBasedLayout;
- (void)setDeleteButton:(id)fp8;
- (id)deleteButton;
- (void)setAvatarImageView:(id)fp8;
- (id)avatarImageView;
- (void)setAvatarPlaceholder:(id)fp8;
- (id)avatarPlaceholder;
- (BOOL)avatarIsMe;
- (id)selectedFriend;
- (void).cxx_destruct;
- (void)notifyFriendDeletion;
- (void)animateDeleteVisible:(BOOL)fp8;
- (void)setAvatarIsMe:(BOOL)fp8;
- (void)setSelectedFriend:(id)fp8;
- (void)handleDeleteButtonTapped:(id)fp8;
- (void)adjustMaskOnImage;
- (void)layoutSubviews;
- (void)setupConstraints;
- (void)setupDeleteButton;
- (void)setupAvatar;
- (void)setup;
- (id)init;

@end

