/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSDate, NSURL;

@interface TNDRInstagramPhotoData : _ABCreateStringWithAddressDictionary
{
    NSDate *_date;
    NSURL *_instagramURL;
    NSURL *_thumbnailURL;
    NSURL *_fullPhotoURL;
}

- (void)setFullPhotoURL:(id)fp8;
- (id)fullPhotoURL;
- (void)setThumbnailURL:(id)fp8;
- (id)thumbnailURL;
- (void)setInstagramURL:(id)fp8;
- (id)instagramURL;
- (void)setDate:(id)fp8;
- (id)date;
- (void).cxx_destruct;
- (id)debugDescription;
- (void)parseDictionary:(id)fp8;
- (id)initWithDictionary:(id)fp8;

@end

