/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, StyledPageControl, UICollectionViewFlowLayout, UIImage;

@interface TNDRPhotoPageController : _ABCreateStringWithAddressDictionary
{
    StyledPageControl *_photoPageControl;
    UICollectionViewFlowLayout *_flowLayout;
    UIImage *_grayImage;
    BOOL _shouldReloadCollectionViewWhenViewAppears;
    id <TNDRPhotoPageControllerDelegate> _delegate;
    NSArray *_photoData;
    UIImage *_lastLoadedImage;
    unsigned int _averagedSelectedPhotoIndex;
    unsigned int _lastLoadedIndex;
}

- (void)setShouldReloadCollectionViewWhenViewAppears:(BOOL)fp8;
- (BOOL)shouldReloadCollectionViewWhenViewAppears;
- (void)setLastLoadedIndex:(unsigned int)fp8;
- (unsigned int)lastLoadedIndex;
- (void)setAveragedSelectedPhotoIndex:(unsigned int)fp8;
- (unsigned int)averagedSelectedPhotoIndex;
- (void)setLastLoadedImage:(id)fp8;
- (id)lastLoadedImage;
- (id)photoData;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)setPhotoData:(id)fp8;
- (void)setCurrentPage:(unsigned int)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)pageControlValueChanged:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewWillEndDragging:(id)fp8 withVelocity:(struct CGPoint)fp12 targetContentOffset:(inout struct CGPoint *)fp20;
- (void)scrollViewDidScroll:(id)fp8;
- (void)reloadDataIfNeeded;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (void)updateViewsForCurrentlySelectedImagePostEdit;
- (void)preloadAllUserImages;
- (void)updateCurrentlySelectedImage;
- (void)setupPhotosCollectionView;
- (void)setupPageControl;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithPhotoData:(id)fp8 andPageControl:(id)fp12;

@end

