/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UICollectionViewDataSource-Protocol.h"

@class TNDRPassportLocationInfoView, TNDRPassportLocationPreviewView;

@interface TNDRPassportPopularLocationCell : _ABCreateStringWithAddressDictionary <UICollectionViewDataSource>
{
    id <TNDRPassportPopularLocationCellDelegate> _delegate;
    TNDRPassportLocationPreviewView *_previewView;
    TNDRPassportLocationInfoView *_infoView;
}

- (void)setInfoView:(id)fp8;
- (id)infoView;
- (void)setPreviewView:(id)fp8;
- (id)previewView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)goToLocationButtonTapped:(id)fp8;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (int)numberOfSectionsInCollectionView:(id)fp8;
- (void)applyLayoutAttributes:(id)fp8;
- (void)_setupSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

