/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRDialogViewController.h"

#import "TNDRWhatsNewDialogPagingDelegate-Protocol.h"

@class NSArray, NSString;

@interface TNDRWhatsNewDialogViewController : TNDRDialogViewController <TNDRWhatsNewDialogPagingDelegate>
{
    NSString *_whatsNewID;
    NSArray *_items;
    id _completion;
}

+ (id)viewControllerNavigationKey;
- (void)setCompletion:(id)fp(null);
- (id)completion;
- (void)setItems:(id)fp8;
- (id)items;
- (void)setWhatsNewID:(id)fp8;
- (id)whatsNewID;
- (void).cxx_destruct;
- (void)whatsNewDialogHeader:(id)fp8 isChangingPageWithFraction:(float)fp12;
- (void)actionButtonPressed:(id)fp8;
- (void)cancelButtonPressed:(id)fp8;
- (void)setupHeaderView;
- (void)setupFooterView;
- (void)viewDidLoad;
- (id)whatsNewFooter;
- (id)whatsNewHeader;
- (id)initWithItems:(id)fp8 completion:(id)fp(null);

@end

