/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TNDRPhotoAccessViewControllerDelegate <NSObject>
- (void)photoAccessManagerCancel:(id)fp8;
- (void)photoAccessManager:(id)fp8 selectedPhotoData:(id)fp12;
@end

