/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface TNDRPassportLocationPreviewView : _ABCreateStringWithAddressDictionary
{
    UIImageView *_locationImageView;
    UILabel *_cityLabel;
    UILabel *_countryLabel;
    UIView *_overlayView;
    NSLayoutConstraint *_cityWidthConstraint;
    NSLayoutConstraint *_countryWidthConstraint;
}

- (void)setCountryWidthConstraint:(id)fp8;
- (id)countryWidthConstraint;
- (void)setCityWidthConstraint:(id)fp8;
- (id)cityWidthConstraint;
- (void)setOverlayView:(id)fp8;
- (id)overlayView;
- (void)setCountryLabel:(id)fp8;
- (id)countryLabel;
- (void)setCityLabel:(id)fp8;
- (id)cityLabel;
- (void)setLocationImageView:(id)fp8;
- (id)locationImageView;
- (void).cxx_destruct;
- (void)setupSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

