/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class CAGradientLayer, NSArray, NSString, TNDRAvatarLinearView, TTTAttributedLabel, UIImageView, UIView;

@interface TNDRProfileSwitcherView : _ABCreateStringWithAddressDictionary
{
    NSArray *_usersForProfile;
    NSString *_groupStatus;
    TTTAttributedLabel *_groupStatusLabel;
    TNDRAvatarLinearView *_avatarLinearView;
    UIImageView *_maskImageView;
    CAGradientLayer *_backDrop;
    CAGradientLayer *_statusGradient;
    UIView *_statusGradientWrapperView;
    struct UIEdgeInsets _textInsetsForLabel;
}

+ (BOOL)requiresConstraintBasedLayout;
- (void)setStatusGradientWrapperView:(id)fp8;
- (id)statusGradientWrapperView;
- (void)setStatusGradient:(id)fp8;
- (id)statusGradient;
- (void)setBackDrop:(id)fp8;
- (id)backDrop;
- (void)setMaskImageView:(id)fp8;
- (id)maskImageView;
- (void)setTextInsetsForLabel:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)textInsetsForLabel;
- (void)setAvatarLinearView:(id)fp8;
- (id)avatarLinearView;
- (void)setGroupStatusLabel:(id)fp8;
- (id)groupStatusLabel;
- (id)groupStatus;
- (void)setUsersForProfile:(id)fp8;
- (id)usersForProfile;
- (void).cxx_destruct;
- (id)viewsForAL;
- (id)metricsForAL;
- (void)updateMask;
- (void)layoutSubviews;
- (void)selectAvatarAtIndex:(int)fp8;
- (void)setGroupStatus:(id)fp8;
- (void)setupBackdropView;
- (void)setupGroupLabelConstraints;
- (void)setupAvatarLinearViewConstraints;
- (void)setupConstraints;
- (void)setupGroupStatusLabel;
- (void)setupAvatarLinearView;
- (void)setup;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)initWithUsers:(id)fp8;

@end

