/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class CAEmitterLayer;

@interface TNDRSnowEmitterView : _ABCreateStringWithAddressDictionary
{
    CAEmitterLayer *_snowLayer;
}

+ (Class)layerClass;
- (void)setSnowLayer:(id)fp8;
- (id)snowLayer;
- (void).cxx_destruct;
- (void)stop;
- (void)start;
- (id)makeEmitterCellWithParticle:(id)fp8;
- (id)makeEmitterAtPoint:(struct CGPoint)fp8;
- (void)prepare;
- (id)initWithFrame:(struct CGRect)fp8;

@end

