/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray;

@interface TNDRProductIdsViewModel : _ABCreateStringWithAddressDictionary
{
    NSArray *_productIds;
}

- (void)setProductIds:(id)fp8;
- (id)productIds;
- (void).cxx_destruct;
- (int)quantityForProductID:(id)fp8;
- (id)sortedSuperLikeProductIDs:(id)fp8;
- (id)sortedSubscriptionProductIDs:(id)fp8;
- (id)sortedAllProductIDs:(id)fp8;
- (id)filteredSuperLikeSKUs:(id)fp8;
- (id)filteredSubscriptionSKUs:(id)fp8;
- (id)filteredSKUs:(id)fp8 forValue:(id)fp12;
- (id)locallyCachedProductResults;
- (id)superLikeProductIDs;
- (id)subscriptionProductIDs;
- (id)allProductIDs;
- (id)productIDsOfType:(int)fp8;
- (id)init;

@end

