/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRActionSheetDelegate-Protocol.h"
#import "TNDRInstagramCollectionViewDelegate-Protocol.h"
#import "TNDRInstagramPhotoViewerDelegate-Protocol.h"
#import "TNDRNotificationWindowDelegate-Protocol.h"
#import "TNDRPhotoPageControllerDelegate-Protocol.h"
#import "TNDRProfileEditorChangedData-Protocol.h"
#import "TNDRRecommendationViewControllerRecsSessionTracking-Protocol.h"
#import "TNDRReportDialogViewControllerDelegate-Protocol.h"
#import "TNDRShareRecViewControllerPresenterDelegate-Protocol.h"
#import "TNDRSuperLikeRoadblockDelegate-Protocol.h"
#import "TNDRSuperLikeTutorialDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSArray, NSIndexPath, NSManagedObjectContext, NSString, StyledPageControl, TNDRActionSheet, TNDRBlockMatch, TNDRConnectionsCollectionViewController, TNDRInstagramCollectionViewController, TNDRInstagramPhotoViewerViewController, TNDRInstagramProfileToPhotoViewerAnimationController, TNDRInterestsCollectionViewController, TNDRJobViewModel, TNDRMatchToChatAnimationController, TNDRMyProfileEditViewController, TNDRPhotoPageController, TNDRProfileGamepadView, TNDRReportUserDialogViewController, TNDRSchoolViewModel, TNDRShareRecViewControllerPresenter, TNDRSlackChatViewController, TNDRSuperLikeFirstTimeConfirmationDialogViewController, TNDRSuperLikeRoadblockDialogViewController, TNDRUser, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UINavigationBar, UIScrollView, UITextView, UIView;

@interface TNDRProfilePreviewViewController : _ABCreateStringWithAddressDictionary <TNDRPhotoPageControllerDelegate, TNDRActionSheetDelegate, TNDRNotificationWindowDelegate, UIViewControllerTransitioningDelegate, TNDRReportDialogViewControllerDelegate, TNDRInstagramCollectionViewDelegate, TNDRInstagramPhotoViewerDelegate, TNDRSuperLikeTutorialDelegate, TNDRSuperLikeRoadblockDelegate, TNDRShareRecViewControllerPresenterDelegate, TNDRProfileEditorChangedData, UIScrollViewDelegate, TNDRURLNavigableProtocol, TNDRRecommendationViewControllerRecsSessionTracking>
{
    UIView *_backgroundView;
    NSArray *_photos;
    int _firstImageToShow;
    UIImageView *_superLikeView;
    UILabel *_nameLabel;
    NSString *_firstName;
    UILabel *_badgeDescription;
    UILabel *_distanceAway;
    UITextView *_bioView;
    NSString *_bio;
    UILabel *_contactsOrFriendsLabel;
    int _numberOfFriends;
    UILabel *_interestsLabel;
    int _numberOfInterests;
    BOOL _editingProfile;
    BOOL _needsToUpdateLayoutsForInfoUpdate;
    BOOL _viewHasAppeared;
    BOOL _isDismissing;
    BOOL _isIOSVersion8;
    TNDRActionSheet *_actionSheet;
    id <UIViewControllerTransitioningDelegate> _profileEditorTransitioningDelegate;
    TNDRMatchToChatAnimationController *_matchToChatAnimationController;
    TNDRSlackChatViewController *_chatViewController;
    UIView *_peopleConnectionsView;
    UIView *_instagramPhotosView;
    BOOL _currentUserProfile;
    BOOL _presentedFromChat;
    BOOL _presentingMatch;
    BOOL _presentingGroupProfile;
    BOOL _memberOfCurrentGroup;
    BOOL _likeOnDismiss;
    BOOL _passOnDismiss;
    BOOL _superLikeOnDismiss;
    BOOL _shouldDismissAfterReporting;
    BOOL _precachedUserAvatarImage;
    BOOL _superLikedFromProfileGamepad;
    id <TNDR2ProfilePreviewDelegate> _delegate;
    TNDRUser *_user;
    TNDRReportUserDialogViewController *_reportUserDialogViewController;
    UINavigationBar *_navigationBar;
    UIView *_infoView;
    TNDRPhotoPageController *_photoPageController;
    UIButton *_doneButton;
    UIButton *_editInfoButton;
    TNDRInstagramCollectionViewController *_instagramCollectionViewController;
    StyledPageControl *_photoPageControl;
    UIScrollView *_mainScrollView;
    TNDRProfileGamepadView *_gamepadView;
    UIView *_navigationBarSnapshot;
    NSManagedObjectContext *_context;
    TNDRInterestsCollectionViewController *_interestsCollectionViewController;
    TNDRInstagramPhotoViewerViewController *_instagramPhotoViewerViewController;
    TNDRConnectionsCollectionViewController *_connectionsCollectionViewController;
    TNDRInstagramProfileToPhotoViewerAnimationController *_instagramAnimationController;
    NSIndexPath *_indexPathOfInstagramCellToTransitionFrom;
    unsigned int _profilePreviewAnalyticsFor;
    UIImageView *_celebrityBadgeView;
    TNDRSuperLikeFirstTimeConfirmationDialogViewController *_superLikeConfirmationDialogViewController;
    TNDRSuperLikeRoadblockDialogViewController *_superLikeProfileDialogViewController;
    UIView *_snapshotButtonView;
    UILabel *_jobLabel;
    UILabel *_schoolLabel;
    UIView *_borderBelowJobSchoolDistance;
    TNDRJobViewModel *_jobViewModel;
    TNDRSchoolViewModel *_schoolViewModel;
    TNDRMyProfileEditViewController *_profileEditor;
    UIButton *_preMatchEllipsisButton;
    UIButton *_shareButton;
    UIActivityIndicatorView *_shareLoadingIndicator;
    TNDRShareRecViewControllerPresenter *_shareRecViewControllerPresenter;
    TNDRBlockMatch *_blockMatchManager;
    unsigned int _analyticsExitMethod;
    struct CGPoint _savedContentOffset;
}

+ (id)viewControllerNavigationKey;
- (void)setAnalyticsExitMethod:(unsigned int)fp8;
- (unsigned int)analyticsExitMethod;
- (void)setBlockMatchManager:(id)fp8;
- (void)setShareRecViewControllerPresenter:(id)fp8;
- (id)shareRecViewControllerPresenter;
- (void)setShareLoadingIndicator:(id)fp8;
- (id)shareLoadingIndicator;
- (void)setShareButton:(id)fp8;
- (id)shareButton;
- (void)setPreMatchEllipsisButton:(id)fp8;
- (id)preMatchEllipsisButton;
- (void)setProfileEditor:(id)fp8;
- (id)profileEditor;
- (void)setSchoolViewModel:(id)fp8;
- (id)schoolViewModel;
- (void)setJobViewModel:(id)fp8;
- (id)jobViewModel;
- (void)setBorderBelowJobSchoolDistance:(id)fp8;
- (id)borderBelowJobSchoolDistance;
- (void)setSchoolLabel:(id)fp8;
- (id)schoolLabel;
- (void)setJobLabel:(id)fp8;
- (id)jobLabel;
- (void)setSnapshotButtonView:(id)fp8;
- (id)snapshotButtonView;
- (void)setSuperLikeProfileDialogViewController:(id)fp8;
- (id)superLikeProfileDialogViewController;
- (void)setSuperLikeConfirmationDialogViewController:(id)fp8;
- (id)superLikeConfirmationDialogViewController;
- (void)setCelebrityBadgeView:(id)fp8;
- (id)celebrityBadgeView;
- (void)setProfilePreviewAnalyticsFor:(unsigned int)fp8;
- (unsigned int)profilePreviewAnalyticsFor;
- (void)setIndexPathOfInstagramCellToTransitionFrom:(id)fp8;
- (id)indexPathOfInstagramCellToTransitionFrom;
- (void)setSuperLikedFromProfileGamepad:(BOOL)fp8;
- (BOOL)superLikedFromProfileGamepad;
- (void)setPrecachedUserAvatarImage:(BOOL)fp8;
- (BOOL)hasPrecachedUserAvatarImage;
- (void)setSavedContentOffset:(struct CGPoint)fp8;
- (struct CGPoint)savedContentOffset;
- (void)setInstagramAnimationController:(id)fp8;
- (id)instagramAnimationController;
- (void)setConnectionsCollectionViewController:(id)fp8;
- (id)connectionsCollectionViewController;
- (void)setInstagramPhotoViewerViewController:(id)fp8;
- (id)instagramPhotoViewerViewController;
- (void)setInterestsCollectionViewController:(id)fp8;
- (id)interestsCollectionViewController;
- (void)setShouldDismissAfterReporting:(BOOL)fp8;
- (BOOL)shouldDismissAfterReporting;
- (void)setContext:(id)fp8;
- (id)context;
- (void)setNavigationBarSnapshot:(id)fp8;
- (id)navigationBarSnapshot;
- (void)setSuperLikeOnDismiss:(BOOL)fp8;
- (BOOL)superLikeOnDismiss;
- (void)setPassOnDismiss:(BOOL)fp8;
- (BOOL)passOnDismiss;
- (void)setLikeOnDismiss:(BOOL)fp8;
- (BOOL)likeOnDismiss;
- (void)setMemberOfCurrentGroup:(BOOL)fp8;
- (BOOL)isMemberOfCurrentGroup;
- (void)setPresentingGroupProfile:(BOOL)fp8;
- (BOOL)isPresentingGroupProfile;
- (void)setPresentingMatch:(BOOL)fp8;
- (BOOL)isPresentingMatch;
- (void)setBackgroundView:(id)fp8;
- (id)backgroundView;
- (void)setGamepadView:(id)fp8;
- (id)gamepadView;
- (void)setMainScrollView:(id)fp8;
- (id)mainScrollView;
- (void)setPhotoPageControl:(id)fp8;
- (id)photoPageControl;
- (void)setInstagramCollectionViewController:(id)fp8;
- (id)instagramCollectionViewController;
- (void)setEditInfoButton:(id)fp8;
- (id)editInfoButton;
- (void)setDoneButton:(id)fp8;
- (id)doneButton;
- (void)setPhotoPageController:(id)fp8;
- (id)photoPageController;
- (void)setInfoView:(id)fp8;
- (id)infoView;
- (void)setNavigationBar:(id)fp8;
- (id)navigationBar;
- (void)setReportUserDialogViewController:(id)fp8;
- (id)reportUserDialogViewController;
- (void)setPresentedFromChat:(BOOL)fp8;
- (BOOL)isPresentedFromChat;
- (void)setUser:(id)fp8;
- (id)user;
- (void)setCurrentUserProfile:(BOOL)fp8;
- (BOOL)isCurrentUserProfile;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)hasBeenInActiveForMoreThanWeeks:(int)fp8 withLastAtiveDate:(id)fp12;
- (BOOL)hasBeenInActiveForMoreThanFourWeeksWithLastActiveDate:(id)fp8;
- (void)instagramPhotoViewerRequestsDismissal:(id)fp8;
- (void)instagramPhotoViewerUpdatedSelectedPhoto:(id)fp8;
- (void)instagramCollectionViewControllerRequestsOpenInstagramForUser:(id)fp8;
- (void)instagramCollectionViewControllerDidHideShareConnectionButton:(id)fp8;
- (void)instagramCollectionViewControllerWillAttemptInstagramLoginView:(id)fp8;
- (void)instagramCollectionViewController:(id)fp8 requestsOpenPhotoViewerWithPhotoIndex:(id)fp12 cellCenter:(struct CGPoint)fp16 cellSize:(struct CGSize)fp24 completion:(id)fp(null);
- (void)requestDismissReportDialogReportSucceeded;
- (void)requestDismissReportDialogCancelled;
- (void)superLikeRoadblockDialogViewControllerConfirmAndWait:(id)fp8 completion:(id)fp(null);
- (void)superLikeRoadblockDialogViewControllerRequestsCancel:(id)fp8 completion:(id)fp(null);
- (void)superLikeRoadblockDialogViewControllerRequestsGetPlus:(id)fp8 completion:(id)fp(null);
- (void)superLikeTutorialDidChooseNotNow:(id)fp8;
- (void)superLikeTutorialDidChooseSuperLike:(id)fp8;
- (void)dialogViewControllerRequestsDismissal:(id)fp8 completion:(id)fp(null);
- (void)transitionTo:(id)fp8 optionsDict:(id)fp12 animated:(BOOL)fp16 completion:(id)fp(null);
- (id)interactionControllerForDismissal:(id)fp8;
- (id)animationControllerForDismissedController:(id)fp8;
- (id)animationControllerForPresentedController:(id)fp8 presentingController:(id)fp12 sourceController:(id)fp16;
- (void)presentChatForMatch;
- (void)reportButtonTapped;
- (id)blockMatchManager;
- (void)blockButtonTapped;
- (void)messageButtonTapped;
- (void)actionSheet:(id)fp8 triggeredButtonWithId:(int)fp12;
- (void)setupActionSheet;
- (void)prematchEllipsisTapped:(id)fp8;
- (BOOL)shareRecViewControllerPresenterShouldPresentShareRecSheet:(id)fp8;
- (void)shareButtonTapped:(id)fp8;
- (BOOL)inboundSegueShouldTriggerRecsSessionEnd;
- (void)scrollViewDidScroll:(id)fp8;
- (void)didChangePhotoIndex:(id)fp8;
- (void)didRequestToFinishEditingProfile;
- (void)didFinishServerPhotoDataUpdate;
- (void)didChangePhotoData:(id)fp8;
- (void)didChangeBio:(id)fp8;
- (id)photoDataForUser;
- (id)coreDataCachedLargePhotoDataForMe:(id)fp8;
- (id)largePhotoDataForMeFromMemory:(BOOL)fp8;
- (struct CGPoint)offsetForDismissal;
- (void)passButtonTapped:(id)fp8;
- (void)showSuperLikeRoadblock;
- (void)showSuperLikeFirstTimeUseTutorial;
- (void)notifyDelegateDidTapSuperLikeButton;
- (void)performSuperLikeIfAvailable;
- (void)superLikeButtonTapped:(id)fp8;
- (void)likeButtonTapped:(id)fp8;
- (void)moreButtonTapped:(id)fp8;
- (void)updateAndNotifyDelegateForDismissal;
- (void)animateForDismissal;
- (void)dismiss;
- (void)profilePhotoTapped:(id)fp8;
- (void)doneButtonTapped:(id)fp8;
- (void)editButtonTapped:(id)fp8;
- (void)updateProfilePreviewWithMockCurrentUserUsingExistingInfo:(id)fp(null);
- (void)prepareEditViewController;
- (id)distanceString:(float)fp8;
- (void)layoutPhotoPageControl;
- (void)layoutViews;
- (BOOL)needToWrap;
- (float)heightForText:(id)fp8 fontSize:(unsigned int)fp12 attributes:(id)fp16;
- (float)widthForText:(id)fp8 fontSize:(unsigned int)fp12;
- (struct CGSize)sizeForText:(id)fp8 fontSize:(unsigned int)fp12;
- (void)addTopBorderToView:(id)fp8;
- (void)addPlaceholderBackground:(id)fp8 toView:(id)fp12;
- (void)addNewInterestsView;
- (void)addPeopleConnections;
- (void)precacheUserInstagramAvatar:(id)fp8;
- (void)addInstagramPhotos;
- (void)addBio;
- (void)addSchoolAndJob;
- (void)addBadgeDescription;
- (void)addNameAndLocation;
- (void)addSuperLike;
- (void)updateJobAndSchoolViewModels;
- (void)setupJobAndSchoolViewModels;
- (void)setupPreMatchEllipsisButton;
- (void)setupShareButton;
- (void)updateInfoView;
- (void)setupInfoView;
- (void)setupProfileGamepadView;
- (void)setupEditInfoButton;
- (void)setupDoneButton;
- (void)setupPhotoPageController;
- (void)handleGroupExpired:(id)fp8;
- (void)handleRequestToShowStatusBar:(id)fp8;
- (void)unregisterNotifications;
- (void)handleCurrentUserSynchronized:(id)fp8;
- (void)registerNotifications;
- (void)setupScrollView;
- (void)refreshUserIfNecessary;
- (int)preferredStatusBarStyle;
- (void)updateCurrentUserProfilePhotosIfNecessary;
- (void)prepareToShowProfileForCurrentUser:(id)fp(null);
- (void)prepareToShowGroupProfileForUser:(id)fp8 isMatch:(BOOL)fp12;
- (void)prepareToShowGameProfileForUser:(id)fp8 delegate:(id)fp12;
- (void)prepareToShowMatchProfileForUser:(id)fp8 delegate:(id)fp12;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)prematchEllipsisButton;
- (id)init;

@end

