/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TNDRProfileThumbnailFlowLayout : _ABCreateStringWithAddressDictionary
{
}

- (id)layoutAttributesForElementsInRect:(struct CGRect)fp8;
- (id)layoutAttributesForItemAtIndexPath:(id)fp8;
- (struct CGRect)frameForItemAtIndexPath:(id)fp8;
- (struct CGSize)collectionViewContentSize;

@end

