/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString;

@interface TNDRCurrentUserMergeOperation : _ABCreateStringWithAddressDictionary
{
    BOOL _isExecuting;
    BOOL _isFinished;
    NSString *_userID;
}

- (void)setUserID:(id)fp8;
- (id)userID;
- (void).cxx_destruct;
- (BOOL)isAsynchronous;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (void)setFinished:(BOOL)fp8;
- (void)setExecuting:(BOOL)fp8;
- (void)start;
- (id)initWithUserID:(id)fp8;

@end

