/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, NSDictionary, NSString;

@interface TNDRGroupFriend : _ABCreateStringWithAddressDictionary
{
    BOOL _inSquad;
    BOOL _myself;
    NSString *_name;
    NSString *_userID;
    NSDictionary *_friendJSON;
    NSArray *_photoJSON;
}

- (void)setPhotoJSON:(id)fp8;
- (id)photoJSON;
- (void)setFriendJSON:(id)fp8;
- (id)friendJSON;
- (BOOL)isMyself;
- (void)setInSquad:(BOOL)fp8;
- (BOOL)isInSquad;
- (void)setUserID:(id)fp8;
- (id)userID;
- (void)setName:(id)fp8;
- (id)name;
- (void).cxx_destruct;
- (id)processedPhotos;
- (id)imageURLForSize:(int)fp8;
- (void)setMyself:(BOOL)fp8;
- (id)avatarImageURL;
- (void)parseJSONDataIntoProperties;
- (id)initWithGroupFriendJSON:(id)fp8;
- (id)init;

@end

