/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRAttributedLabel.h"

#import "TNDRChatContentViewProtocol-Protocol.h"

@class CALayer, TNDRChatCell, TNDRMessage, TNDRSlackChatTextView;

@interface TNDRChatTextView : TNDRAttributedLabel <TNDRChatContentViewProtocol>
{
    BOOL _showLikeOption;
    BOOL _hasTail;
    BOOL _emojiOnly;
    BOOL _statusUpdate;
    CALayer *_mask;
    TNDRSlackChatTextView *_textView;
    TNDRChatCell *_parentCell;
    unsigned int _bubbleType;
    TNDRMessage *_message;
}

+ (struct UIEdgeInsets)leftInsetsWithTail;
+ (struct UIEdgeInsets)leftInsets;
+ (struct UIEdgeInsets)rightInsetsWithTail;
+ (struct UIEdgeInsets)rightInsets;
+ (id)labelWithDefaultMessageOptions;
+ (id)defaultStatusFont;
+ (id)defaultEmojiFont;
+ (id)defaultMessageFont;
+ (float)maxWidth;
- (void)setStatusUpdate:(BOOL)fp8;
- (BOOL)isStatusUpdate;
- (void)setEmojiOnly:(BOOL)fp8;
- (BOOL)isEmojiOnly;
- (void)setHasTail:(BOOL)fp8;
- (BOOL)hasTail;
- (id)message;
- (unsigned int)bubbleType;
- (void)setParentCell:(id)fp8;
- (id)parentCell;
- (void)setShowLikeOption:(BOOL)fp8;
- (BOOL)showLikeOption;
- (void)setTextView:(id)fp8;
- (id)textView;
- (id)mask;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)menuDidHide:(id)fp8;
- (BOOL)shouldBecomeFirstResponder;
- (void)attributedLabel:(id)fp8 didSelectLinkWithPhoneNumber:(id)fp12;
- (void)attributedLabel:(id)fp8 didSelectLinkWithAddress:(id)fp12;
- (void)attributedLabel:(id)fp8 didSelectLinkWithURL:(id)fp12;
- (id)urlForTouchPoint:(struct CGPoint)fp8;
- (void)setTextInsets:(struct UIEdgeInsets)fp8;
- (BOOL)canPerformAction:(SEL)fp8 withSender:(id)fp12;
- (void)heartTapped:(id)fp8;
- (id)additionalMenuItems;
- (int)bottomAlignmentAttributeForAvatar;
- (void)setMask:(id)fp8;
- (void)layoutSubviews;
- (void)setBounds:(struct CGRect)fp8;
- (void)configureForOnlyEmjoi;
- (void)setBubbleType:(unsigned int)fp8;
- (void)setMessage:(id)fp8;
- (id)errorTextLinkAttributes;
- (id)pendingTextLinkAttributes;
- (id)darkTextLinkAttributes;
- (id)lightTextLinkAttributes;

@end

