/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_TNDRLocation.h"

#import "TNDRParsable-Protocol.h"

@interface TNDRLocation : _TNDRLocation <TNDRParsable>
{
}

+ (id)safeValueForPlacemarkValue:(id)fp8;
+ (id)createLocationFromLocation:(id)fp8 placemark:(id)fp12 inContext:(id)fp16;
+ (id)locationWithPlacemark:(id)fp8;
- (id)placemark;
- (CDAnonymousStruct8)coordinate;
- (id)shortLocationName;
- (id)niceLocationName;
- (void)setCoordinate:(CDAnonymousStruct8)fp8;
- (id)location;
- (void)updateFromDictionary:(id)fp8;
- (BOOL)isCoordinate:(CDAnonymousStruct8)fp8 equivalentToCoordinate:(CDAnonymousStruct8)fp24 maximumDelta:(double)fp40;
- (BOOL)isEqualToLocation:(id)fp8;

@end

