/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRDialogViewController.h"

@class NSString, UIView;

@interface TNDRAlertDialogViewController : TNDRDialogViewController
{
    id <TNDRActionDialogViewControllerDelegate><TNDRDialogViewControllerDelegate> _delegate;
    UIView *_opaqueBackgroundView;
    NSString *_alertTitle;
    NSString *_alertDetail;
    NSString *_confirmationButtonTitle;
    NSString *_cancelButtonTitle;
    id _confirmationButtonBlock;
    id _cancelButtonBlock;
}

+ (id)viewControllerNavigationKey;
- (void)setCancelButtonBlock:(id)fp(null);
- (id)cancelButtonBlock;
- (void)setConfirmationButtonBlock:(id)fp(null);
- (id)confirmationButtonBlock;
- (void)setCancelButtonTitle:(id)fp8;
- (id)cancelButtonTitle;
- (void)setConfirmationButtonTitle:(id)fp8;
- (id)confirmationButtonTitle;
- (void)setAlertDetail:(id)fp8;
- (id)alertDetail;
- (void)setAlertTitle:(id)fp8;
- (id)alertTitle;
- (void)setOpaqueBackgroundView:(id)fp8;
- (id)opaqueBackgroundView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (float)preferredDialogViewControllerContainerWidth;
- (void)show;
- (void)didTapCancelButton:(id)fp8;
- (void)didTapConfirmationButton:(id)fp8;
- (void)viewDidLayoutSubviews;
- (void)setOpaqueContent:(BOOL)fp8;
- (void)viewDidLoad;
- (id)detailText;
- (id)titleText;
- (id)initWithTitle:(id)fp8 detail:(id)fp12 confirmationButtonTitle:(id)fp16 confirmationButtonBlock:(id)fp(null) cancelButtonTitle:(void)fp20 cancelButtonBlock:(id)fp24;
- (id)initWithTitle:(id)fp8 detail:(id)fp12 confirmationButtonTitle:(id)fp16 cancelButtonTitle:(id)fp20 delegate:(id)fp24;

@end

