/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TNDRMatchRelationships : _ABCreateStringWithAddressDictionary
{
}

+ (id)user;
+ (id)myGroup;
+ (id)messages;
+ (id)matchmaker;
+ (id)lists;
+ (id)group;
+ (id)friendRequest;
+ (id)allMembers;

@end

