/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString, UILabel;

@interface TNDRDescriptionFooterView : _ABCreateStringWithAddressDictionary
{
    NSString *_descriptionText;
    UILabel *_descriptionLabel;
    float _labelHeight;
}

- (void)setLabelHeight:(float)fp8;
- (float)labelHeight;
- (void)setDescriptionLabel:(id)fp8;
- (id)descriptionLabel;
- (id)descriptionText;
- (void).cxx_destruct;
- (float)requiredHeight;
- (void)setDescriptionTextColor:(id)fp8;
- (void)setDescriptionText:(id)fp8;
- (id)initWithReuseIdentifier:(id)fp8;

@end

