/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, UIView;

@interface TNDRFacebookPhotoAlbumListController : _ABCreateStringWithAddressDictionary
{
    NSArray *_albums;
    BOOL _fbAlbumsCompleted;
    BOOL _fbMyTaggedPhotosCompleted;
    UIView *_activityContainerView;
    id _photoPickerDelegate;
    NSArray *_taggedPhotosOfMeArray;
}

- (void)setTaggedPhotosOfMeArray:(id)fp8;
- (id)taggedPhotosOfMeArray;
- (void)setPhotoPickerDelegate:(id)fp8;
- (id)photoPickerDelegate;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)makeFBRequestForPhotosTaggedWithMe;
- (void)hideLoadingView;
- (void)showLoadingView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadAlbums;
- (void)setup;
- (id)initWithStyle:(int)fp8;

@end

