/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSDictionary, NSMutableArray, NSString;

@interface TNDRURLNavigationInfo : _ABCreateStringWithAddressDictionary
{
    int _dismissTimes;
    NSMutableArray *_componentsToNavigate;
    NSString *_query;
    NSDictionary *_optionsDict;
}

- (void)setOptionsDict:(id)fp8;
- (id)optionsDict;
- (void)setQuery:(id)fp8;
- (id)query;
- (void)setComponentsToNavigate:(id)fp8;
- (id)componentsToNavigate;
- (void)setDismissTimes:(int)fp8;
- (int)dismissTimes;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)description;
- (void)setup;
- (id)init;

@end

