/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, UIButton, UIView;

@interface TNDRHomeActionBar : _ABCreateStringWithAddressDictionary
{
    int _actionBarType;
    UIButton *_leftButton;
    UIButton *_rightButton;
    UIView *_topBorder;
    UIView *_bottomBorder;
    UIView *_centerBorder;
    NSArray *_buttonTitles;
    NSArray *_buttonActions;
}

+ (BOOL)requiresConstraintBasedLayout;
- (void)setButtonActions:(id)fp8;
- (id)buttonActions;
- (void)setButtonTitles:(id)fp8;
- (id)buttonTitles;
- (void)setCenterBorder:(id)fp8;
- (id)centerBorder;
- (void)setBottomBorder:(id)fp8;
- (id)bottomBorder;
- (void)setTopBorder:(id)fp8;
- (id)topBorder;
- (void)setRightButton:(id)fp8;
- (id)rightButton;
- (void)setLeftButton:(id)fp8;
- (id)leftButton;
- (int)actionBarType;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)metricsForAutoLayout;
- (id)viewsForAutoLayout;
- (id)defaultActionBarButtonWithTitle:(id)fp8;
- (void)resetViewState;
- (void)handleButtonActionTapped:(id)fp8;
- (void)updateActionBarWithButtonTitles:(id)fp8 titleColors:(id)fp12 andActions:(id)fp16;
- (void)updateActionBarWithButtonTitles:(id)fp8 andActions:(id)fp12;
- (void)setActionBarType:(int)fp8;
- (void)setupButtonActions;
- (void)setupConstraints;
- (void)setupDividers;
- (void)setupButtonsWithColors:(id)fp8;
- (id)initWithButtonTitles:(id)fp8 colors:(id)fp12 andActions:(id)fp16;
- (id)initWithButtonTitles:(id)fp8 andActions:(id)fp12;

@end

