/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRURLNavigableProtocol-Protocol.h"

@class NSURL, TNDRMatch, UIButton, UIImage, UIImageView, UILabel, UIView;

@interface TNDRNewMatchViewController : _ABCreateStringWithAddressDictionary <TNDRURLNavigableProtocol>
{
    UIImageView *_headingView;
    UILabel *_matchDescriptionLabel;
    UILabel *_buttonOrSeparateLabel;
    UIButton *_actionButton;
    UIButton *_continueButton;
    UIView *_backgroundOverlay;
    UIView *_foregroundView;
    int photoIndex;
    BOOL _iPhone6Screen;
    BOOL _iPhone6PlusScreen;
    BOOL _iphone4Screen;
    TNDRMatch *_match;
    UIImage *_blurredImage;
    NSURL *_currentUserImageURL;
    UIImageView *_blurredImageView;
    UIImageView *_superLikeMatchBadge;
    UIView *_userAvatarView;
    UIView *_matchAvatarView;
}

+ (id)viewControllerNavigationKey;
- (void)setMatchAvatarView:(id)fp8;
- (id)matchAvatarView;
- (void)setUserAvatarView:(id)fp8;
- (id)userAvatarView;
- (void)setSuperLikeMatchBadge:(id)fp8;
- (id)superLikeMatchBadge;
- (void)setBlurredImageView:(id)fp8;
- (id)blurredImageView;
- (void)setCurrentUserImageURL:(id)fp8;
- (id)currentUserImageURL;
- (id)blurredImage;
- (id)match;
- (void).cxx_destruct;
- (void)setupVerifiedBadges;
- (void)setupSuperLikeMatchBadge;
- (void)setupBadges;
- (id)ordinalMatchCount;
- (void)tellYourFriends:(id)fp8;
- (void)continuePlaying:(id)fp8;
- (void)showChat:(id)fp8;
- (void)setMatch:(id)fp8;
- (void)updateViewForMatchedUser;
- (id)photoRotationValuesWithMultiplier:(float)fp8;
- (id)photoTranslationValuesWithMultiplier:(float)fp8;
- (id)photoTransformValuesWithMultiplier:(float)fp8;
- (void)animatePhotosIn;
- (void)animateButtonsIn;
- (void)animateOut:(id)fp(null);
- (void)viewDidLayoutSubviews;
- (void)setBlurredImage:(id)fp8;
- (void)performNewMatchAnimation:(id)fp(null);
- (void)animateSuperLikeStarIn:(id)fp(null);
- (void)viewWillDisappear:(BOOL)fp8;
- (void)updateConstraintsForMatchedDescriptionLabel;
- (void)updateConstraintsForAvatarViews;
- (id)avatarViewForMatch;
- (id)imageViewForPhoto;
- (struct CGSize)imageViewSize;
- (id)avatarViewForCurrentUser;
- (void)viewDidLoad;
- (int)preferredStatusBarStyle;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

