/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class TNDRPassportMapSearchViewController, TNDRPassportStackViewController;

@interface TNDRPassportStackContainerView : _ABCreateStringWithAddressDictionary
{
    TNDRPassportStackViewController *_passportStackViewController;
    TNDRPassportMapSearchViewController *_mapViewController;
}

- (void)setMapViewController:(id)fp8;
- (id)mapViewController;
- (void)setPassportStackViewController:(id)fp8;
- (id)passportStackViewController;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;

@end

