/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AFHTTPSessionManager.h"

@class NSMutableSet, NSOperation, NSString, NSURLSessionDataTask;

@interface TNDRHTTPClient : AFHTTPSessionManager
{
    BOOL _mayBeNewUser;
    NSString *_searchLocale;
    NSOperation *_lastMessageOperation;
    NSURLSessionDataTask *_updatesTask;
    NSURLSessionDataTask *_recsTask;
    NSMutableSet *_tasksOnRetryTimer;
}

+ (id)translatedLocaleForCurrentiOSLocale;
- (void)setTasksOnRetryTimer:(id)fp8;
- (id)tasksOnRetryTimer;
- (void)setRecsTask:(id)fp8;
- (id)recsTask;
- (void)setUpdatesTask:(id)fp8;
- (id)updatesTask;
- (void)setLastMessageOperation:(id)fp8;
- (id)lastMessageOperation;
- (void)setMayBeNewUser:(BOOL)fp8;
- (BOOL)mayBeNewUser;
- (void)setSearchLocale:(id)fp8;
- (id)searchLocale;
- (void).cxx_destruct;
- (id)requestRecShareLink:(id)fp8 completion:(id)fp(null);
- (void)userWithUserName:(id)fp8 completion:(id)fp(null);
- (void)deleteUserName:(id)fp8 completion:(id)fp(null);
- (void)changeUserName:(id)fp8 completion:(id)fp(null);
- (void)createUserName:(id)fp8 completion:(id)fp(null);
- (void)cancelAllHTTPOperations;
- (void)cancelRecommendationOperations;
- (void)cancelUpdateOperations;
- (id)formattedTokenFromData:(id)fp8;
- (void)retrieveUserMetadata:(id)fp(null);
- (void)reauthenticate;
- (id)stringFromTNDRHTTPRequestMethod:(int)fp8;
- (id)completionForFailure:(SEL)fp4 parameters:(id)fp(null) method:(void)fp8 path:(id)fp12;
- (id)completionForSuccess:(SEL)fp4;
- (id)performRequestWithPath:(id)fp8 method:(int)fp12 parameters:(id)fp16 sendParamsInBody:(BOOL)fp20 completion:(id)fp(null) enqueue:(void)fp24;
- (id)performRequestWithPath:(id)fp8 method:(int)fp12 parameters:(id)fp16 completion:(id)fp(null);
- (void)retrieveWhatsNew:(id)fp(null);
- (void)declineRecommendationGroup:(id)fp8 recSuperLikedCurrentGroup:(BOOL)fp12 inTrending:(BOOL)fp16 firstPhotoID:(id)fp20 completion:(id)fp(null);
- (void)likeRecommendationGroup:(id)fp8 superLiked:(BOOL)fp12 recSuperLikedCurrentGroup:(BOOL)fp16 userTraveling:(BOOL)fp20 inTrending:(BOOL)fp24 firstPhotoID:(id)fp28 completion:(id)fp(null);
- (void)unmatchGroupMatch:(id)fp8 completion:(id)fp(null);
- (void)unmuteGroupMatch:(id)fp8 completion:(id)fp(null);
- (void)muteGroupMatch:(id)fp8 completion:(id)fp(null);
- (void)unmuteMatch:(id)fp8 completion:(id)fp(null);
- (void)muteMatch:(id)fp8 completion:(id)fp(null);
- (void)leaveGroup:(id)fp8 completion:(id)fp(null);
- (void)extendGroupLifetime:(id)fp8 completion:(id)fp(null);
- (void)retrieveGroup:(id)fp8 completion:(id)fp(null);
- (void)updateGroup:(id)fp8 withStatus:(id)fp12 completion:(id)fp(null);
- (void)createGroupWithIDs:(id)fp8 status:(id)fp12 completion:(id)fp(null);
- (void)retrieveFriendsOnTinderForGroupCreation:(id)fp(null);
- (void)removeCurrentUserSchoolWithCompletion:(id)fp(null);
- (void)removeCurrentUserJobWithCompletion:(id)fp(null);
- (void)updateCurrentUserSchoolSelection:(id)fp8 completion:(id)fp(null);
- (void)updateCurrentUserJobSelection:(id)fp8 completion:(id)fp(null);
- (void)markTutorialAsViewed:(id)fp8 completion:(id)fp(null);
- (void)sendUserFeedback:(id)fp8 starRating:(int)fp12 completion:(id)fp(null);
- (void)requestUserCommonConnections:(id)fp8 completion:(id)fp(null);
- (void)disconnectInstagramAccountFromTinderUseProfile:(id)fp(null);
- (void)linkInstagramToTinderUserProfileWithAccessToken:(id)fp8 completion:(id)fp(null);
- (void)requestSearchLocationCoordinate:(CDAnonymousStruct8)fp8 completion:(id)fp(null);
- (void)requestSearchLocation:(id)fp8 completion:(id)fp(null);
- (void)requestPopularLocationsWithCompletion:(id)fp(null);
- (void)sendSharedPhoneNumbers:(id)fp8 completion:(id)fp(null);
- (void)sendSharedFacebookFriends:(id)fp8 completion:(id)fp(null);
- (void)requestFriendsUsingTinder:(id)fp(null);
- (void)completeForMockData:(id)fp8 completion:(id)fp(null);
- (void)ignoreMatchRequestFromUser:(id)fp8 completion:(id)fp(null);
- (void)acceptMatchRequestFromUser:(id)fp8 completion:(id)fp(null);
- (void)requestMatchWithTinderID:(id)fp8 completion:(id)fp(null);
- (void)requestMatchForFacebookFriendOnTinder:(id)fp8 completion:(id)fp(null);
- (void)requestMatchWithFacebookID:(id)fp8 completion:(id)fp(null);
- (void)deleteMatchesWithIDs:(id)fp8 fromListWithID:(id)fp12 withCompletionHandler:(id)fp(null);
- (void)deleteListWithID:(id)fp8 withCompletionHandler:(id)fp(null);
- (void)addMatchesWithIDs:(id)fp8 toListWithID:(id)fp12 withCompletionHandler:(id)fp(null);
- (void)addMatchWithID:(id)fp8 toListWithID:(id)fp12 withCompletionHandler:(id)fp(null);
- (void)changeListTitle:(id)fp8 forListWithID:(id)fp12 withCompletionHandler:(id)fp(null);
- (void)createListWithTitle:(id)fp8 withCompletionHandler:(id)fp(null);
- (void)loadListsWithCompletionHandler:(id)fp(null);
- (void)updateProfileWithBirthdate:(id)fp8 gender:(int)fp12 completion:(id)fp(null);
- (void)updateProfileWithGender:(int)fp8 completion:(id)fp(null);
- (void)updateProfileWithBirthdate:(id)fp8 completion:(id)fp(null);
- (void)requestValidationForToken:(id)fp8 completion:(id)fp(null);
- (void)requestTokenForPhoneNumber:(id)fp8 completion:(id)fp(null);
- (void)reportMatch:(id)fp8 momentID:(id)fp12 withReason:(id)fp16 andOptionalExplanation:(id)fp20 completion:(id)fp(null);
- (void)reportMatch:(id)fp8 withReason:(id)fp12 andOptionalExplanation:(id)fp16 completion:(id)fp(null);
- (void)reportUser:(id)fp8 withReason:(id)fp12 andOptionalExplanation:(id)fp16 completion:(id)fp(null);
- (void)acceptAccountWarningNotice:(id)fp(null);
- (void)requestUpdatesBeginning:(id)fp8 completion:(id)fp(null);
- (void)followMatch:(id)fp8 shouldFollow:(BOOL)fp12 completion:(id)fp(null);
- (void)blockMatch:(id)fp8 completion:(id)fp(null);
- (void)sendPhotoMessage:(id)fp8 toMatch:(id)fp12 withMessageID:(id)fp16 completion:(id)fp(null);
- (void)fullMessageWithID:(id)fp8 withMessage:(id)fp12 completion:(id)fp(null);
- (void)sendMessageLike:(id)fp8 likeValue:(BOOL)fp12 completion:(id)fp(null);
- (void)sendMessage:(id)fp8 toMatch:(id)fp12 completion:(id)fp(null);
- (void)requestMatch:(id)fp8 completion:(id)fp(null);
- (void)requestUser:(id)fp8 completion:(id)fp(null);
- (void)requestSuperLikeInfo:(id)fp(null);
- (void)rewindGroup:(id)fp8 withLastSwipe:(int)fp12 completionBlock:(id)fp(null);
- (void)rewindPreviousSuperLike:(id)fp8 completion:(id)fp(null);
- (void)declineRecommendation:(id)fp8 recSuperLikedCurrentUser:(BOOL)fp12 inTrending:(BOOL)fp16 firstPhotoID:(id)fp20 completion:(id)fp(null);
- (void)likeRecommendation:(id)fp8 superLiked:(BOOL)fp12 recSuperLikedCurrentUser:(BOOL)fp16 userTraveling:(BOOL)fp20 recTraveling:(BOOL)fp24 inTrending:(BOOL)fp28 firstPhotoID:(id)fp32 completion:(id)fp(null);
- (void)requestRecommendations:(id)fp(null);
- (void)deleteAccount:(id)fp(null);
- (void)sendPushNotificationSettings:(id)fp8 completion:(id)fp(null);
- (void)removePushNotificationToken:(id)fp8 completion:(id)fp(null);
- (void)addPushNotificationToken:(id)fp8 completion:(id)fp(null);
- (void)updateCurrentUserProfile:(id)fp8 completion:(id)fp(null);
- (id)requestCurrentUserProfile:(id)fp(null);
- (void)didFinishTask:(id)fp8;
- (void)requestCurrentUserLocation:(id)fp8 completion:(id)fp(null);
- (id)dataTaskForCurrentUserLocation:(id)fp8 completion:(id)fp(null);
- (void)updateCurrentUserLocation:(id)fp8 completion:(id)fp(null);
- (void)handleAuthenticationFailure:(id)fp8 error:(id)fp12 completionBlock:(id)fp(null);
- (void)setupAuthorizationDependentObjects;
- (void)handleAuthenticationSuccess:(id)fp8 task:(id)fp12 completionBlock:(id)fp(null);
- (void)authenticateWithFacebookToken:(id)fp8 facebookID:(id)fp12 shouldForceRefresh:(BOOL)fp16 completion:(id)fp(null);
- (id)sesh:(id)fp8 id:(id)fp12;
- (BOOL)hasAuthenticationToken;
- (void)clearAuthorizationHeader;
- (void)setAuthorizationHeaderWithToken:(id)fp8;
- (void)setup;
- (id)initWithBaseURL:(id)fp8;
- (id)requestReturnUserHomeWithCompletionBlock:(id)fp(null);
- (id)requestUserTravelToLocation:(id)fp8 completion:(id)fp(null);
- (id)submitPurchaseReceipt:(id)fp8 completion:(id)fp(null);
- (id)retrievePurchasesWithCompletion:(id)fp(null);
- (id)retrieveProductIdsForPurchaseWithCompletion:(id)fp(null);

@end

