/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSLayoutConstraint, UIButton, UIView;

@interface TNDRWhatsNewDialogFooter : _ABCreateStringWithAddressDictionary
{
    UIButton *_actionButton;
    UIButton *_nextButton;
    UIButton *_cancelButton;
    UIView *_rightButtonBackground;
    NSLayoutConstraint *_cancelButtonHalfWidthConstraint;
}

+ (BOOL)requiresConstraintBasedLayout;
- (void)setCancelButtonHalfWidthConstraint:(id)fp8;
- (id)cancelButtonHalfWidthConstraint;
- (void)setRightButtonBackground:(id)fp8;
- (void)setCancelButton:(id)fp8;
- (void)setNextButton:(id)fp8;
- (void)setActionButton:(id)fp8;
- (void).cxx_destruct;
- (void)updateWithProgress:(float)fp8 totalPages:(int)fp12;
- (struct CGSize)intrinsicContentSize;
- (void)setupConstraints;
- (id)cancelButton;
- (id)nextButton;
- (id)actionButton;
- (id)rightButtonBackground;
- (void)setup;
- (id)initWithFrame:(struct CGRect)fp8;

@end

