/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSNumber, NSString, UIImageView, UILongPressGestureRecognizer, UIPanGestureRecognizer;

@interface TNDRSlider : _ABCreateStringWithAddressDictionary <UIGestureRecognizerDelegate>
{
    UIImageView *_sliderInactive;
    UIImageView *_sliderActive;
    BOOL _isSingleHead;
    UIImageView *_lowHead;
    UIImageView *_hiHead;
    float _lowValue;
    float _hiValue;
    UIPanGestureRecognizer *_lowPanGR;
    UIPanGestureRecognizer *_hiPanGR;
    UILongPressGestureRecognizer *_lowPressGR;
    UILongPressGestureRecognizer *_hiPressGR;
    struct CGPoint _panStartPoint;
    struct CGPoint _panCurPoint;
    BOOL shouldShowTooltip;
    BOOL _maxIsRange;
    NSString *_valueLabel;
    NSNumber *_minimumSpan;
    NSNumber *_startValue;
    NSNumber *_endValue;
    NSNumber *_maximumValue;
    NSNumber *_minimumValue;
    id _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setMaxIsRange:(BOOL)fp8;
- (BOOL)maxIsRange;
- (void)setMinimumValue:(id)fp8;
- (id)minimumValue;
- (void)setMaximumValue:(id)fp8;
- (id)maximumValue;
- (id)endValue;
- (id)startValue;
- (void)setMinimumSpan:(id)fp8;
- (id)minimumSpan;
- (void)setValueLabel:(id)fp8;
- (id)valueLabel;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)alignThumb:(id)fp8 toValue:(int)fp12;
- (id)valueOfPositionFor:(id)fp8;
- (float)calculateMinimumSpanPixels;
- (void)handleHeadPan:(id)fp8;
- (void)handlePressPan:(id)fp8;
- (void)registerGestureRecognizers;
- (id)hiValue;
- (id)lowValue;
- (BOOL)isDualHead;
- (void)calculateAllSubFramesAndPositions;
- (void)setEndValue:(id)fp8;
- (void)setStartValue:(id)fp8;
- (void)setup;
- (id)init;

@end

