/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRAsyncOperation.h"

@class TNDRMatch;

@interface TNDRSpotlightUpdateThumbnailOperation : TNDRAsyncOperation
{
    TNDRMatch *_match;
}

- (void)setMatch:(id)fp8;
- (id)match;
- (void).cxx_destruct;
- (void)updateSpotlightThumbnail;
- (BOOL)matchIsValid;
- (void)executeAsyncTask;
- (id)initWithMatch:(id)fp8;

@end

