/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TNDRTinderPlusBlendSelectTableViewControllerDelegate <NSObject>
- (void)tndr_tableViewController:(id)fp8 didSelectBlend:(int)fp12 didFinishSelection:(BOOL)fp16;
@end

