/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@class UIImageView, UIViewController;

@interface TNDRGameToNewMatchAnimationController : _ABCreateStringWithAddressDictionary <UIViewControllerAnimatedTransitioning>
{
    BOOL _reversed;
    UIViewController *_source;
    UIImageView *_blurredView;
    double _presentationDuration;
    double _dismissalDuration;
}

- (void)setBlurredView:(id)fp8;
- (id)blurredView;
- (void)setSource:(id)fp8;
- (id)source;
- (void)setDismissalDuration:(double)fp8;
- (double)dismissalDuration;
- (void)setPresentationDuration:(double)fp8;
- (double)presentationDuration;
- (void)setReversed:(BOOL)fp8;
- (BOOL)isReversed;
- (void).cxx_destruct;
- (void)animateDismissal:(id)fp8;
- (void)animatePresentation:(id)fp8;
- (void)animateTransition:(id)fp8;
- (double)transitionDuration:(id)fp8;
- (id)init;

@end

