/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class CLGeocoder, NSArray, NSMutableDictionary;

@interface TNDRPassportMapSearchLocationViewModel : _ABCreateStringWithAddressDictionary
{
    NSArray *_mapSearchResults;
    CLGeocoder *_geocoder;
    NSMutableDictionary *_cacheMapSearchResults;
}

- (void)setCacheMapSearchResults:(id)fp8;
- (id)cacheMapSearchResults;
- (void)setGeocoder:(id)fp8;
- (id)geocoder;
- (id)mapSearchResults;
- (void).cxx_destruct;
- (void)searchAppleMaps:(id)fp8 completion:(id)fp(null);
- (void)searchAppleMapsWithLocation:(id)fp8 completion:(id)fp(null);
- (id)searchLocallyForCachedResults:(id)fp8;
- (void)performSearch:(id)fp8 remotelyIfNeeded:(BOOL)fp12;
- (void)performSearch:(id)fp8;
- (id)popularLocationsResults;
- (id)init;

@end

