/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIImageView;

@interface TNDRSettingsCell : _ABCreateStringWithAddressDictionary
{
    UIImageView *_backgroundImageView;
}

- (void)setBackgroundImageView:(id)fp8;
- (id)backgroundImageView;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)configureCellForItem:(id)fp8;
- (void)setup;
- (void)layoutSubviews;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

