/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, NSDateFormatter, TNDRPopularLocation;

@interface TNDRPassportPopularLocationViewModel : _ABCreateStringWithAddressDictionary
{
    TNDRPopularLocation *_popularLocation;
    NSArray *_activeUserPhotos;
    NSDateFormatter *_dateFormatter;
}

- (void)setDateFormatter:(id)fp8;
- (id)dateFormatter;
- (void)setActiveUserPhotos:(id)fp8;
- (id)activeUserPhotos;
- (void)setPopularLocation:(id)fp8;
- (id)popularLocation;
- (void).cxx_destruct;
- (id)location;
- (id)goToLocationString;
- (id)avatarURLForIndexPath:(id)fp8;
- (int)numberOfActivePeople;
- (id)activeInLocationString;
- (id)timeString;
- (id)populationString;
- (id)countryName;
- (id)cityName;
- (id)locationImageURL;
- (id)initWithPopularLocation:(id)fp8 dateFormatter:(id)fp12;

@end

