/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_TNDRList.h"

@interface TNDRList : _TNDRList
{
}

+ (BOOL)hasNewMatchesOrMessages:(id)fp8;
+ (void)createWithName:(id)fp8 completion:(id)fp(null);
+ (void)loadListsWitchCompletionHandler:(id)fp(null);
- (void)deleteWithCompletion:(id)fp(null);
- (void)addMatchesToList:(id)fp8 completion:(id)fp(null);
- (void)removeMatchesFromList:(id)fp8 completion:(id)fp(null);
- (void)renameTo:(id)fp8 completion:(id)fp(null);

@end

