/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray;

@interface TNDRRecsMergeOperation : _ABCreateStringWithAddressDictionary
{
    BOOL _isExecuting;
    BOOL _isFinished;
    unsigned int _newRecCount;
    NSArray *_recsJSON;
}

- (void)setRecsJSON:(id)fp8;
- (id)recsJSON;
- (void)setNewRecCount:(unsigned int)fp8;
- (unsigned int)newRecCount;
- (void).cxx_destruct;
- (void)mergeRecommendations;
- (void)start;
- (BOOL)isAsynchronous;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (void)setFinished:(BOOL)fp8;
- (void)setExecuting:(BOOL)fp8;
- (id)initWithRecommendationsToMerge:(id)fp8 currentRecCount:(unsigned int)fp12;

@end

