/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AFHTTPSessionManager.h"

@interface TNDRHTTPFacebookClient : AFHTTPSessionManager
{
}

+ (id)sharedHTTPClient;
- (void)completeWithFailure:(id)fp8 error:(id)fp12 completion:(id)fp(null);
- (void)completeWithSuccess:(id)fp8 responseObject:(id)fp12 completion:(id)fp(null);
- (id)stringByAppendingFacebookAccessToken:(id)fp8;
- (id)pathForFQLQuery:(id)fp8;
- (void)requestCommonAttributesForUser:(id)fp8 completion:(id)fp(null);
- (void)requestCommonConnectionsForUser:(id)fp8 imageWidth:(float)fp12 completion:(id)fp(null);
- (void)requestAlbumCoverForCurrentUserPhotos:(id)fp(null);

@end

