/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRPassportMapViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CLLocationManager, FBKVOController, NSArray, NSDate, NSTimer, TNDRPassportMapSearchLocationViewModel, TNDRPassportMapSearchView, TNDRPassportMapViewController, UIBarButtonItem, UINavigationController, UISearchBar, UISearchDisplayController, UITableView, UITapGestureRecognizer;

@interface TNDRPassportMapSearchViewController : _ABCreateStringWithAddressDictionary <UIGestureRecognizerDelegate, TNDRPassportMapViewDelegate, UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource, UISearchDisplayDelegate>
{
    BOOL _shouldShowPopularLocations;
    id <TNDRPassportMapSearchViewControllerDelegate><TNDRPassportPaywallDelegate> _delegate;
    TNDRPassportMapViewController *_mapViewController;
    TNDRPassportMapSearchView *_containerView;
    UINavigationController *_navigationController;
    UISearchDisplayController *_aSearchDisplayController;
    TNDRPassportMapSearchLocationViewModel *_mapSearchViewModel;
    UITableView *_searchResultsTableView;
    UIBarButtonItem *_backButtonItem;
    UIBarButtonItem *_locateButtonItem;
    UISearchBar *_searchBar;
    CLLocationManager *_locationManager;
    FBKVOController *_kvoController;
    UITapGestureRecognizer *_tapGestureRecognizer;
    NSTimer *_autoCompleteSearchTimer;
    NSArray *_popularLocationsList;
    NSDate *_pinDropStartTime;
    NSDate *_pinDropEndTime;
}

- (void)setPinDropEndTime:(id)fp8;
- (id)pinDropEndTime;
- (void)setPinDropStartTime:(id)fp8;
- (id)pinDropStartTime;
- (void)setPopularLocationsList:(id)fp8;
- (id)popularLocationsList;
- (void)setAutoCompleteSearchTimer:(id)fp8;
- (id)autoCompleteSearchTimer;
- (void)setShouldShowPopularLocations:(BOOL)fp8;
- (BOOL)shouldShowPopularLocations;
- (void)setTapGestureRecognizer:(id)fp8;
- (id)tapGestureRecognizer;
- (void)setKvoController:(id)fp8;
- (id)kvoController;
- (void)setLocationManager:(id)fp8;
- (id)locationManager;
- (void)setSearchBar:(id)fp8;
- (id)searchBar;
- (void)setLocateButtonItem:(id)fp8;
- (id)locateButtonItem;
- (void)setBackButtonItem:(id)fp8;
- (id)backButtonItem;
- (void)setSearchResultsTableView:(id)fp8;
- (id)searchResultsTableView;
- (void)setMapSearchViewModel:(id)fp8;
- (id)mapSearchViewModel;
- (void)setASearchDisplayController:(id)fp8;
- (id)aSearchDisplayController;
- (void)setNavigationController:(id)fp8;
- (id)navigationController;
- (void)setContainerView:(id)fp8;
- (id)containerView;
- (void)setMapViewController:(id)fp8;
- (id)mapViewController;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (void)keyboardWillHide;
- (void)searchDisplayController:(id)fp8 didHideSearchResultsTableView:(id)fp12;
- (void)searchDisplayController:(id)fp8 willHideSearchResultsTableView:(id)fp12;
- (void)searchDisplayController:(id)fp8 willShowSearchResultsTableView:(id)fp12;
- (BOOL)searchDisplayController:(id)fp8 shouldReloadTableForSearchString:(id)fp12;
- (void)searchBar:(id)fp8 textDidChange:(id)fp12;
- (void)searchDisplayControllerDidEndSearch:(id)fp8;
- (void)searchDisplayControllerDidBeginSearch:(id)fp8;
- (void)searchDisplayControllerWillBeginSearch:(id)fp8;
- (void)showPopularLocationsInList;
- (void)searchBarSearchButtonClicked:(id)fp8;
- (void)searchBarCancelButtonClicked:(id)fp8;
- (BOOL)searchBarShouldBeginEditing:(id)fp8;
- (void)didEndMovingToAnnotatedLocation:(id)fp8;
- (void)willStartMovingToAnnotatedLocation;
- (void)showOnlyStatusBar:(BOOL)fp8 animated:(BOOL)fp12;
- (void)locationButtonTapped;
- (void)backButtonTapped;
- (void)mapViewTapped;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (void)setupMapSearchDisplay;
- (void)dealloc;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;

@end

