/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@class FLAnimatedImageView, NSIndexPath, TNDRSlackChatViewController, UIImageView;

@interface TNDRGIFPreviewViewerAnimationController : _ABCreateStringWithAddressDictionary <UIViewControllerAnimatedTransitioning>
{
    BOOL _presenting;
    FLAnimatedImageView *_animatedImageView;
    NSIndexPath *_indexPathOfGIFSelected;
    FLAnimatedImageView *_movingImageView;
    TNDRSlackChatViewController *_chatViewController;
    UIImageView *_leftBubbleWithTailImageView;
    UIImageView *_rightBubbleWithTailImageView;
    float _yOffsetPosition;
    struct CGRect _previewFrame;
}

- (void)setYOffsetPosition:(float)fp8;
- (float)yOffsetPosition;
- (void)setRightBubbleWithTailImageView:(id)fp8;
- (id)rightBubbleWithTailImageView;
- (void)setLeftBubbleWithTailImageView:(id)fp8;
- (id)leftBubbleWithTailImageView;
- (void)setChatViewController:(id)fp8;
- (id)chatViewController;
- (void)setPreviewFrame:(struct CGRect)fp8;
- (struct CGRect)previewFrame;
- (void)setMovingImageView:(id)fp8;
- (id)indexPathOfGIFSelected;
- (void)setAnimatedImageView:(id)fp8;
- (id)animatedImageView;
- (void)setPresenting:(BOOL)fp8;
- (BOOL)isPresenting;
- (void).cxx_destruct;
- (void)extractAndCacheYOffsetFromCollectionView:(id)fp8;
- (void)setupMaskImageViews;
- (id)maskForCell:(id)fp8;
- (void)setIndexPathOfGIFSelected:(id)fp8;
- (id)movingImageView;
- (void)handleDismissal:(id)fp8;
- (void)handlePresentation:(id)fp8;
- (void)animateTransition:(id)fp8;
- (double)transitionDuration:(id)fp8;
- (id)init;

@end

