/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TNDRPaywallNavigableProtocol <NSObject>
- (void)preparePaywallFrom:(unsigned int)fp8 offerTitle:(id)fp12 featureAdvertised:(int)fp16 withCompletion:(id)fp(null);
@end

