/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TNDRSearchFieldDelegate <NSObject>
- (void)tndr_searchFieldSearchButtonClicked:(id)fp8;
- (void)tndr_searchFieldCancelButtonClicked:(id)fp8;
- (void)tndr_searchFieldTextDidEndEditing:(id)fp8;
- (void)tndr_searchFieldTextDidBeginEditing:(id)fp8;
- (void)tndr_searchField:(id)fp8 textDidChange:(id)fp12;
@end

