/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, NSString;

@interface TNDRConsumable : _ABCreateStringWithAddressDictionary
{
    NSString *_productId;
    NSString *_productType;
    NSString *_receiptId;
    NSArray *_features;
}

- (id)features;
- (id)receiptId;
- (id)productType;
- (id)productId;
- (void).cxx_destruct;
- (id)description;
- (id)initWithProductId:(id)fp8 productType:(id)fp12 features:(id)fp16 receiptId:(id)fp20;

@end

