/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRInstagramLoginWebViewControllerDelegate-Protocol.h"
#import "TNDRProfileServiceConnectorViewDelegate-Protocol.h"

@class NSString, TNDRInstagramLoginWebViewController, TNDRProfileServiceConnectorView, UINavigationController;

@interface TNDRInstagramConnectionViewController : _ABCreateStringWithAddressDictionary <TNDRInstagramLoginWebViewControllerDelegate, TNDRProfileServiceConnectorViewDelegate>
{
    TNDRProfileServiceConnectorView *_instagramConnectionView;
    NSString *_instagramName;
    TNDRInstagramLoginWebViewController *_instagramLoginViewController;
    UINavigationController *_navController;
}

- (void)setNavController:(id)fp8;
- (id)navController;
- (void)setInstagramLoginViewController:(id)fp8;
- (id)instagramLoginViewController;
- (void)setInstagramName:(id)fp8;
- (id)instagramName;
- (void)setInstagramConnectionView:(id)fp8;
- (id)instagramConnectionView;
- (void).cxx_destruct;
- (void)requestDisconnectInstagram;
- (void)dismissInstagramLoginView;
- (void)didCancelInstagramLogin;
- (void)didFailLoginWithMessage:(id)fp8;
- (void)didCompleteLoginWithAccessCode:(id)fp8;
- (void)serviceDisconnectRequested:(id)fp8;
- (void)attemptToLoginToInstagram;
- (void)serviceConnectionRequested:(id)fp8;
- (void)updateInstagramConnectionViewStateWithInstagramName:(id)fp8;
- (void)setupWithInstagramName:(id)fp8;
- (id)initWithInstagramName:(id)fp8;

@end

