/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "RMStoreReceiptVerificator-Protocol.h"

@class FBKVOController, NSArray, NSData, NSTimer, NSURLSessionDataTask, TNDRPassportPaywallViewModel, TNDRProductIdsViewModel, TNDRPurchasesViewModel;

@interface TNDRPaywallGatekeeper : _ABCreateStringWithAddressDictionary <RMStoreReceiptVerificator>
{
    BOOL _paywallBeingShownToUser;
    BOOL _verifyingReceipt;
    BOOL _isAttemptingToRestore;
    TNDRPurchasesViewModel *_purchasesViewModel;
    TNDRProductIdsViewModel *_productIdsViewModel;
    FBKVOController *_purchasesKVOController;
    FBKVOController *_productIdsKVOController;
    NSArray *_activePurchases;
    NSData *_receiptToVerify;
    NSData *_receiptVerified;
    NSURLSessionDataTask *_currentReceiptVerificationTask;
    NSTimer *_verificationTimer;
    id _verificationSuccessBlock;
    id _verificationFailureBlock;
    TNDRPassportPaywallViewModel *_paywallViewModel;
}

+ (id)sharedPaywallGatekeeper;
- (void)setPaywallViewModel:(id)fp8;
- (id)paywallViewModel;
- (void)setVerificationFailureBlock:(id)fp(null);
- (id)verificationFailureBlock;
- (void)setVerificationSuccessBlock:(id)fp(null);
- (id)verificationSuccessBlock;
- (void)setVerificationTimer:(id)fp8;
- (id)verificationTimer;
- (void)setCurrentReceiptVerificationTask:(id)fp8;
- (id)currentReceiptVerificationTask;
- (void)setReceiptVerified:(id)fp8;
- (id)receiptVerified;
- (void)setReceiptToVerify:(id)fp8;
- (id)receiptToVerify;
- (void)setActivePurchases:(id)fp8;
- (id)activePurchases;
- (void)setIsAttemptingToRestore:(BOOL)fp8;
- (BOOL)isAttemptingToRestore;
- (void)setProductIdsKVOController:(id)fp8;
- (id)productIdsKVOController;
- (void)setPurchasesKVOController:(id)fp8;
- (id)purchasesKVOController;
- (void)setProductIdsViewModel:(id)fp8;
- (id)productIdsViewModel;
- (void)setPurchasesViewModel:(id)fp8;
- (id)purchasesViewModel;
- (void)setVerifyingReceipt:(BOOL)fp8;
- (BOOL)isVerifyingReceipt;
- (void)setPaywallBeingShownToUser:(BOOL)fp8;
- (BOOL)isPaywallBeingShownToUser;
- (void).cxx_destruct;
- (id)productsArrayForAnalytics;
- (int)quantityForProductID:(id)fp8;
- (void)reloadPurchases:(id)fp8;
- (void)requestSuperLikePaywallViewModel:(id)fp(null);
- (void)requestSubscriptionPaywallViewModel:(id)fp(null);
- (void)requestPaywallViewModel:(id)fp(null);
- (void)requestPaywallViewModelOfType:(int)fp8 withCompletion:(id)fp(null);
- (id)superLikeSuperLikeProductIds;
- (id)subscriptionProductIds;
- (id)allProductIds;
- (id)superLikeALCProductIdentifiers;
- (id)activePurchasesProductIdentifiers;
- (id)productIdentifiers;
- (BOOL)hasReedemedConsumableForTransaction:(id)fp8;
- (BOOL)isTinderPlusActive;
- (void)checkReceiptVerificationTaskStatus:(id)fp8;
- (void)attemptValidatingPurchaseReceipt:(id)fp8 transaction:(id)fp12 success:(id)fp(null) failure:(void)fp16;
- (void)verifyTransaction:(id)fp8 success:(id)fp(null) failure:(void)fp12;
- (void)setupPurchaseViewModel;
- (void)requestPaywallInformation;
- (void)clearPaywallInformation;
- (id)init;

@end

