/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_TNDRGroup.h"

#import "TNDRUserGroupProtocol-Protocol.h"

@interface TNDRGroup : _TNDRGroup <TNDRUserGroupProtocol>
{
    BOOL _profileViewed;
    BOOL _seenOnStack;
}

+ (id)formattedNameForMembers:(id)fp8 owner:(id)fp12 currentUserID:(id)fp16;
+ (void)clearAllCurrentGroupsExcept:(id)fp8 inContext:(id)fp12;
+ (void)clearAllCurrentGroupsInContext:(id)fp8;
+ (id)currentGroupsPredicate;
+ (id)rewindableGroup;
- (void)setSeenOnStack:(BOOL)fp8;
- (BOOL)seenOnStack;
- (void)setProfileViewed:(BOOL)fp8;
- (BOOL)isProfileViewed;
- (void)trackRewindFromPaywall:(BOOL)fp8 isUserTraveling:(BOOL)fp12;
- (void)deleteCurrentMembers;
- (BOOL)isVerified;
- (id)commonName;
- (id)entityID;
- (void)resetForRewind;
- (id)memberUserIDsForAnalytics;
- (id)groupName;
- (id)groupTitle;
- (id)groupMatchDescription;
- (id)membersWithoutPlaceholders;
- (id)membersWithoutOwner;
- (id)membersWithOwnerFirst;
- (void)trackRecsPhotoView;
- (void)trackRecsView;
- (id)mainBadgeColor;
- (id)mainBadgeDescription;
- (id)mainBadgeType;
- (BOOL)isGroupAlmostExpired;
- (double)timeIntervalTilExpiration;
- (id)owner;
- (id)likeCompletionBlockForSuperLike:(SEL)fp4 completion:(BOOL)fp8;
- (BOOL)currentGroupDidSuperLikeGroup;
- (void)setIsCurrentGroupAndClearOthersInContext:(id)fp8;
- (id)dislikeCompletionBlockWithCompletion:(SEL)fp4;
- (int)previousSwipe;
- (void)rewindGroupRecommendation:(id)fp(null);
- (void)rewindSuperLikedRecommendation:(id)fp(null);
- (void)declineRecommendationTrending:(BOOL)fp8 completion:(id)fp(null);
- (void)declineRecommendation:(id)fp(null);
- (void)likeRecommendationTrending:(BOOL)fp8 superLiked:(BOOL)fp12 completion:(id)fp(null);
- (void)likeRecommendationWithSuperLike:(BOOL)fp8 completion:(id)fp(null);
- (BOOL)didSuperLikeCurrentGroup;
- (id)ownerInContext:(id)fp8;
- (BOOL)setUpGroupFromDictionary:(id)fp8;

@end

