/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRDialogHeader-Protocol.h"

@class UILabel, UIView;

@interface TNDRVanNuysDialogHeader : _ABCreateStringWithAddressDictionary <TNDRDialogHeader>
{
    BOOL _calculateContentSize;
    float _preferredContentWidth;
    UIView *_centerImageView;
    UIView *_bannerImageView;
    UIView *_imageContainerView;
    UIView *_contentView;
    UIView *_textBackgroundView;
    float _textContentSpacing;
    UILabel *_titleTextLabel;
    UILabel *_detailTextLabel;
    UIView *_separatorLine;
    struct UIEdgeInsets _contentViewInsets;
}

+ (float)heightForViewWithTitleText:(id)fp8 detailText:(id)fp12 width:(float)fp16;
+ (float)heightForViewWithTitleString:(id)fp8 detailString:(id)fp12 width:(float)fp16;
+ (float)heightForViewWithText:(id)fp8 width:(float)fp12;
+ (struct CGSize)sizeOfHeaderBannerImage;
+ (BOOL)requiresConstraintBasedLayout;
+ (id)paragraphStyleWithTextInsetsWithParagraphStyle:(id)fp8;
+ (id)defaultReportBannerImageView;
+ (id)headerOfWidth:(float)fp8 titleText:(id)fp12 detailText:(id)fp16 textContainerInsets:(struct UIEdgeInsets)fp20 textContentSpacing:(float)fp36 bannerView:(id)fp40 bannerCenterView:(id)fp44 opaque:(BOOL)fp48;
+ (id)headerOfWidth:(float)fp8 titleText:(id)fp12 detailText:(id)fp16 textContainerInsets:(struct UIEdgeInsets)fp20 textContentSpacing:(float)fp36 centerView:(id)fp40 opaque:(BOOL)fp44;
+ (id)headerOfWidth:(float)fp8 titleText:(id)fp12 detailText:(id)fp16 textContainerInsets:(struct UIEdgeInsets)fp20 textContentSpacing:(float)fp36 centerImage:(id)fp40;
+ (id)headerOfWidth:(float)fp8 titleText:(id)fp12 detailText:(id)fp16;
- (void)setCalculateContentSize:(BOOL)fp8;
- (BOOL)calculateContentSize;
- (void)setSeparatorLine:(id)fp8;
- (id)separatorLine;
- (void)setDetailTextLabel:(id)fp8;
- (id)detailTextLabel;
- (void)setTitleTextLabel:(id)fp8;
- (id)titleTextLabel;
- (void)setTextContentSpacing:(float)fp8;
- (float)textContentSpacing;
- (void)setContentViewInsets:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)contentViewInsets;
- (void)setTextBackgroundView:(id)fp8;
- (id)textBackgroundView;
- (void)setContentView:(id)fp8;
- (id)contentView;
- (void)setImageContainerView:(id)fp8;
- (id)imageContainerView;
- (void)setBannerImageView:(id)fp8;
- (id)bannerImageView;
- (void)setCenterImageView:(id)fp8;
- (id)centerImageView;
- (float)preferredContentWidth;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (void)layoutSubviews;
- (float)preferredTextLabelWidth;
- (void)autolayoutSubviews;
- (void)updateConstraints;
- (void)setupSubviews;
- (void)setPreferredContentWidth:(float)fp8;
- (BOOL)hideSeparatorLine;
- (void)setHideSeparatorLine:(BOOL)fp8;
- (void)setDetailText:(id)fp8;
- (void)setTitleText:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8 titleText:(id)fp24 detailText:(id)fp28 textContainerInsets:(struct UIEdgeInsets)fp32 textContentSpacing:(float)fp48 bannerView:(id)fp52 bannerCenterView:(id)fp56 opaque:(BOOL)fp60;

@end

