/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSObject;

@interface TNDRCardCellSuperLikeStarViewTailsLayerDelegate : _ABCreateStringWithAddressDictionary
{
    NSObject *_delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)drawLayer:(id)fp8 inContext:(struct CGContext *)fp12;
- (id)initWithDelegate:(id)fp8;

@end

