/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, NSShadow, NSTimer, UIColor;

@interface TNDRAnimatedEqualizerButton : _ABCreateStringWithAddressDictionary
{
    BOOL _animated;
    UIColor *_barColor;
    NSShadow *_barShadow;
    NSArray *_bars;
    NSTimer *_animationTimer;
}

- (void)setAnimationTimer:(id)fp8;
- (id)animationTimer;
- (void)setBars:(id)fp8;
- (id)bars;
- (id)barShadow;
- (id)barColor;
- (BOOL)isAnimated;
- (void).cxx_destruct;
- (void)animateBars:(BOOL)fp8;
- (void)setAnimated:(BOOL)fp8;
- (void)setBarShadow:(id)fp8;
- (void)setBarColor:(id)fp8;
- (float)randomHeight;
- (id)barPathWithHeight:(float)fp8;
- (void)setupEqualizerBars;
- (void)setHighlighted:(BOOL)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

