/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRViewControllerAnimatedTransitioning-Protocol.h"
#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@class TNDRSuperLikePackagesPaywallVC;

@interface TNDRSuperLikePackagesPaywallAC : _ABCreateStringWithAddressDictionary <UIViewControllerAnimatedTransitioning, TNDRViewControllerAnimatedTransitioning>
{
    BOOL _presenting;
    TNDRSuperLikePackagesPaywallVC *_paywallVC;
}

- (void)setPaywallVC:(id)fp8;
- (id)paywallVC;
- (void)setPresenting:(BOOL)fp8;
- (BOOL)isPresenting;
- (void).cxx_destruct;
- (void)executeDismissalAnimation:(id)fp8;
- (void)executePresentationAnimation:(id)fp8;
- (void)animateTransition:(id)fp8;
- (double)transitionDuration:(id)fp8;

@end

