/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRExpiredChatViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class TNDRExpiredChatHeaderView, TNDRExpiredChatView, TNDRExpiredChatViewModel, TNDRMatch, TNDRProfilePreviewViewController, UIGestureRecognizer;

@interface TNDRExpiredChatViewController : _ABCreateStringWithAddressDictionary <TNDRExpiredChatViewDelegate, UIGestureRecognizerDelegate>
{
    id <TNDRExpiredChatViewControllerDelegate><TNDR2ProfilePreviewDelegate> _delegate;
    TNDRMatch *_match;
    TNDRExpiredChatViewModel *_viewModel;
    TNDRExpiredChatHeaderView *_headerView;
    TNDRExpiredChatView *_expiredChatView;
    TNDRProfilePreviewViewController *_profilePreviewVC;
    UIGestureRecognizer *_tapGestureRecognizer;
}

- (void)setTapGestureRecognizer:(id)fp8;
- (id)tapGestureRecognizer;
- (void)setProfilePreviewVC:(id)fp8;
- (id)profilePreviewVC;
- (void)setExpiredChatView:(id)fp8;
- (id)expiredChatView;
- (void)setHeaderView:(id)fp8;
- (id)headerView;
- (void)setViewModel:(id)fp8;
- (id)viewModel;
- (void)setMatch:(id)fp8;
- (id)match;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)isProfilePreviewVCSetupForUser:(id)fp8;
- (void)setupMatchProfilePreviewForUser:(id)fp8;
- (void)showMatchProfileForUser:(id)fp8;
- (void)handleTap:(id)fp8;
- (void)requestToLikeWithSuperLike:(BOOL)fp8 user:(id)fp12;
- (void)requestTransitionToMatchProfileForUser:(id)fp8;
- (int)swipeValueForRow:(int)fp8;
- (id)imageURLForRow:(int)fp8;
- (id)nameForRow:(int)fp8;
- (id)userForRow:(int)fp8;
- (int)numberOfRows;
- (void)didLikeUser:(id)fp8;
- (float)fullHeight;
- (float)minimizedHeight;
- (void)setupExpiredChatView;
- (void)setupConstraints;
- (void)setupTapGR;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithMatch:(id)fp8;

@end

