/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRPassportUnderlinedView.h"

@class UILabel, UIView;

@interface TNDRPassportLocationStatsView : TNDRPassportUnderlinedView
{
    UILabel *_populationLabel;
    UILabel *_timeLabel;
    UIView *_labelContainer;
    UILabel *_populationDescriptionLabel;
    UILabel *_timeDescriptionLabel;
}

- (void)setTimeDescriptionLabel:(id)fp8;
- (id)timeDescriptionLabel;
- (void)setPopulationDescriptionLabel:(id)fp8;
- (id)populationDescriptionLabel;
- (void)setLabelContainer:(id)fp8;
- (id)labelContainer;
- (void)setTimeLabel:(id)fp8;
- (id)timeLabel;
- (void)setPopulationLabel:(id)fp8;
- (id)populationLabel;
- (void).cxx_destruct;
- (void)setupLayoutConstraints;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setupSubviews;

@end

