/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRDialogViewController.h"

#import "TNDRAccountWarningDialog-Protocol.h"

@class NSAttributedString, TNDRAccountWarningsViewModel;

@interface TNDRAccountWarningDialogViewController : TNDRDialogViewController <TNDRAccountWarningDialog>
{
    BOOL _recalculateWarningsSummary;
    BOOL _sendAnalyticsForThisAppSession;
    int _warningType;
    NSAttributedString *_titleText;
    TNDRAccountWarningsViewModel *_warningViewModel;
}

+ (id)viewControllerNavigationKey;
- (void)setSendAnalyticsForThisAppSession:(BOOL)fp8;
- (BOOL)didSendAnalyticsForThisAppSession;
- (void)setRecalculateWarningsSummary:(BOOL)fp8;
- (BOOL)recalculateWarningsSummary;
- (void)setWarningViewModel:(id)fp8;
- (id)warningViewModel;
- (void)setTitleText:(id)fp8;
- (int)warningType;
- (void).cxx_destruct;
- (id)confirmationButton;
- (id)agreementButton;
- (id)warningsSummary;
- (id)confirmation;
- (id)agreement;
- (id)detailText;
- (id)titleText;
- (void)setWarningType:(int)fp8;
- (void)handleTapInAgreementButton;
- (void)handleTapInAgreementCheckbox;
- (void)setupAgreementButtons;
- (void)setupViews;
- (unsigned int)dialogPriority;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithAccountWarningType:(int)fp8;

@end

