/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRDialogViewController.h"

@class NSAttributedString, TNDRUser, TTTAttributedLabel;

@interface TNDRUserReportedDialogViewController : TNDRDialogViewController
{
    TNDRUser *_user;
    NSAttributedString *_titleText;
    NSAttributedString *_detailText;
    TTTAttributedLabel *_titleTextLabel;
}

- (id)titleTextLabel;
- (void)setDetailText:(id)fp8;
- (id)detailText;
- (void)setTitleText:(id)fp8;
- (id)titleText;
- (void)setUser:(id)fp8;
- (id)user;
- (void).cxx_destruct;
- (void)handleConfirmationButtonTap;
- (id)confirmationButton;
- (id)reportIcon;
- (void)setupControls;
- (void)setupViews;
- (void)setupTitleAndDetail;
- (void)viewDidLoad;

@end

