/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIActivityIndicatorView, UILabel;

@interface TNDRUpdatingMatchesView : _ABCreateStringWithAddressDictionary
{
    UILabel *_label;
    UIActivityIndicatorView *_spinner;
}

- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setLabel:(id)fp8;
- (id)label;
- (void).cxx_destruct;
- (void)adjustUpdatingMatches;
- (void)setup;
- (id)initWithFrame:(struct CGRect)fp8;

@end

