/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSDictionary;

@interface TNDRSquadMergeOperation : _ABCreateStringWithAddressDictionary
{
    BOOL _isExecuting;
    BOOL _isFinished;
    BOOL _addedToGroup;
    int _squadOperationType;
    NSDictionary *_squadJSON;
}

- (void)setSquadJSON:(id)fp8;
- (id)squadJSON;
- (void)setSquadOperationType:(int)fp8;
- (int)squadOperationType;
- (void)setAddedToGroup:(BOOL)fp8;
- (BOOL)hasBeenAddedToGroup;
- (void).cxx_destruct;
- (void)mergeSquadInformation;
- (void)start;
- (BOOL)isAsynchronous;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (void)setFinished:(BOOL)fp8;
- (void)setExecuting:(BOOL)fp8;
- (id)initWithSquadJSONToMerge:(id)fp8;

@end

