/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UITableViewDataSource-Protocol.h"

@class NSArray, NSMutableSet, TNDRTableViewSeparatorCell;

@interface TNDRGroupCreateVM : _ABCreateStringWithAddressDictionary <UITableViewDataSource>
{
    BOOL _currentlySearching;
    BOOL _didSelectFirstFriend;
    id <TNDRGroupCreateModelDelegate> _delegate;
    NSMutableSet *_selectedFriends;
    NSArray *_friendsAvailable;
    NSArray *_friendsInSquads;
    NSArray *_parsedFriendsAvailable;
    NSArray *_parsedFriendsInSquads;
    TNDRTableViewSeparatorCell *_inviteCell;
}

- (void)setInviteCell:(id)fp8;
- (void)setDidSelectFirstFriend:(BOOL)fp8;
- (BOOL)didSelectFirstFriend;
- (void)setParsedFriendsInSquads:(id)fp8;
- (id)parsedFriendsInSquads;
- (void)setParsedFriendsAvailable:(id)fp8;
- (id)parsedFriendsAvailable;
- (void)setFriendsInSquads:(id)fp8;
- (id)friendsInSquads;
- (void)setFriendsAvailable:(id)fp8;
- (id)friendsAvailable;
- (void)setCurrentlySearching:(BOOL)fp8;
- (BOOL)isCurrentlySearching;
- (void)setSelectedFriends:(id)fp8;
- (id)selectedFriends;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (int)friendSectionTypeForSection:(int)fp8;
- (id)inviteCell;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)currentGroupStatus;
- (BOOL)hasNoFriends;
- (id)memberIDsForGroupCreation;
- (void)performSearchWithText:(id)fp8;
- (void)deselectFriend:(id)fp8;
- (BOOL)isFriendSelectedAtIndexPath:(id)fp8;
- (BOOL)selectFriendAtIndexPath:(id)fp8;
- (BOOL)canSelectMoreFriends;
- (id)friendObjectForMyself;
- (id)friendAtIndexPath:(id)fp8;
- (void)parseJSONDataIntoFriends:(id)fp8;
- (void)refreshServerFriendData;
- (void)setup;
- (id)init;

@end

