/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDR2ProfilePreviewDelegate-Protocol.h"
#import "TNDRReportDialogViewControllerDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, TNDRGroup, TNDRProfilePreviewViewController, TNDRProfileSwitcherView, TNDRReportUserDialogViewController, UIButton, UIScrollView;

@interface TNDRGroupProfileViewController : _ABCreateStringWithAddressDictionary <TNDR2ProfilePreviewDelegate, UIScrollViewDelegate, UIViewControllerTransitioningDelegate, TNDRReportDialogViewControllerDelegate, TNDRURLNavigableProtocol>
{
    BOOL _currentGroupProfile;
    BOOL _matchProfile;
    BOOL _presentedFromChat;
    BOOL _myGroup;
    BOOL _didTransitionSwitcher;
    TNDRGroup *_group;
    NSArray *_members;
    TNDRProfilePreviewViewController *_profileVCForTransition;
    TNDRProfileSwitcherView *_profileSwitcherView;
    NSMutableArray *_profileVCs;
    UIScrollView *_mainScrollView;
    UIButton *_doneButton;
    int _lastSelectedIndex;
    NSString *_groupID;
    TNDRReportUserDialogViewController *_reportUserDialogViewController;
}

+ (id)viewControllerNavigationKey;
- (void)setReportUserDialogViewController:(id)fp8;
- (id)reportUserDialogViewController;
- (void)setGroupID:(id)fp8;
- (id)groupID;
- (void)setDidTransitionSwitcher:(BOOL)fp8;
- (BOOL)didTransitionSwitcher;
- (void)setLastSelectedIndex:(int)fp8;
- (int)lastSelectedIndex;
- (void)setDoneButton:(id)fp8;
- (id)doneButton;
- (void)setMainScrollView:(id)fp8;
- (id)mainScrollView;
- (void)setProfileVCs:(id)fp8;
- (id)profileVCs;
- (void)setProfileSwitcherView:(id)fp8;
- (id)profileSwitcherView;
- (void)setProfileVCForTransition:(id)fp8;
- (id)profileVCForTransition;
- (void)setMyGroup:(BOOL)fp8;
- (BOOL)isMyGroup;
- (void)setPresentedFromChat:(BOOL)fp8;
- (BOOL)isPresentedFromChat;
- (void)setMatchProfile:(BOOL)fp8;
- (BOOL)isMatchProfile;
- (void)setMembers:(id)fp8;
- (id)members;
- (void)setGroup:(id)fp8;
- (id)group;
- (void)setCurrentGroupProfile:(BOOL)fp8;
- (BOOL)isCurrentGroupProfile;
- (void).cxx_destruct;
- (id)animationControllerForDismissedController:(id)fp8;
- (id)animationControllerForPresentedController:(id)fp8 presentingController:(id)fp12 sourceController:(id)fp16;
- (void)transitionTo:(id)fp8 optionsDict:(id)fp12 animated:(BOOL)fp16 completion:(id)fp(null);
- (id)containedViewControllers;
- (void)requestDismissReportDialogCancelled;
- (void)requestDismissReportDialogReportSucceeded;
- (void)didTapReportButtonForUser:(id)fp8;
- (void)didTapProfileDoneButton;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (void)animateDoneButtonVisible:(BOOL)fp8;
- (void)restoreProfileVCPostTransition;
- (void)prepareForProfileTransition;
- (void)handleGroupDidExpire:(id)fp8;
- (void)handleAvatarTapped:(id)fp8;
- (void)registerNotifications;
- (void)getGroupStatus;
- (void)doneButtonTapped:(id)fp8;
- (void)resetInternalViewPositions;
- (struct CATransform3D)transformProfileSwitcherDown;
- (void)setUpOtherProfileVCs;
- (void)setupProfileSwitcher;
- (void)setupMainScrollView;
- (void)setUpFirstProfileVC;
- (void)setupDoneButton;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)setupMockGroupForProfile;
- (id)initWithMembers:(id)fp8 groupID:(id)fp12;
- (id)initWithGroup:(id)fp8;

@end

