/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class CALayer, PLScrollingLabel, TNDRPassportPaywallViewModel, UILabel;

@interface TNDRSubscriptionPriceSavingsDotView : _ABCreateStringWithAddressDictionary
{
    BOOL _savingsAgainstTopMultiplier;
    TNDRPassportPaywallViewModel *_paywallViewModel;
    PLScrollingLabel *_saveLabel;
    UILabel *_savingsLabel;
    CALayer *_backgroundLayer;
    CALayer *_foregroundLayer;
}

+ (struct CGSize)defaultSize;
- (void)setSavingsAgainstTopMultiplier:(BOOL)fp8;
- (BOOL)isSavingsAgainstTopMultiplier;
- (void)setForegroundLayer:(id)fp8;
- (id)foregroundLayer;
- (void)setBackgroundLayer:(id)fp8;
- (id)backgroundLayer;
- (void)setSavingsLabel:(id)fp8;
- (id)savingsLabel;
- (void)setSaveLabel:(id)fp8;
- (id)saveLabel;
- (void)setPaywallViewModel:(id)fp8;
- (id)paywallViewModel;
- (void).cxx_destruct;
- (float)fontPointSizeForPercent;
- (float)fontPointSizeForSave;
- (struct CGRect)frameForSaveLabel;
- (void)setupForegroundLayer;
- (void)setupBackgroundLayer;
- (void)updateSavingsStringForNewPaywall:(id)fp8 forTopMultiplierProduct:(BOOL)fp12;
- (void)setupWithPaywallModel:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8 paywallModel:(id)fp24 savingsAgainstTopPrice:(BOOL)fp28;

@end

