/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSString, NSURLSessionDataTask, UICollectionView, UILabel;

@interface TNDRGIFStripDataSource : _ABCreateStringWithAddressDictionary <UICollectionViewDelegate, UICollectionViewDataSource>
{
    NSString *_query;
    UICollectionView *_collectionView;
    id <TNDRGIFStripDataSourceDelegate> _delegate;
    NSURLSessionDataTask *_previousGIFRequest;
    NSArray *_GIFs;
    NSArray *_trendingGIFs;
    unsigned int _pageNumber;
    UILabel *_noResultsLabel;
}

- (void)setNoResultsLabel:(id)fp8;
- (void)setPageNumber:(unsigned int)fp8;
- (unsigned int)pageNumber;
- (void)setTrendingGIFs:(id)fp8;
- (id)trendingGIFs;
- (void)setGIFs:(id)fp8;
- (id)GIFs;
- (void)setPreviousGIFRequest:(id)fp8;
- (id)previousGIFRequest;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)collectionView;
- (id)query;
- (void).cxx_destruct;
- (void)collectionView:(id)fp8 didSelectItemAtIndexPath:(id)fp12;
- (struct CGSize)collectionView:(id)fp8 layout:(id)fp12 sizeForItemAtIndexPath:(id)fp16;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (void)showErrorLabel;
- (void)showNoResultsLabel;
- (void)showMessageGeneric;
- (id)noResultsLabel;
- (void)setQuery:(id)fp8;
- (BOOL)isTextBlank;
- (id)ratingForCurrentUser;
- (void)loadTrendingGIFsForTryNumber:(unsigned int)fp8;
- (id)initWithCollectionView:(id)fp8;

@end

