/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SLKTextView.h"

@class UIResponder;

@interface TNDRSlackChatTextView : SLKTextView
{
    UIResponder *_overrideNextResponder;
}

- (void)setOverrideNextResponder:(id)fp8;
- (id)overrideNextResponder;
- (void).cxx_destruct;
- (BOOL)resignFirstResponder;
- (BOOL)canPerformAction:(SEL)fp8 withSender:(id)fp12;
- (id)nextResponder;

@end

