/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRURLNavigableProtocol-Protocol.h"

@class CLPlacemark, MBProgressHUD, MKMapView, NSDictionary, TNDRExternalLinkManager, UINavigationBar, UIToolbar, UIViewController<TNDRMapPreviewViewControllerDelegate>;

@interface TNDRMapPreviewViewController : _ABCreateStringWithAddressDictionary <TNDRURLNavigableProtocol>
{
    BOOL _hasAppeared;
    BOOL _didShowPlacemark;
    UIViewController<TNDRMapPreviewViewControllerDelegate> *_delegate;
    MKMapView *_mapView;
    NSDictionary *_addressComponents;
    UINavigationBar *_navbar;
    UIToolbar *_toolbar;
    CLPlacemark *_geocodedPlacemark;
    TNDRExternalLinkManager *_linkManager;
    MBProgressHUD *_errorHUD;
    CDAnonymousStruct2 _boundingRegion;
}

+ (id)viewControllerNavigationKey;
- (void)setErrorHUD:(id)fp8;
- (id)errorHUD;
- (void)setLinkManager:(id)fp8;
- (id)linkManager;
- (void)setGeocodedPlacemark:(id)fp8;
- (id)geocodedPlacemark;
- (void)setDidShowPlacemark:(BOOL)fp8;
- (BOOL)didShowPlacemark;
- (void)setHasAppeared:(BOOL)fp8;
- (BOOL)hasAppeared;
- (void)setToolbar:(id)fp8;
- (id)toolbar;
- (void)setNavbar:(id)fp8;
- (id)navbar;
- (void)setBoundingRegion:(CDAnonymousStruct2)fp8;
- (CDAnonymousStruct2)boundingRegion;
- (void)setAddressComponents:(id)fp8;
- (id)addressComponents;
- (void)setMapView:(id)fp8;
- (id)mapView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (id)previewActionItems;
- (void)geoCodeAddressComponents;
- (void)hideError;
- (void)showError;
- (void)addPlacemarkToMap;
- (void)showNavBarForPop;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)handleNavigationRequested;
- (void)handleDoneButtonTapped:(id)fp8;
- (void)setupErrorView;
- (void)setupToolbar;
- (void)setupNavbar;
- (void)setupMapView;
- (void)didReceiveMemoryWarning;
- (id)initWithAddressComponents:(id)fp8;

@end

