/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIImageView;

@interface TNDRButtonAnimateView : _ABCreateStringWithAddressDictionary
{
    BOOL _crossModeEnabled;
    UIImageView *_mainImageView;
    UIImageView *_secondaryImageView;
}

- (BOOL)crossModeEnabled;
- (void)setSecondaryImageView:(id)fp8;
- (id)secondaryImageView;
- (void)setMainImageView:(id)fp8;
- (id)mainImageView;
- (void).cxx_destruct;
- (void)setCrossModeEnabled:(BOOL)fp8;
- (void)animateAppearanceOfView:(id)fp8 whileHidingView:(id)fp12;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

