/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString, UIImage, UIImageView, UILabel;

@interface TNDRAdFooter : _ABCreateStringWithAddressDictionary
{
    NSString *_titleText;
    NSString *_subtitleText;
    UIImage *_image;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIImageView *_imageView;
}

- (void)setImageView:(id)fp8;
- (id)imageView;
- (void)setSubtitleLabel:(id)fp8;
- (id)subtitleLabel;
- (void)setTitleLabel:(id)fp8;
- (id)titleLabel;
- (id)image;
- (id)subtitleText;
- (id)titleText;
- (void).cxx_destruct;
- (void)handleDraggedRequestEnableTouches:(id)fp8;
- (void)handleDraggedRequestCancelTouches:(id)fp8;
- (void)registerNotifications;
- (void)setImage:(id)fp8;
- (void)setSubtitleText:(id)fp8;
- (void)setTitleText:(id)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)layoutSubviews;
- (void)setup;
- (id)initWithFrame:(struct CGRect)fp8;

@end

