/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSDictionary, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, NSTimer;

@interface TNDRAppBoyTracker : _ABCreateStringWithAddressDictionary
{
    BOOL _didUnarchive;
    NSMutableDictionary *_userCustomAttributes;
    NSDictionary *_userCustomAttributeChangeOptions;
    NSString *_userId;
    NSTimer *_timer;
    NSObject<OS_dispatch_queue> *_serialQueue;
    unsigned int _taskId;
}

+ (id)appBoyArchiveStorePath;
+ (id)userCustomAttributeChangeOptions;
+ (id)sharedAppBoyTracker;
- (void)setDidUnarchive:(BOOL)fp8;
- (BOOL)didUnarchive;
- (void)setTaskId:(unsigned int)fp8;
- (unsigned int)taskId;
- (void)setSerialQueue:(id)fp8;
- (id)serialQueue;
- (void)setTimer:(id)fp8;
- (id)timer;
- (id)userId;
- (void)setUserCustomAttributeChangeOptions:(id)fp8;
- (id)userCustomAttributeChangeOptions;
- (void)setUserCustomAttributes:(id)fp8;
- (id)userCustomAttributes;
- (void).cxx_destruct;
- (void)applicationWillTerminate:(id)fp8;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationWillEnterForeground:(id)fp8;
- (void)applicationDidBecomeActive:(id)fp8;
- (void)handleCurrentUserWillLogout:(id)fp8;
- (void)logPurchase:(id)fp8 currency:(id)fp12 price:(id)fp16;
- (void)userSentChatMessage:(id)fp8;
- (void)userOpenedChat:(id)fp8;
- (void)userViewedMatchesList;
- (void)userGotANewMatch:(id)fp8 superLike:(BOOL)fp12;
- (void)userShownOutOfLikesBouncer;
- (void)userSuperLikeExceeded:(int)fp8;
- (void)groupSuperLikeSucceededOnGroup:(id)fp8;
- (void)userSuperLikeSucceededOn:(id)fp8;
- (void)groupSuperLikeAttemptedOnGroup:(id)fp8;
- (void)userSuperLikeAttemptedOn:(id)fp8;
- (void)userSwipedRightOnSuperLikeGroup:(id)fp8;
- (void)userSwipedRightOnSuperLikeRec:(id)fp8;
- (void)userSwipedRightOnBrandedCard:(id)fp8;
- (void)userClickedOnVideoAd:(id)fp8;
- (void)setAccountDeleteDate:(id)fp8;
- (void)setAccountCreationDate:(id)fp8;
- (void)setSeekingDistance:(float)fp8;
- (void)setSeekingMaxAge:(int)fp8;
- (void)setSeekingMinAge:(int)fp8;
- (void)setSeekingGender:(int)fp8;
- (void)userRemovedInstagram;
- (void)userAddedInstagram:(id)fp8;
- (void)setInstagram:(id)fp8;
- (void)userRemovedWorkInfo;
- (void)userAddedWorkInfo;
- (void)userRemovedEducationInfo;
- (void)userAddedEducationInfo;
- (void)userChangedBio:(id)fp8;
- (void)setGender:(int)fp8;
- (void)setHasWorkInfo:(BOOL)fp8;
- (void)setHasEducationInfo:(BOOL)fp8;
- (void)setProfileEnabledGroups:(BOOL)fp8;
- (void)setGroupState:(int)fp8;
- (void)userCreatedAGroup;
- (void)userJoinedAGroup;
- (void)setCanCreateGroup:(BOOL)fp8;
- (void)setBio:(id)fp8;
- (void)userBecameTinderPlusSubscriber;
- (void)setIsTinderPlusSubscriber:(BOOL)fp8;
- (void)unreadMessageCountChanged:(int)fp8;
- (void)setUnreadMessageCount:(int)fp8;
- (void)userRemovedProfilePhoto;
- (void)userAddedProfilePhoto;
- (void)setProfilePhotoCount:(int)fp8;
- (void)matchCountChanged:(int)fp8;
- (void)setMatchCount:(int)fp8;
- (void)sendAppBoyCustomAttributesImmediately:(BOOL)fp8;
- (void)sendAppBoyCustomAttributesAsNeeded;
- (id)dateAfterTimeIntervalForAttribute:(id)fp8;
- (BOOL)trackOnChangedValueForAttribute:(id)fp8;
- (void)setAppBoyCustomAttribute:(id)fp8 withValue:(id)fp12 immediately:(BOOL)fp16;
- (void)setAppBoyCustomAttribute:(id)fp8 withValue:(id)fp12;
- (void)setAppBoyCustomAttribute:(id)fp8 withBOOLValue:(BOOL)fp12 immediately:(BOOL)fp16;
- (void)setAppBoyCustomAttribute:(id)fp8 withBOOLValue:(BOOL)fp12;
- (void)setAppBoyCustomAttribute:(id)fp8 withIntegerValue:(int)fp12 immediately:(BOOL)fp16;
- (void)setAppBoyCustomAttribute:(id)fp8 withIntegerValue:(int)fp12;
- (void)setAppBoyCustomAttribute:(id)fp8 withDoubleValue:(double)fp12 immediately:(BOOL)fp20;
- (void)setAppBoyCustomAttribute:(id)fp8 withDoubleValue:(double)fp12;
- (void)collectUserDataFromCurrentUser;
- (void)setUserId:(id)fp8;
- (void)changeUser:(id)fp8 creationDate:(id)fp12 facebookData:(id)fp16;
- (void)deleteArchive;
- (id)readAttributesFromDiskAtPath:(id)fp8;
- (void)unarchive;
- (void)writeAttributesToDisk:(id)fp8 path:(id)fp12;
- (void)archiveFromSerialQueue;
- (void)archive;
- (id)appboyEndPointDelegate;
- (BOOL)isTrackingEnabled;
- (void)dealloc;
- (void)setup;
- (id)init;

@end

