/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRThumbnailViewModel.h"

@class NSArray, NSString;

@interface TNDRInstagramViewModel : TNDRThumbnailViewModel
{
    NSString *_userId;
    int _totalInstagramPostNum;
    NSString *_userName;
    NSString *_userAvatarImage;
    NSArray *_instagramPhotos;
}

- (void)setInstagramPhotos:(id)fp8;
- (id)instagramPhotos;
- (id)userAvatarImage;
- (id)userName;
- (int)totalInstagramPostNum;
- (id)userId;
- (void).cxx_destruct;
- (int)availableInstagramPhotos;
- (void)parseInstagramPhotosJSON:(id)fp8;
- (void)parseInstagramJSON:(id)fp8;
- (id)photoDataForIndexPath:(id)fp8;
- (id)initWithInstagramJSON:(id)fp8;
- (id)initWithTNDRUser:(id)fp8;

@end

