/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TNDRWhatsNewIntrinsicHeightCalculatorCollectionView : _ABCreateStringWithAddressDictionary
{
    float _intrinsicHeight;
}

- (float)intrinsicHeight;
- (struct CGSize)intrinsicContentSize;
- (void)setIntrinsicHeight:(float)fp8;
- (id)initWithFrame:(struct CGRect)fp8 collectionViewLayout:(id)fp24;

@end

