/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_TNDRFriend.h"

#import "TNDRCommonAttribute-Protocol.h"

@interface TNDRFriend : _TNDRFriend <TNDRCommonAttribute>
{
}

+ (id)createFriendFromTinderID:(id)fp8 requestStatus:(int)fp12 userID:(id)fp16 fullName:(id)fp20;
- (id)description;
- (id)imageURLforSize:(struct CGSize)fp8;
- (id)commonAttributeName;

@end

