/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "MKAnnotation-Protocol.h"

@class CLLocation, MKMapItem, MKPlacemark, NSString;

@interface TNDRPassportMapAnnotation : _ABCreateStringWithAddressDictionary <MKAnnotation>
{
    CDAnonymousStruct11 _coordinate;
    BOOL _receivedUpdatedInfo;
    MKPlacemark *_placemark;
    MKMapItem *_mapItem;
    CLLocation *_location;
    NSString *_name;
    NSString *_title;
    NSString *_subtitle;
}

+ (id)annotationForLocation:(id)fp8;
+ (id)annotationForLocation:(id)fp8 name:(id)fp12 title:(id)fp16 subtitle:(id)fp20;
+ (id)annotationForLocation:(id)fp8 title:(id)fp12 subtitle:(id)fp16;
+ (id)annotationForLocation:(id)fp8 placemark:(id)fp12 mapItem:(id)fp16;
- (void)setReceivedUpdatedInfo:(BOOL)fp8;
- (BOOL)receivedUpdatedInfo;
- (id)subtitle;
- (id)title;
- (id)name;
- (id)location;
- (id)mapItem;
- (id)placemark;
- (void).cxx_destruct;
- (id)gotoLocation;
- (id)landmarkName;
- (id)addressString;
- (id)locationName;
- (id)placeName;
- (CDAnonymousStruct8)coordinate;
- (void)requestLocationInfoWithCompletion:(id)fp(null);
- (void)_setupTitles;
- (id)initForLocation:(id)fp8 name:(id)fp12 title:(id)fp16 subtitle:(id)fp20;
- (id)initWithLocation:(id)fp8 placemark:(id)fp12 mapItem:(id)fp16;
- (id)initWithLocation:(id)fp8;

@end

