/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface TNDRDiscoverOffView : _ABCreateStringWithAddressDictionary
{
    NSString *_discoverOffTitle;
    NSString *_discoverOffDescription;
    NSString *_discoverButtonTitle;
    id <TNDRDiscoverOffViewDelegate> _delegate;
    UIButton *_discoverButton;
    UILabel *_discoverOffTitleLabel;
    UILabel *_discoverOffDescriptionLabel;
    UIImageView *_cardOutlines;
    UIImageView *_gamePadInactive;
    UIActivityIndicatorView *_activityIndicator;
}

- (void)setActivityIndicator:(id)fp8;
- (id)activityIndicator;
- (void)setGamePadInactive:(id)fp8;
- (id)gamePadInactive;
- (void)setCardOutlines:(id)fp8;
- (id)cardOutlines;
- (void)setDiscoverOffDescriptionLabel:(id)fp8;
- (id)discoverOffDescriptionLabel;
- (void)setDiscoverOffTitleLabel:(id)fp8;
- (id)discoverOffTitleLabel;
- (void)setDiscoverButton:(id)fp8;
- (id)discoverButton;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)viewShouldAppearBusy:(BOOL)fp8;
- (void)animateOut:(id)fp(null);
- (void)didTapDiscoverButton:(id)fp8;
- (void)layoutSubviews;
- (void)setup;
- (id)initWithFrame:(struct CGRect)fp8;

@end

