/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TNDRPassportPopularLocationCellDelegate <NSObject>
- (void)configureCell:(id)fp8 atIndexPath:(id)fp12 onCell:(id)fp16;
- (int)numberOfActiveUsersForCell:(id)fp8;
- (void)tappedGoToLocationOnCell:(id)fp8;
@end

