/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRPassportUnderlinedView.h"

@class UILabel;

@interface TNDRPassportLocationsHeaderView : TNDRPassportUnderlinedView
{
    UILabel *_titleLabel;
}

- (void)setTitleLabel:(id)fp8;
- (id)titleLabel;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)fp8;

@end

