/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TNDRCardCellStackControl <NSObject>
- (void)showTutorialToUser:(id)fp8 completion:(id)fp(null);
- (void)returnRecommendationToCenterForServerError:(id)fp8 completion:(id)fp(null);
- (void)returnRecommendationToCenterForSuperLikeLimitExceeded:(id)fp8;
- (void)returnRecommendationToCenterForRateLimiting:(id)fp8;
- (void)returnCardCellToCenter:(id)fp8;
- (void)dismissCardCellWithSwipeUp:(id)fp8 showStamp:(unsigned int)fp12;
- (void)dismissCardCellWithSwipeRight:(id)fp8 showStamp:(unsigned int)fp12;
- (void)dismissCardCellWithSwipeLeft:(id)fp8 showStamp:(unsigned int)fp12;
- (void)showNotInGroupDialogVC;
@end

