/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DDAbstractLogger.h"

#import "DDLogger-Protocol.h"

@interface TNDRCLSLogger : DDAbstractLogger <DDLogger>
{
}

+ (id)sharedInstance;
+ (void)initialize;
- (id)loggerName;
- (void)logMessage:(id)fp8;
- (id)init;

@end

