/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRActionSheetDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, TNDRActionSheet, TNDRDescriptionFooterView, UIActivityIndicatorView, UIImageView, UILabel, UITableView, UITableViewCell, UITextField;

@interface TNDRWebURLViewController : _ABCreateStringWithAddressDictionary <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, TNDRActionSheetDelegate, TNDRURLNavigableProtocol>
{
    BOOL _presentedModally;
    BOOL _dismissingProgrammatically;
    BOOL _confirmationButtonStateEnabled;
    UITableView *_tableView;
    UITableViewCell *_editingProfileURLCell;
    UITableViewCell *_customURLConfirmationCell;
    UITableViewCell *_deleteURLConfirmationCell;
    UITableViewCell *_characterCountingCell;
    UILabel *_customURLLabel;
    UILabel *_deleteURLLabel;
    UITextField *_profileURLTextField;
    NSString *_currentUsername;
    NSString *_initalUsername;
    UILabel *_baseURLabel;
    UILabel *_characterCountLabel;
    UIImageView *_activityIndicator;
    UIActivityIndicatorView *_spinner;
    TNDRDescriptionFooterView *_footerView;
    UILabel *_descriptionLabel;
    float _descriptionLabelMaximumWidth;
    TNDRActionSheet *_deleteURLConfirmationSheet;
}

+ (id)viewControllerNavigationKey;
- (void)setConfirmationButtonStateEnabled:(BOOL)fp8;
- (BOOL)confirmationButtonStateEnabled;
- (void)setDismissingProgrammatically:(BOOL)fp8;
- (BOOL)dismissingProgrammatically;
- (void)setDeleteURLConfirmationSheet:(id)fp8;
- (void)setDescriptionLabelMaximumWidth:(float)fp8;
- (float)descriptionLabelMaximumWidth;
- (void)setDescriptionLabel:(id)fp8;
- (id)descriptionLabel;
- (void)setFooterView:(id)fp8;
- (id)footerView;
- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setActivityIndicator:(id)fp8;
- (id)activityIndicator;
- (void)setCharacterCountLabel:(id)fp8;
- (id)characterCountLabel;
- (void)setBaseURLabel:(id)fp8;
- (id)baseURLabel;
- (void)setInitalUsername:(id)fp8;
- (id)initalUsername;
- (void)setCurrentUsername:(id)fp8;
- (id)currentUsername;
- (void)setProfileURLTextField:(id)fp8;
- (id)profileURLTextField;
- (void)setDeleteURLLabel:(id)fp8;
- (id)deleteURLLabel;
- (void)setCustomURLLabel:(id)fp8;
- (id)customURLLabel;
- (void)setCharacterCountingCell:(id)fp8;
- (void)setDeleteURLConfirmationCell:(id)fp8;
- (void)setCustomURLConfirmationCell:(id)fp8;
- (void)setEditingProfileURLCell:(id)fp8;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (void)setPresentedModally:(BOOL)fp8;
- (BOOL)presentedModally;
- (void).cxx_destruct;
- (id)actionFeasiblilityTinderOrangeColor:(BOOL)fp8;
- (id)baseURLColor;
- (id)cellBorderOutlineColor;
- (struct CGRect)frameForLabelWithSameCenter:(id)fp8;
- (void)showSucessAlertWithMessage:(id)fp8;
- (void)showErrorAlertWithMessage:(id)fp8;
- (void)didTapAccessoryDoneButton;
- (void)actionSheet:(id)fp8 triggeredButtonWithId:(int)fp12;
- (void)handleURLRemoval;
- (void)dismissViewController;
- (void)saveUsernameAndMoveBackToDiscoveryController;
- (void)handleURLConfirmation;
- (void)setEnabledState:(BOOL)fp8 withActivityType:(unsigned int)fp12;
- (float)cellWidth;
- (BOOL)textFieldShouldEndEditing:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayHeaderView:(id)fp12 forSection:(int)fp16;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (id)deleteURLConfirmationSheet;
- (id)characterCountingCell;
- (id)deleteURLConfirmationCell;
- (id)customURLConfirmationCell;
- (id)editingProfileURLCell;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)setupTableView;
- (void)viewDidAppear:(BOOL)fp8;
- (void)didReceiveMemoryWarning;
- (void)setTheFrame;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;

@end

