/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AFJSONResponseSerializer.h"

@interface TNDRJSONResponseSerializerWithData : AFJSONResponseSerializer
{
}

- (id)responseObjectForResponse:(id)fp8 data:(id)fp12 error:(id *)fp16;

@end

