/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TNDRPaywallAnimatableProtocol <NSObject>
- (void)setBottomActionButton:(id)fp8;
- (id)bottomActionButton;
- (void)setContainerView:(id)fp8;
- (id)containerView;
- (void)setBackgroundOverlay:(id)fp8;
- (id)backgroundOverlay;
@end

