/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDROptionsTableViewControllerDelegate-Protocol.h"
#import "TNDRSliderCellDelegate-Protocol.h"
#import "TNDRSwitchCellDelegate-Protocol.h"
#import "TNDRTinderPlusBlendSelectTableViewControllerDelegate-Protocol.h"
#import "TNDRTinderPlusFeaturePurchaseTableViewControllerDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, TNDRDescriptionFooterView, TNDROptionsTableViewController, TNDRPassportLocationsListViewController, TNDRPassportLocationsListViewModel, TNDRSliderCell, TNDRTinderPlusRecsBlendSelectTableViewController, TNDRWebURLViewController, UISwitch, UITableViewCell;

@interface TNDRDiscoverSettingsViewController : _ABCreateStringWithAddressDictionary <TNDRSliderCellDelegate, TNDRSwitchCellDelegate, TNDROptionsTableViewControllerDelegate, TNDRTinderPlusFeaturePurchaseTableViewControllerDelegate, TNDRTinderPlusBlendSelectTableViewControllerDelegate, UITableViewDataSource, UITableViewDelegate, TNDRURLNavigableProtocol>
{
    BOOL _preventUpdateOfSettings;
    UITableViewCell *_showMeCell;
    TNDRDescriptionFooterView *_showMeDescriptionFooter;
    TNDRDescriptionFooterView *_usernameTutorialDescriptionFooter;
    UITableViewCell *_locationCell;
    TNDRSliderCell *_distanceSliderCell;
    TNDRSliderCell *_ageSliderCell;
    UITableViewCell *_genderPreferenceCell;
    UITableViewCell *_blendRecsPreferenceCell;
    UISwitch *_showMeSwitch;
    UITableViewCell *_urlEditingCell;
    UITableViewCell *_urlSharingCell;
    UITableViewCell *_viewURLCell;
    NSString *_publicUserName;
    TNDRPassportLocationsListViewModel *_passportViewModel;
    TNDRPassportLocationsListViewController *_passportLocationsListController;
    TNDRTinderPlusRecsBlendSelectTableViewController *_blendOptionsTableViewController;
    TNDROptionsTableViewController *_genderOptionsTableViewController;
    int _currentSelectedBlend;
    NSMutableArray *_sectionNumberToDiscoverySectionTypeMapper;
    TNDRWebURLViewController *_webURLViewController;
}

+ (id)viewControllerNavigationKey;
- (void)setWebURLViewController:(id)fp8;
- (void)setSectionNumberToDiscoverySectionTypeMapper:(id)fp8;
- (id)sectionNumberToDiscoverySectionTypeMapper;
- (void)setCurrentSelectedBlend:(int)fp8;
- (int)currentSelectedBlend;
- (void)setGenderOptionsTableViewController:(id)fp8;
- (id)genderOptionsTableViewController;
- (void)setBlendOptionsTableViewController:(id)fp8;
- (id)blendOptionsTableViewController;
- (void)setPassportLocationsListController:(id)fp8;
- (void)setPassportViewModel:(id)fp8;
- (void)setPreventUpdateOfSettings:(BOOL)fp8;
- (BOOL)preventUpdateOfSettings;
- (void)setPublicUserName:(id)fp8;
- (id)publicUserName;
- (void)setViewURLCell:(id)fp8;
- (void)setUrlSharingCell:(id)fp8;
- (void)setUrlEditingCell:(id)fp8;
- (void)setShowMeSwitch:(id)fp8;
- (id)showMeSwitch;
- (void)setBlendRecsPreferenceCell:(id)fp8;
- (void)setGenderPreferenceCell:(id)fp8;
- (void)setAgeSliderCell:(id)fp8;
- (void)setDistanceSliderCell:(id)fp8;
- (void)setLocationCell:(id)fp8;
- (void)setUsernameTutorialDescriptionFooter:(id)fp8;
- (id)usernameTutorialDescriptionFooter;
- (void)setShowMeDescriptionFooter:(id)fp8;
- (id)showMeDescriptionFooter;
- (void)setShowMeCell:(id)fp8;
- (void).cxx_destruct;
- (void)handleSharingResponseWithActivityType:(id)fp8 completion:(BOOL)fp12;
- (void)transitionTo:(id)fp8 optionsDict:(id)fp12 animated:(BOOL)fp16 completion:(id)fp(null);
- (id)webURLViewController;
- (id)passportLocationsListController;
- (void)handleDiscoverSwitchChanged:(id)fp8;
- (void)updateServerWithChangedSettings;
- (id)titleForCurrentBlend;
- (id)indexPathOfCurrentSelectedBlend;
- (int)currentSelectedGender;
- (id)attributedStringForLocationText:(id)fp8 traveling:(BOOL)fp12;
- (void)updateLocationCellForCurrentUser:(id)fp8;
- (void)adjustAgeSliderCellValuesForCurrentUser:(id)fp8;
- (void)configureForCurrentUser;
- (void)tndr_tableViewController:(id)fp8 didSelectBlend:(int)fp12 didFinishSelection:(BOOL)fp16;
- (void)tndr_tableViewControllerDidSelectGetTinderPlus:(id)fp8;
- (void)didSelectOptionWithIndex:(int)fp8;
- (void)didToggleSwitch:(id)fp8;
- (void)sliderValueChanged:(id)fp8;
- (void)didChangeSliderValue:(id)fp8;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)viewURLCell;
- (id)urlEditingCell;
- (id)urlSharingCell;
- (int)discoverWhereSectionAdjustedRow:(int)fp8;
- (void)refreshPassportViewModel;
- (id)newPassportViewModel;
- (id)passportViewModel;
- (id)blendRecsPreferenceCell;
- (id)genderPreferenceCell;
- (id)ageSliderCell;
- (void)configureDistanceSliderCellForStandardMeasurement:(id)fp8;
- (void)configureDistanceSliderCellForMetricMeasurement:(id)fp8;
- (id)distanceSliderCell;
- (id)locationCell;
- (id)showMeCell;
- (void)handleUserDidSynchronize:(id)fp8;
- (void)unregisterNotifications;
- (void)registerNotifications;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)init;

@end

