/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRActionSheetDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"

@class NSArray, TNDRActionSheet, TNDRAppSettingsLogoView, TNDRAppSettingsTableViewCell, TNDRDescriptionFooterView, TNDROSSLicensesTVC, TNDRSupportContacter, UISwitch;

@interface TNDRAppSettingsViewController : _ABCreateStringWithAddressDictionary <TNDRActionSheetDelegate, TNDRURLNavigableProtocol>
{
    BOOL _loggingOut;
    id <TNDRAppSettingsViewControllerDelegate> _menuDelegate;
    UISwitch *_notificationNewMatchSwitch;
    UISwitch *_notificationMessageLikeSwitch;
    UISwitch *_notificationMatchRequestSwitch;
    UISwitch *_notificationMessagesSwitch;
    UISwitch *_notificationSuperLikeSwitch;
    UISwitch *_notificationVibrationSwitch;
    TNDRAppSettingsLogoView *_logoView;
    TNDRDescriptionFooterView *_tinderIDDescriptionFooterView;
    TNDRAppSettingsTableViewCell *_tinderIDCell;
    TNDRSupportContacter *_contacter;
    TNDRActionSheet *_logoutActionSheet;
    TNDRActionSheet *_deleteActionSheet;
    TNDROSSLicensesTVC *_licencesTVC;
    NSArray *_sections;
}

+ (id)viewControllerNavigationKey;
- (void)setLoggingOut:(BOOL)fp8;
- (BOOL)loggingOut;
- (void)setSections:(id)fp8;
- (id)sections;
- (void)setLicencesTVC:(id)fp8;
- (id)licencesTVC;
- (void)setDeleteActionSheet:(id)fp8;
- (id)deleteActionSheet;
- (void)setLogoutActionSheet:(id)fp8;
- (id)logoutActionSheet;
- (void)setContacter:(id)fp8;
- (id)contacter;
- (void)setTinderIDCell:(id)fp8;
- (void)setTinderIDDescriptionFooterView:(id)fp8;
- (id)tinderIDDescriptionFooterView;
- (void)setLogoView:(id)fp8;
- (id)logoView;
- (void)setNotificationVibrationSwitch:(id)fp8;
- (id)notificationVibrationSwitch;
- (void)setNotificationSuperLikeSwitch:(id)fp8;
- (id)notificationSuperLikeSwitch;
- (void)setNotificationMessagesSwitch:(id)fp8;
- (id)notificationMessagesSwitch;
- (void)setNotificationMatchRequestSwitch:(id)fp8;
- (id)notificationMatchRequestSwitch;
- (void)setNotificationMessageLikeSwitch:(id)fp8;
- (id)notificationMessageLikeSwitch;
- (void)setNotificationNewMatchSwitch:(id)fp8;
- (id)notificationNewMatchSwitch;
- (void)setMenuDelegate:(id)fp8;
- (id)menuDelegate;
- (void).cxx_destruct;
- (void)navigateToGameViewController;
- (void)showLicenses;
- (void)showURL:(id)fp8 title:(id)fp12;
- (void)showTermsOfService;
- (void)showPrivacyPolicy;
- (void)updateServerWithNewPushNotificationSettings;
- (void)saveSettings:(id)fp8;
- (void)saveNotificationSwitches;
- (void)setNotificationSwitches;
- (void)actionSheet:(id)fp8 triggeredButtonWithId:(int)fp12;
- (void)performUserDeletion;
- (void)deleteAccount:(id)fp8;
- (void)handleUserDidClearInformation:(id)fp8;
- (void)performUserLogout;
- (void)logOut:(id)fp8;
- (void)shareTinder:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 viewForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)tinderIDCell;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)init;

@end

