/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface TNDRMyProfilePhotoCell : _ABCreateStringWithAddressDictionary
{
    UIImageView *_overlayImageView;
    BOOL _clearMask;
    UIButton *_button;
    BOOL _hideButtons;
    BOOL _hidePhotoNumberShadow;
    BOOL _photoUploadInProgress;
    UIImageView *_photo;
    UIButton *_deleteButton;
    UIButton *_addButton;
    UIButton *_dotDotDotButton;
    UILabel *_photoNumberLabel;
    UIActivityIndicatorView *_photoUploadIndicator;
}

- (void)setPhotoUploadIndicator:(id)fp8;
- (id)photoUploadIndicator;
- (BOOL)photoUploadInProgress;
- (BOOL)hidePhotoNumberShadow;
- (BOOL)hideButtons;
- (void)setPhotoNumberLabel:(id)fp8;
- (id)photoNumberLabel;
- (void)setDotDotDotButton:(id)fp8;
- (id)dotDotDotButton;
- (void)setAddButton:(id)fp8;
- (id)addButton;
- (void)setDeleteButton:(id)fp8;
- (id)deleteButton;
- (void)setPhoto:(id)fp8;
- (id)photo;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)placeHolderImage;
- (void)makeFrameAndShadow;
- (void)applyLayoutAttributes:(id)fp8;
- (id)makeButtonWithImage:(id)fp8 isAdd:(BOOL)fp12;
- (void)makeButtons;
- (void)setHideButtons:(BOOL)fp8;
- (void)prepareForReuse;
- (void)maskOff:(BOOL)fp8;
- (void)makeMask;
- (id)imageWithImage:(id)fp8 scaledToSize:(struct CGSize)fp12;
- (void)setPhotoUploadInProgress:(BOOL)fp8;
- (void)makePhotoNumberLabelShadow;
- (void)setHidePhotoNumberShadow:(BOOL)fp8;
- (void)makePhotoNumberLabel;
- (void)makePhotoUploadIndicator;
- (void)makePhotoView;
- (id)initWithFrame:(struct CGRect)fp8;

@end

