/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRCardCell.h"

#import "TNDRCardCellViewProvider-Protocol.h"
#import "TNDRRecCardCellProtocol-Protocol.h"

@class TNDRCardCellGroupInfoView, TNDRCardCellGroupPhotoView, TNDRGroup, TNDRTutorialToolTip;

@interface TNDRGroupCardCell : TNDRCardCell <TNDRCardCellViewProvider, TNDRRecCardCellProtocol>
{
    BOOL _superLiked;
    BOOL _superLikeAvailable;
    TNDRGroup *_group;
    TNDRCardCellGroupPhotoView *_photoView;
    TNDRCardCellGroupInfoView *_infoView;
    TNDRTutorialToolTip *_toolTip;
}

- (void)setSuperLikeAvailable:(BOOL)fp8;
- (BOOL)superLikeAvailable;
- (void)setSuperLiked:(BOOL)fp8;
- (BOOL)superLiked;
- (void)setToolTip:(id)fp8;
- (void)setInfoView:(id)fp8;
- (id)infoView;
- (void)setPhotoView:(id)fp8;
- (id)photoView;
- (id)group;
- (void).cxx_destruct;
- (id)superLikeShadowColor;
- (id)superLikeBorderColor;
- (void)handleSuperLikeTopCardHidden:(id)fp8;
- (void)handleSuperLikeTopCardRevealed:(id)fp8;
- (id)toolTip;
- (void)resetToolTip;
- (void)pulsate;
- (id)description;
- (id)secondaryView;
- (id)contentView;
- (id)recObject;
- (id)recID;
- (void)showSuperLikeChrome;
- (void)hideSuperLikeChrome;
- (BOOL)isSuperLikeCard;
- (void)setGroup:(id)fp8;
- (void)prepareForCardStackAnimation:(BOOL)fp8;
- (void)prepareForCardStackAnimation:(BOOL)fp8 hideProfilePhoto:(BOOL)fp12;
- (void)prepareForReuse;
- (void)setUpObservers;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

