/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "MKMapViewDelegate-Protocol.h"
#import "SMCalloutViewDelegate-Protocol.h"
#import "TNDRPassportMapSearchViewControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CALayer, CLLocation, MKAnnotationView, MKPlacemark, NSTimer, TNDRPassportMapAnnotation, TNDRPassportMapAnnotationLookup, TNDRPassportMapView, TNDRPassportMapViewCalloutView, UILongPressGestureRecognizer, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface TNDRPassportMapViewController : _ABCreateStringWithAddressDictionary <UIGestureRecognizerDelegate, MKMapViewDelegate, SMCalloutViewDelegate, TNDRPassportMapSearchViewControllerDelegate>
{
    CALayer *_mapLayer;
    NSTimer *_timer;
    BOOL _usingCurrentUserLocation;
    BOOL _dismissCurrentCallout;
    BOOL _userPinDrop;
    BOOL _notZoomed;
    BOOL _movedMapWithAFingerOrANipple;
    BOOL _mapRegionIsChanging;
    BOOL _dropPinInProgress;
    id <TNDRPassportPaywallDelegate> _paywallDelegate;
    id <TNDRPassportMapViewDelegate> _delegate;
    CLLocation *_activeLocation;
    MKPlacemark *_activePlacemark;
    TNDRPassportMapView *_mapView;
    TNDRPassportMapViewCalloutView *_calloutView;
    TNDRPassportMapAnnotationLookup *_annotationLookup;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    id _moveToAnnotateMapLocationCompletionBlock;
    id _didAddAnnotationCompletionBlock;
    MKAnnotationView *_selectedAnnotationView;
    NSTimer *_pinDropCalloutAnimTimer;
    int _calloutViewLoadingState;
    TNDRPassportMapAnnotation *_lastAnnotationOperation;
    MKPlacemark *_placemarkSelectedFromSearch;
    MKAnnotationView *_lastSelectedAnnotationView;
    UIPanGestureRecognizer *_mapMoveGestureRecognizer;
    CDAnonymousStruct11 _currentLocation;
}

- (void)setDropPinInProgress:(BOOL)fp8;
- (BOOL)isDropPinInProgress;
- (void)setMapRegionIsChanging:(BOOL)fp8;
- (BOOL)mapRegionIsChanging;
- (void)setMovedMapWithAFingerOrANipple:(BOOL)fp8;
- (BOOL)hasMovedMapWithAFingerOrANipple;
- (void)setMapMoveGestureRecognizer:(id)fp8;
- (id)mapMoveGestureRecognizer;
- (void)setNotZoomed:(BOOL)fp8;
- (BOOL)isNotZoomed;
- (void)setUserPinDrop:(BOOL)fp8;
- (BOOL)isUserPinDrop;
- (void)setLastSelectedAnnotationView:(id)fp8;
- (id)lastSelectedAnnotationView;
- (void)setPlacemarkSelectedFromSearch:(id)fp8;
- (id)placemarkSelectedFromSearch;
- (void)setLastAnnotationOperation:(id)fp8;
- (id)lastAnnotationOperation;
- (void)setCalloutViewLoadingState:(int)fp8;
- (int)calloutViewLoadingState;
- (void)setPinDropCalloutAnimTimer:(id)fp8;
- (id)pinDropCalloutAnimTimer;
- (void)setSelectedAnnotationView:(id)fp8;
- (id)selectedAnnotationView;
- (void)setDidAddAnnotationCompletionBlock:(id)fp(null);
- (id)didAddAnnotationCompletionBlock;
- (void)setMoveToAnnotateMapLocationCompletionBlock:(id)fp(null);
- (id)moveToAnnotateMapLocationCompletionBlock;
- (void)setDismissCurrentCallout:(BOOL)fp8;
- (BOOL)dismissCurrentCallout;
- (void)setDoubleTapGestureRecognizer:(id)fp8;
- (id)doubleTapGestureRecognizer;
- (void)setLongPressGestureRecognizer:(id)fp8;
- (id)longPressGestureRecognizer;
- (void)setTapGestureRecognizer:(id)fp8;
- (id)tapGestureRecognizer;
- (void)setAnnotationLookup:(id)fp8;
- (id)annotationLookup;
- (void)setCalloutView:(id)fp8;
- (id)calloutView;
- (void)setMapView:(id)fp8;
- (id)mapView;
- (void)setActivePlacemark:(id)fp8;
- (id)activePlacemark;
- (void)setActiveLocation:(id)fp8;
- (id)activeLocation;
- (void)setUsingCurrentUserLocation:(BOOL)fp8;
- (BOOL)isUsingCurrentUserLocation;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setPaywallDelegate:(id)fp8;
- (id)paywallDelegate;
- (void)setCurrentLocation:(CDAnonymousStruct8)fp8;
- (CDAnonymousStruct8)currentLocation;
- (void).cxx_destruct;
- (void)dropPin:(id)fp8;
- (void)pinTapped;
- (id)checkmarkImage;
- (void)calloutViewClicked:(id)fp8;
- (void)setupCalloutViewForTraveling;
- (void)showTravelingCalloutViewWithTitle:(id)fp8 andSubtitle:(id)fp12;
- (void)animateInCalloutView:(id)fp8;
- (void)setupAndDisplayAnnotation:(id)fp8 forAnnotationView:(id)fp12;
- (void)setupCalloutViewWithLeftAirplaneIcon:(BOOL)fp8;
- (void)setAnchorPoint:(struct CGPoint)fp8 forView:(id)fp16;
- (void)animateSquishAnnotationView:(id)fp8;
- (void)animateInAnnotationView:(id)fp8;
- (void)mapView:(id)fp8 didDeselectAnnotationView:(id)fp12;
- (void)mapView:(id)fp8 didSelectAnnotationView:(id)fp12;
- (void)mapView:(id)fp8 didAddAnnotationViews:(id)fp12;
- (id)mapView:(id)fp8 viewForAnnotation:(id)fp12;
- (void)mapView:(id)fp8 regionDidChangeAnimated:(BOOL)fp12;
- (void)mapView:(id)fp8 regionWillChangeAnimated:(BOOL)fp12;
- (void)showAnnotation:(id)fp8 moveMap:(BOOL)fp12 zoomed:(BOOL)fp16 animated:(BOOL)fp20 fromSearch:(BOOL)fp24 completion:(id)fp(null);
- (void)showAnnotation:(id)fp8 zoomed:(BOOL)fp12 animated:(BOOL)fp16 fromSearch:(BOOL)fp20 completion:(id)fp(null);
- (void)showAnnotation:(id)fp8 zoomed:(BOOL)fp12 animated:(BOOL)fp16 completion:(id)fp(null);
- (void)showAnnotationAtLocation:(id)fp8 moveMap:(BOOL)fp12 zoomed:(BOOL)fp16 animated:(BOOL)fp20 isCurrentUserLocation:(BOOL)fp24 completion:(id)fp(null);
- (void)showAnnotationAtLocation:(id)fp8 moveMap:(BOOL)fp12 zoomed:(BOOL)fp16 animated:(BOOL)fp20 completion:(id)fp(null);
- (float)round:(float)fp8 toSignificantFigures:(int)fp12;
- (BOOL)isDouble:(double)fp8 equivalentTo:(double)fp16;
- (BOOL)isRegion:(CDAnonymousStruct2)fp8 equalToRegion:(CDAnonymousStruct2)fp40;
- (void)moveToAnnotatedMapLocation:(id)fp8 moveMap:(BOOL)fp12 zoomed:(BOOL)fp16 animated:(BOOL)fp20 completion:(id)fp(null);
- (void)moveToAnnotatedMapLocation:(id)fp8 animated:(BOOL)fp12 completion:(id)fp(null);
- (void)moveToAnnotatedMapLocation:(id)fp8 animated:(BOOL)fp12;
- (void)moveToAnnotatedMapLocation:(id)fp8;
- (void)didSelectToCloseMapView;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (void)handleMapMovePanGestureRecognizer:(id)fp8;
- (void)_handleDoubleTap;
- (void)setupMapGestureRecognizers;
- (void)viewDidLoad;
- (id)init;

@end

