/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, NSLayoutConstraint, NSString, NSURL, TNDRExpiredChatGamepadView, TNDRUser, UIImage, UIImageView, UILabel, UIView<TNDRExpiredChatRowDelegate>;

@interface TNDRExpiredChatRow : _ABCreateStringWithAddressDictionary
{
    UIView<TNDRExpiredChatRowDelegate> *_delegate;
    NSString *_name;
    NSURL *_imageURL;
    TNDRUser *_user;
    int _swipeValue;
    UIImageView *_avatarImageView;
    UILabel *_nameLabel;
    NSString *_detailText;
    UILabel *_detailTextLabel;
    UIImage *_circleImage;
    TNDRExpiredChatGamepadView *_gamepad;
    NSLayoutConstraint *_nameLabelCenterYConstraint;
    NSArray *_detailTextConstraints;
    UIImageView *_celebrityBadgeImageView;
    UIImageView *_rightImageView;
}

- (void)setRightImageView:(id)fp8;
- (id)rightImageView;
- (void)setCelebrityBadgeImageView:(id)fp8;
- (id)celebrityBadgeImageView;
- (void)setDetailTextConstraints:(id)fp8;
- (id)detailTextConstraints;
- (void)setNameLabelCenterYConstraint:(id)fp8;
- (id)nameLabelCenterYConstraint;
- (void)setGamepad:(id)fp8;
- (id)gamepad;
- (void)setCircleImage:(id)fp8;
- (id)circleImage;
- (void)setDetailTextLabel:(id)fp8;
- (id)detailTextLabel;
- (id)detailText;
- (void)setNameLabel:(id)fp8;
- (id)nameLabel;
- (void)setAvatarImageView:(id)fp8;
- (id)avatarImageView;
- (int)swipeValue;
- (id)user;
- (id)imageURL;
- (id)name;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)trackRatingOfLiked:(BOOL)fp8 superLiked:(BOOL)fp12 fromMore:(BOOL)fp16;
- (void)updateRecommendationToPass;
- (void)superLikeButtonTapped:(id)fp8;
- (void)passButtonTapped:(id)fp8;
- (void)likeButtonTapped:(id)fp8;
- (void)didTapAvatar:(id)fp8;
- (void)disableButtons;
- (void)greyOutButton:(id)fp8;
- (void)setSwipeValue:(int)fp8;
- (void)configureForDidSuperlikeCurrentUserIfNeeded;
- (void)setUser:(id)fp8;
- (void)setImageURL:(id)fp8;
- (void)setDetailText:(id)fp8;
- (void)setName:(id)fp8;
- (void)addDetailTextConstraints;
- (void)setupConstraints;
- (void)setupButtonpad;
- (void)setupBadgeView;
- (void)setupDetailTextLabel;
- (void)setupNameView;
- (void)setupAvatarView;
- (void)setup;
- (id)initWithFrame:(struct CGRect)fp8;

@end

