/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TNDRImageManager : _ABCreateStringWithAddressDictionary
{
}

+ (id)sharedInstance;
- (id)keyForManagedObjectID:(id)fp8;
- (id)retrieveImageFromDiskForKey:(id)fp8;
- (id)writeImage:(id)fp8 toDiskWithKey:(id)fp12;
- (id)imagePathForKey:(id)fp8;

@end

