/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "ABKAppboyEndpointDelegate-Protocol.h"

@interface TNDRAppboyEndpointDelegate : _ABCreateStringWithAddressDictionary <ABKAppboyEndpointDelegate>
{
}

- (id)getResourceEndpoint:(id)fp8;
- (id)getApiEndpoint:(id)fp8;

@end

