/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRExperiment.h"

@interface TNDRSMSARecExperiment : TNDRExperiment
{
}

- (void)preloadExperimentVariables;
- (void)setupExperimentVariables;
- (void)updateExperiment;
- (id)profileShareRecColor;
- (id)superLikeCardShareRecColor;
- (id)cardShareRecColor;
- (id)colorForExperimentVar:(id)fp8;
- (BOOL)shouldShowShareRecOnProfile;
- (BOOL)shouldShowShareRecOnCard;
- (id)experimentVariables;
- (id)experimentName;

@end

