/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NBPhoneNumberUtil, NSArray, NSIndexPath, NSNumber, NSString, UIBarButtonItem, UINavigationBar, UITableView;

@interface TNDRRegionCodePickerController : _ABCreateStringWithAddressDictionary <UITableViewDataSource, UITableViewDelegate>
{
    id <TNDRRegionCodePickerDelegate> _delegate;
    NSNumber *_selectedRegionPrefix;
    NSString *_selectedRegionCode;
    UITableView *_tableView;
    UINavigationBar *_navigationBar;
    NSArray *_regionData;
    NBPhoneNumberUtil *_sharedPhoneUtil;
    UIBarButtonItem *_barButtonChoose;
    NSString *_cellIdentifier;
    NSIndexPath *_selectedIndexPath;
}

- (void)setSelectedIndexPath:(id)fp8;
- (id)selectedIndexPath;
- (void)setCellIdentifier:(id)fp8;
- (id)cellIdentifier;
- (void)setBarButtonChoose:(id)fp8;
- (id)barButtonChoose;
- (void)setSharedPhoneUtil:(id)fp8;
- (id)sharedPhoneUtil;
- (void)setRegionData:(id)fp8;
- (id)regionData;
- (void)setNavigationBar:(id)fp8;
- (id)navigationBar;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (void)setSelectedRegionCode:(id)fp8;
- (id)selectedRegionCode;
- (void)setSelectedRegionPrefix:(id)fp8;
- (id)selectedRegionPrefix;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)scrollToSelectedCountry;
- (void)handleChooseRegionTapped:(id)fp8;
- (void)handleCloseTapped:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)setupTableView;
- (void)setupNavigationBar;
- (void)setupData;
- (void)setup;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)init;

@end

