/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIImageView, UILabel;

@interface TNDRTooltip : _ABCreateStringWithAddressDictionary
{
    UILabel *_textLabel;
    UIImageView *_centerImageView;
    UIImageView *_rightImageView;
    UIImageView *_leftImageView;
}

- (void)setLeftImageView:(id)fp8;
- (id)leftImageView;
- (void)setRightImageView:(id)fp8;
- (id)rightImageView;
- (void)setCenterImageView:(id)fp8;
- (id)centerImageView;
- (void)setTextLabel:(id)fp8;
- (id)textLabel;
- (void).cxx_destruct;
- (id)initWithText:(id)fp8 aboveView:(id)fp12 inView:(id)fp16;

@end

