/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TNDRCardCell.h"

#import "TNDRCardCellViewProvider-Protocol.h"
#import "TNDRRecCardCellProtocol-Protocol.h"

@class TNDRCardCellUserInformationView, TNDRCardCellUserProfilePhotoView, TNDRTutorialToolTip, TNDRUser, UITapGestureRecognizer;

@interface TNDRUserCardCell : TNDRCardCell <TNDRCardCellViewProvider, TNDRRecCardCellProtocol>
{
    BOOL _superLiked;
    TNDRUser *_user;
    TNDRCardCellUserProfilePhotoView *_profilePhotoView;
    TNDRCardCellUserInformationView *_informationView;
    TNDRTutorialToolTip *_toolTip;
    id <TNDRUserCardCellDelegate> _delegate;
    UITapGestureRecognizer *_tapShareButtonGR;
}

- (void)setTapShareButtonGR:(id)fp8;
- (id)tapShareButtonGR;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setSuperLiked:(BOOL)fp8;
- (BOOL)superLiked;
- (void)setToolTip:(id)fp8;
- (void)setInformationView:(id)fp8;
- (id)informationView;
- (void)setProfilePhotoView:(id)fp8;
- (id)profilePhotoView;
- (id)user;
- (void).cxx_destruct;
- (void)handleTapShareButton:(id)fp8;
- (id)superLikeShadowColor;
- (id)superLikeBorderColor;
- (void)handleShareButtonRequestComplete:(id)fp8;
- (void)handleSuperLikeTopCardHidden:(id)fp8;
- (void)handleSuperLikeTopCardRevealed:(id)fp8;
- (id)recObject;
- (id)recID;
- (id)toolTip;
- (void)resetToolTip;
- (void)pulsate;
- (id)description;
- (id)secondaryView;
- (id)contentView;
- (void)showSuperLikeChrome;
- (void)hideSuperLikeChrome;
- (BOOL)isSuperLikeCard;
- (void)setUser:(id)fp8;
- (void)prepareForCardStackAnimation:(BOOL)fp8 hideProfilePhoto:(BOOL)fp12;
- (void)prepareForCardStackAnimation:(BOOL)fp8;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

