/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSMutableDictionary, NSMutableSet;

@interface TNDRPassportStackLayout : _ABCreateStringWithAddressDictionary
{
    float _scaleFactor;
    float _verticalDistanceBetweenCards;
    float _stackCenterVerticalOffset;
    NSMutableDictionary *_layoutAttributes;
    NSMutableSet *_insertedIndexPaths;
    NSMutableSet *_deletedIndexPaths;
    struct CGSize _cardSize;
}

- (void)setDeletedIndexPaths:(id)fp8;
- (id)deletedIndexPaths;
- (void)setInsertedIndexPaths:(id)fp8;
- (id)insertedIndexPaths;
- (void)setLayoutAttributes:(id)fp8;
- (id)layoutAttributes;
- (void)setStackCenterVerticalOffset:(float)fp8;
- (float)stackCenterVerticalOffset;
- (void)setCardSize:(struct CGSize)fp8;
- (struct CGSize)cardSize;
- (void)setVerticalDistanceBetweenCards:(float)fp8;
- (float)verticalDistanceBetweenCards;
- (float)scaleFactor;
- (void).cxx_destruct;
- (id)layoutAttributesForItemAtIndexPath:(id)fp8;
- (id)layoutAttributesForElementsInRect:(struct CGRect)fp8;
- (void)finalizeCollectionViewUpdates;
- (void)prepareForCollectionViewUpdates:(id)fp8;
- (void)prepareLayout;
- (struct CGSize)collectionViewContentSize;
- (void)setScaleFactor:(float)fp8;
- (id)init;

@end

