/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSLayoutConstraint, TNDRCardCellSocialStatView, TNDRCardCellSuperLikeStarView, TNDRUserTeaserViewModel, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIView;

@interface TNDRCardCellUserInformationView : _ABCreateStringWithAddressDictionary <UIGestureRecognizerDelegate>
{
    BOOL _isSuperLikeView;
    BOOL _superLikeStarAnimating;
    BOOL _superLikeChromeHidden;
    BOOL _hasBadge;
    BOOL _superLikeAvailable;
    BOOL _showShareButton;
    UIImageView *_celebrityBadgeImageView;
    UIView *_superLikeColorBar;
    TNDRCardCellSuperLikeStarView *_superLikeStarView;
    UIButton *_shareButton;
    UILabel *_nameAndAgeLabel;
    UILabel *_bottomDescriptionLabel;
    TNDRCardCellSocialStatView *_commonFriendsStatView;
    TNDRCardCellSocialStatView *_commonInterestsStatView;
    UIActivityIndicatorView *_shareLoadingIndicator;
    NSLayoutConstraint *_nameAndAgeLabelVerticalPosition;
    NSLayoutConstraint *_nameAndAgeLabelRightConstraint;
    NSLayoutConstraint *_commonFriendsNoInterestContraint;
    NSLayoutConstraint *_commonFriendsHasInterestConstraint;
    NSLayoutConstraint *_commonFriendsStatViewWidthConstraint;
    NSLayoutConstraint *_commonInterestsStatViewWidthConstaint;
    NSLayoutConstraint *_superLikeBarHeightConstraint;
    int _commonInterestsCount;
    TNDRUserTeaserViewModel *_teaserViewModel;
}

- (void)setShowShareButton:(BOOL)fp8;
- (BOOL)showShareButton;
- (void)setSuperLikeAvailable:(BOOL)fp8;
- (BOOL)superLikeAvailable;
- (void)setTeaserViewModel:(id)fp8;
- (id)teaserViewModel;
- (void)setCommonInterestsCount:(int)fp8;
- (int)commonInterestsCount;
- (void)setHasBadge:(BOOL)fp8;
- (BOOL)hasBadge;
- (void)setSuperLikeBarHeightConstraint:(id)fp8;
- (id)superLikeBarHeightConstraint;
- (void)setSuperLikeChromeHidden:(BOOL)fp8;
- (BOOL)superLikeChromeHidden;
- (void)setSuperLikeStarAnimating:(BOOL)fp8;
- (BOOL)isSuperLikeStarAnimating;
- (void)setIsSuperLikeView:(BOOL)fp8;
- (BOOL)isSuperLikeView;
- (void)setCommonInterestsStatViewWidthConstaint:(id)fp8;
- (id)commonInterestsStatViewWidthConstaint;
- (void)setCommonFriendsStatViewWidthConstraint:(id)fp8;
- (id)commonFriendsStatViewWidthConstraint;
- (void)setCommonFriendsHasInterestConstraint:(id)fp8;
- (id)commonFriendsHasInterestConstraint;
- (void)setCommonFriendsNoInterestContraint:(id)fp8;
- (id)commonFriendsNoInterestContraint;
- (void)setNameAndAgeLabelRightConstraint:(id)fp8;
- (id)nameAndAgeLabelRightConstraint;
- (void)setNameAndAgeLabelVerticalPosition:(id)fp8;
- (id)nameAndAgeLabelVerticalPosition;
- (void)setShareLoadingIndicator:(id)fp8;
- (id)shareLoadingIndicator;
- (void)setCommonInterestsStatView:(id)fp8;
- (id)commonInterestsStatView;
- (void)setCommonFriendsStatView:(id)fp8;
- (id)commonFriendsStatView;
- (void)setBottomDescriptionLabel:(id)fp8;
- (id)bottomDescriptionLabel;
- (void)setNameAndAgeLabel:(id)fp8;
- (id)nameAndAgeLabel;
- (void)setShareButton:(id)fp8;
- (id)shareButton;
- (void)setSuperLikeStarView:(id)fp8;
- (id)superLikeStarView;
- (void)setSuperLikeColorBar:(id)fp8;
- (id)superLikeColorBar;
- (void)setCelebrityBadgeImageView:(id)fp8;
- (id)celebrityBadgeImageView;
- (void).cxx_destruct;
- (void)configureBottomDescriptionLabelWithUser:(id)fp8;
- (id)superLikeColorBarColor;
- (id)superLikeTextColor;
- (id)nameTextSuperLikeColor;
- (id)nameTextDefaultColor;
- (id)statDefaultCommonTintColor;
- (id)statSuperLikeTintColor;
- (id)statDefaultTintColor;
- (id)defaultBackgroundColor;
- (void)configureCommonInterestsView:(id)fp8 value:(int)fp12;
- (void)configureCommonFriendsView:(id)fp8 value:(int)fp12;
- (void)configureName:(id)fp8 age:(id)fp12;
- (void)updateConstraints;
- (void)stopShareLoadingIndicator;
- (void)startShareLoadingIndicator;
- (void)stopAnimatingSuperLikeStar;
- (void)startAnimatingSuperLikeStar;
- (void)hideSuperLikeBar:(BOOL)fp8 animated:(BOOL)fp12;
- (void)hideSuperLikeChrome:(BOOL)fp8 animated:(BOOL)fp12;
- (void)resetView;
- (void)layoutSubviews;
- (void)configureWithUser:(id)fp8;
- (void)layoutSuperLikeStarView;
- (void)layoutSuperLikeColorBar;
- (void)layoutCelebrityBadgeImageView;
- (void)layoutCommonFriendsStatView;
- (void)layoutBottomDescriptionLabel;
- (void)layoutCommonInterestsStatView;
- (void)layoutShareButton;
- (void)layoutNameAndAgeLabel;
- (void)setupUserTeaserViewModel;
- (void)setupSuperLikeStarView;
- (void)setupSuperLikeColorBar;
- (void)setupCelebrityBadgeImageView;
- (void)setupCommonFriendsStatView;
- (void)setupBottomDescriptionLabel;
- (void)setupCommonInterestsStatView;
- (void)setupShareButton;
- (void)setupNameAndAgeLabel;
- (void)setup;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithSuperLikeAvailable:(BOOL)fp8 showShareButton:(BOOL)fp12;

@end

