/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIImageView, UILabel;

@interface TNDRIntroCell : _ABCreateStringWithAddressDictionary
{
    UILabel *_descriptionLabel;
    UIImageView *_screenshotImageView;
    UIImageView *_phoneWireFrameImageView;
}

- (void)setPhoneWireFrameImageView:(id)fp8;
- (id)phoneWireFrameImageView;
- (void)setScreenshotImageView:(id)fp8;
- (id)screenshotImageView;
- (void)setDescriptionLabel:(id)fp8;
- (id)descriptionLabel;
- (void).cxx_destruct;
- (void)setup;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)fp8;

@end

