/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@interface TNDRFacebookImagePickerController : _ABCreateStringWithAddressDictionary
{
    BOOL _isPickingForMainPhoto;
    id _photoPickerDelegate;
}

- (void)setIsPickingForMainPhoto:(BOOL)fp8;
- (BOOL)isPickingForMainPhoto;
- (void)setPhotoPickerDelegate:(id)fp8;
- (id)photoPickerDelegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)setupOriginalNavigationBarBackButtonAppearance;
- (void)viewDidLoad;

@end

