/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class UIImage;

@interface TNDRGroupFriendCheckView : _ABCreateStringWithAddressDictionary
{
    BOOL _checked;
    UIImage *_checkedImage;
    UIImage *_uncheckedImage;
}

- (void)setUncheckedImage:(id)fp8;
- (id)uncheckedImage;
- (void)setCheckedImage:(id)fp8;
- (id)checkedImage;
- (BOOL)isChecked;
- (void).cxx_destruct;
- (void)setChecked:(BOOL)fp8;
- (void)setup;
- (id)init;

@end

