/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TNDRHomeProfileViewDelegate <NSObject>
- (void)didRequestToOpenPassportSettings;
- (void)didRequestToEditProfile;
- (void)didUpdateCurrentUserAvatarLastViewedPhoto:(id)fp8;
- (void)didRequestToOpenUserProfileWithFullSizeAvatar:(id)fp8 andFrame:(struct CGRect)fp12;
@end

