/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UIWebViewDelegate-Protocol.h"

@class MBProgressHUD, NSString, UIWebView;

@interface TNDRFacebookLoginWebviewController : _ABCreateStringWithAddressDictionary <UIWebViewDelegate>
{
    BOOL _cleanedLoginPage;
    id <TNDRFacebookLoginWebviewControllerDelegate> _delegate;
    UIWebView *_webview;
    NSString *_retrievedFacebookToken;
    MBProgressHUD *_currentHUD;
}

- (void)setCleanedLoginPage:(BOOL)fp8;
- (BOOL)hasCleanedLoginPage;
- (void)setCurrentHUD:(id)fp8;
- (id)currentHUD;
- (void)setRetrievedFacebookToken:(id)fp8;
- (id)retrievedFacebookToken;
- (void)setWebview:(id)fp8;
- (id)webview;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)animateInLoadedWebview;
- (void)cleanFacebookLoginWebview:(id)fp8;
- (BOOL)shouldPreventLoadingRequest:(id)fp8;
- (void)hideHUDForView;
- (BOOL)checkHTMLBody:(id)fp8 forStrings:(id)fp12;
- (BOOL)encounteredUserCancellationInWebview:(id)fp8;
- (BOOL)encounteredPermissionsRequest:(id)fp8;
- (BOOL)encounteredErrorInWebview:(id)fp8;
- (BOOL)requestIsStartingFacebookAuth:(id)fp8;
- (void)parseFacebookTokenFromFinalLoad;
- (id)commaSeparatedRequiredPermissions;
- (id)facebookManualLoginURLRequest;
- (id)customRedirectURL;
- (void)removeCookies;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)setupWithDelegate:(id)fp8;
- (id)initWithDelegate:(id)fp8;

@end

