/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "MKAnnotation-Protocol.h"

@class NSString, NSURL;

@interface TNDRPreviewAnnotation : _ABCreateStringWithAddressDictionary <MKAnnotation>
{
    NSString *_title;
    NSString *_subTitle;
    NSURL *_url;
    CDAnonymousStruct11 _coordinate;
}

- (void)setUrl:(id)fp8;
- (id)url;
- (void)setSubTitle:(id)fp8;
- (id)subTitle;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setCoordinate:(CDAnonymousStruct8)fp8;
- (CDAnonymousStruct8)coordinate;
- (void).cxx_destruct;

@end

