/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSCopying-Protocol.h"

@class NSString, NSURL, UIImage;

@interface TNDRMyProfilePhotoData : _ABCreateStringWithAddressDictionary <NSCopying>
{
    BOOL _isUploadingToServer;
    NSURL *_url;
    UIImage *_image;
    NSString *_photoId;
    NSString *_clientPhotoId;
}

+ (id)profilePhotoFromTNDRPhoto:(id)fp8;
- (void)setIsUploadingToServer:(BOOL)fp8;
- (BOOL)isUploadingToServer;
- (void)setClientPhotoId:(id)fp8;
- (id)clientPhotoId;
- (void)setPhotoId:(id)fp8;
- (id)photoId;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setUrl:(id)fp8;
- (id)url;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

