/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSAttributedString, NSLayoutConstraint, TNDRLabel, UILabel, UIView;

@interface TNDRNewSubscriptionCostCollectionViewCell : _ABCreateStringWithAddressDictionary
{
    NSAttributedString *_numberOfMonths;
    UIView *_outerContainerView;
    UIView *_innerContainerView;
    NSLayoutConstraint *_topContainerViewConstraint;
    TNDRLabel *_pricePerMonthLabel;
    UILabel *_numberOfMonthsLabel;
    UILabel *_discountLabel;
    NSAttributedString *_selectedAttributedString;
}

+ (id)priceTextColor;
+ (id)unselectedBorderColor;
- (void)setSelectedAttributedString:(id)fp8;
- (id)selectedAttributedString;
- (void)setDiscountLabel:(id)fp8;
- (id)discountLabel;
- (void)setNumberOfMonthsLabel:(id)fp8;
- (id)numberOfMonthsLabel;
- (void)setPricePerMonthLabel:(id)fp8;
- (id)pricePerMonthLabel;
- (void)setTopContainerViewConstraint:(id)fp8;
- (id)topContainerViewConstraint;
- (void)setInnerContainerView:(id)fp8;
- (id)innerContainerView;
- (void)setOuterContainerView:(id)fp8;
- (id)outerContainerView;
- (id)numberOfMonths;
- (void).cxx_destruct;
- (void)updateForSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (void)prepareForReuse;
- (void)setSelected:(BOOL)fp8;
- (void)setNumberOfMonths:(id)fp8;
- (id)discount;
- (void)setDiscount:(id)fp8;
- (id)pricePerMonth;
- (void)setPricePerMonth:(id)fp8;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

