/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, TNDRMatch;

@interface TNDRExpiredChatViewModel : _ABCreateStringWithAddressDictionary
{
    TNDRMatch *_match;
    NSArray *_members;
}

- (void)setMembers:(id)fp8;
- (id)members;
- (void)setMatch:(id)fp8;
- (id)match;
- (void).cxx_destruct;
- (int)rowForUser:(id)fp8;
- (id)userForRow:(int)fp8;
- (int)swipeValueForRow:(int)fp8;
- (id)nameForRow:(int)fp8;
- (id)avatarURLForRow:(int)fp8;
- (int)numberOfRows;
- (void)setup;
- (id)initWithMatch:(id)fp8;

@end

