/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSArray, UIButton, UIView;

@interface TNDRSuperLikeDialogFooter : _ABCreateStringWithAddressDictionary
{
    BOOL _calculateContentSize;
    UIButton *_actionButton;
    UIButton *_cancelButton;
    float _preferredContentWidth;
    unsigned int _footerType;
    NSArray *_contentConstraints;
    UIView *_contentView;
    float _preferredButtonHeight;
}

+ (id)footerOfType:(unsigned int)fp8;
+ (BOOL)requiresConstraintBasedLayout;
- (void)setPreferredButtonHeight:(float)fp8;
- (float)preferredButtonHeight;
- (void)setContentView:(id)fp8;
- (id)contentView;
- (void)setContentConstraints:(id)fp8;
- (id)contentConstraints;
- (void)setFooterType:(unsigned int)fp8;
- (unsigned int)footerType;
- (void)setCalculateContentSize:(BOOL)fp8;
- (BOOL)calculateContentSize;
- (void)setPreferredContentWidth:(float)fp8;
- (float)preferredContentWidth;
- (void)setCancelButton:(id)fp8;
- (id)cancelButton;
- (void)setActionButton:(id)fp8;
- (id)actionButton;
- (void).cxx_destruct;
- (void)invalidateIntrinsicContentSize;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)updateSubviewConstraints;
- (void)updateConstraints;
- (void)setupSubview;
- (id)initWithFooterType:(unsigned int)fp8;

@end

