/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "UICollectionViewDelegateLeftAlignedLayout-Protocol.h"

@class TNDRInterestsCollectionViewCell, TNDRInterestsViewModel, TNDRUser, UILabel;

@interface TNDRInterestsCollectionViewController : _ABCreateStringWithAddressDictionary <UICollectionViewDelegateLeftAlignedLayout>
{
    TNDRUser *_user;
    TNDRInterestsViewModel *_viewModel;
    TNDRInterestsCollectionViewCell *_sizingCell;
    UILabel *_titleLabel;
}

- (void)setTitleLabel:(id)fp8;
- (id)titleLabel;
- (void)setSizingCell:(id)fp8;
- (id)sizingCell;
- (void)setViewModel:(id)fp8;
- (id)viewModel;
- (id)user;
- (void).cxx_destruct;
- (struct UIEdgeInsets)collectionView:(id)fp8 layout:(id)fp12 insetForSectionAtIndex:(int)fp16;
- (float)collectionView:(id)fp8 layout:(id)fp12 minimumLineSpacingForSectionAtIndex:(int)fp16;
- (float)collectionView:(id)fp8 layout:(id)fp12 minimumInteritemSpacingForSectionAtIndex:(int)fp16;
- (struct CGSize)collectionView:(id)fp8 layout:(id)fp12 sizeForItemAtIndexPath:(id)fp16;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (int)numberOfSectionsInCollectionView:(id)fp8;
- (void)setUser:(id)fp8;
- (void)viewDidLoad;
- (void)setup;

@end

