/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class TNDRPassportLocationActivePeopleView, TNDRPassportLocationStatsView, UIButton;

@interface TNDRPassportLocationInfoView : _ABCreateStringWithAddressDictionary
{
    TNDRPassportLocationStatsView *_statView;
    TNDRPassportLocationActivePeopleView *_activePeopleView;
    UIButton *_goToLocationButton;
}

- (void)setGoToLocationButton:(id)fp8;
- (id)goToLocationButton;
- (void)setActivePeopleView:(id)fp8;
- (id)activePeopleView;
- (void)setStatView:(id)fp8;
- (id)statView;
- (void).cxx_destruct;
- (void)_setupAutoLayout;
- (void)_setupSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

