/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRURLNavigationManager-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@interface TNDRAlertDVCManager : _ABCreateStringWithAddressDictionary <UIViewControllerTransitioningDelegate, TNDRURLNavigationManager>
{
}

+ (id)sharedAlertDVCManager;
- (id)animationControllerForDismissedController:(id)fp8;
- (id)animationControllerForPresentedController:(id)fp8 presentingController:(id)fp12 sourceController:(id)fp16;
- (BOOL)handlesViewController:(id)fp8;

@end

