/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_TNDRUser.h"

#import "TNDRUserGroupProtocol-Protocol.h"

@interface TNDRUser : _TNDRUser <TNDRUserGroupProtocol>
{
    BOOL _profileViewed;
    BOOL _seenOnStack;
}

+ (id)rewindableUser;
- (void)setSeenOnStack:(BOOL)fp8;
- (BOOL)seenOnStack;
- (void)setProfileViewed:(BOOL)fp8;
- (BOOL)isProfileViewed;
- (void)trackRewindFromPaywall:(BOOL)fp8 isUserTraveling:(BOOL)fp12;
- (id)firstPhotoID;
- (void)resetForRewind;
- (id)commonName;
- (id)entityID;
- (void)reportWithReason:(id)fp8 andMessage:(id)fp12 completion:(id)fp(null);
- (void)trackRecsPhotoView;
- (void)trackRecsView;
- (id)sortedPhotos;
- (id)mainBadgeColor;
- (id)mainBadgeDescription;
- (id)mainBadgeType;
- (id)coloredImageFromImage:(id)fp8 hexColor:(id)fp12;
- (BOOL)currentUserDidSuperLikeUser;
- (BOOL)didSuperLikeCurrentUser;
- (void)awakeFromInsert;
- (id)commonInterestsFromCurrentLikes;
- (void)updateCommonAttributes:(id)fp(null);
- (int)degreeForCommonID:(id)fp8 inConnections:(id)fp12;
- (void)updateCommonConnectionsWithFB:(id)fp(null);
- (void)rearrangePhotosForUser:(id)fp8 basedOnJSON:(id)fp12;
- (void)updateUserCommonConnections:(id)fp(null);
- (void)update:(id)fp(null);
- (void)rewindSuperLikedRecommendation:(id)fp(null);
- (void)declineRecommendationTrending:(BOOL)fp8 completion:(id)fp(null);
- (void)declineRecommendation:(id)fp(null);
- (void)likeRecommendationTrending:(BOOL)fp8 superLiked:(BOOL)fp12 completion:(id)fp(null);
- (void)likeRecommendationWithSuperLike:(BOOL)fp8 completion:(id)fp(null);
- (id)dislikeCompletionBlockWithCompletion:(SEL)fp4;
- (id)likeCompletionBlockForSuperLike:(SEL)fp4 completion:(BOOL)fp8;
- (id)imageURLForWidth:(float)fp8 useLargerImageIfAvailable:(BOOL)fp12;
- (id)imageURLForWidth:(float)fp8;
- (id)smallMainImageURL;
- (id)largeMainImageURL;
- (BOOL)isMemberOfCurrentGroup;
- (BOOL)setUpUserFromDictionary:(id)fp8 inGroup:(id)fp12 groupMemberType:(int)fp16 isNewUser:(BOOL)fp20;

@end

