/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class UIActivityIndicatorView, UINavigationBar, UIWebView;

@interface TNDRInstagramLoginWebViewController : _ABCreateStringWithAddressDictionary <UIWebViewDelegate, TNDRURLNavigableProtocol>
{
    id <TNDRInstagramLoginWebViewControllerDelegate> _delegate;
    UINavigationBar *_navigationBar;
    UIWebView *_igLoginWebView;
    UIActivityIndicatorView *_spinner;
}

+ (id)viewControllerNavigationKey;
- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setIgLoginWebView:(id)fp8;
- (id)igLoginWebView;
- (void)setNavigationBar:(id)fp8;
- (id)navigationBar;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (id)parseErrorMessageFromURL:(id)fp8;
- (id)parseOutIGAccessCodeFromURL:(id)fp8;
- (BOOL)loginProcessHasErrors:(id)fp8;
- (BOOL)urlIsRedirectionURL:(id)fp8;
- (void)parseAccessCodeAndNotifyDelegate:(id)fp8;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)loadInstagramSite;
- (id)instagramLoginRequest;
- (id)instagramLoginURL;
- (void)handleCancelButtonTapped:(id)fp8;
- (void)removeCookies;
- (void)resetWebView;
- (void)retryLogin;
- (void)hideSpinner;
- (void)showSpinner;
- (void)removeWebViewGrayBackground:(id)fp8;
- (void)setupWebView;
- (void)setupNavigationBar;
- (float)heightNavbar;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;

@end

