/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "TNDRURLNavigableProtocol-Protocol.h"

@interface TNDRSafariViewController : _ABCreateStringWithAddressDictionary <TNDRURLNavigableProtocol>
{
    BOOL _previewingForPeek;
}

+ (id)viewControllerNavigationKey;
- (void)setPreviewingForPeek:(BOOL)fp8;
- (BOOL)isPreviewingForPeek;
- (void)viewDidDisappear:(BOOL)fp8;

@end

