/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSCoding-Protocol.h"

@class NSDictionary, NSString, NSTextCheckingResult;

@interface TTTAttributedLabelLink : _ABCreateStringWithAddressDictionary <NSCoding>
{
    NSTextCheckingResult *_result;
    NSDictionary *_attributes;
    NSDictionary *_activeAttributes;
    NSDictionary *_inactiveAttributes;
    NSString *_accessibilityValue;
    id _linkTapBlock;
    id _linkLongPressBlock;
}

- (void)setLinkLongPressBlock:(id)fp(null);
- (id)linkLongPressBlock;
- (void)setLinkTapBlock:(id)fp(null);
- (id)linkTapBlock;
- (void)setAccessibilityValue:(id)fp8;
- (id)inactiveAttributes;
- (id)activeAttributes;
- (id)attributes;
- (id)result;
- (void).cxx_destruct;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)accessibilityValue;
- (id)initWithAttributesFromLabel:(id)fp8 textCheckingResult:(id)fp12;
- (id)initWithAttributes:(id)fp8 activeAttributes:(id)fp12 inactiveAttributes:(id)fp16 textCheckingResult:(id)fp20;

@end

