/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSCalendar, NSLocale, NSString;

@interface TTTTimeIntervalFormatter : _ABCreateStringWithAddressDictionary
{
    BOOL _usesAbbreviatedCalendarUnits;
    BOOL _usesApproximateQualifier;
    BOOL _usesIdiomaticDeicticExpressions;
    NSLocale *_locale;
    NSCalendar *_calendar;
    NSString *_pastDeicticExpression;
    NSString *_presentDeicticExpression;
    NSString *_futureDeicticExpression;
    NSString *_deicticExpressionFormat;
    NSString *_suffixExpressionFormat;
    NSString *_approximateQualifierFormat;
    unsigned int _numberOfSignificantUnits;
    unsigned int _leastSignificantUnit;
    unsigned int _significantUnits;
    double _presentTimeIntervalMargin;
}

- (void)setSignificantUnits:(unsigned int)fp8;
- (unsigned int)significantUnits;
- (void)setLeastSignificantUnit:(unsigned int)fp8;
- (unsigned int)leastSignificantUnit;
- (void)setNumberOfSignificantUnits:(unsigned int)fp8;
- (unsigned int)numberOfSignificantUnits;
- (void)setUsesIdiomaticDeicticExpressions:(BOOL)fp8;
- (BOOL)usesIdiomaticDeicticExpressions;
- (void)setUsesApproximateQualifier:(BOOL)fp8;
- (BOOL)usesApproximateQualifier;
- (void)setUsesAbbreviatedCalendarUnits:(BOOL)fp8;
- (BOOL)usesAbbreviatedCalendarUnits;
- (void)setPresentTimeIntervalMargin:(double)fp8;
- (double)presentTimeIntervalMargin;
- (void)setApproximateQualifierFormat:(id)fp8;
- (id)approximateQualifierFormat;
- (void)setSuffixExpressionFormat:(id)fp8;
- (id)suffixExpressionFormat;
- (void)setDeicticExpressionFormat:(id)fp8;
- (id)deicticExpressionFormat;
- (void)setFutureDeicticExpression:(id)fp8;
- (id)futureDeicticExpression;
- (void)setPresentDeicticExpression:(id)fp8;
- (id)presentDeicticExpression;
- (void)setPastDeicticExpression:(id)fp8;
- (id)pastDeicticExpression;
- (void)setCalendar:(id)fp8;
- (id)calendar;
- (void)setLocale:(id)fp8;
- (id)locale;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)getObjectValue:(out id *)fp8 forString:(id)fp12 errorDescription:(out id *)fp16;
- (id)stringForObjectValue:(id)fp8;
- (id)itRelativeDateStringForComponents:(id)fp8;
- (id)frRelativeDateStringForComponents:(id)fp8;
- (id)jaRelativeDateStringForComponents:(id)fp8;
- (id)csRelativeDateStringForComponents:(id)fp8;
- (id)plRelativeDateStringForComponents:(id)fp8;
- (id)nlRelativeDateStringForComponents:(id)fp8;
- (id)esRelativeDateStringForComponents:(id)fp8;
- (id)enRelativeDateStringForComponents:(id)fp8;
- (id)caRelativeDateStringForComponents:(id)fp8;
- (id)localizedIdiomaticDeicticExpressionForComponents:(id)fp8;
- (id)localizedStringForNumber:(unsigned int)fp8 ofCalendarUnit:(unsigned int)fp12;
- (id)stringForTimeIntervalFromDate:(id)fp8 toDate:(id)fp12;
- (id)stringForTimeInterval:(double)fp8;
- (id)init;

@end

