/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

#import "NSCoding-Protocol.h"

@class NSNumberFormatter;

@interface TTTUnitOfInformationFormatter : _ABCreateStringWithAddressDictionary <NSCoding>
{
    BOOL _displaysInTermsOfBytes;
    BOOL _usesIECBinaryPrefixesForCalculation;
    BOOL _usesIECBinaryPrefixesForDisplay;
    NSNumberFormatter *_numberFormatter;
}

- (void)setNumberFormatter:(id)fp8;
- (id)numberFormatter;
- (void)setUsesIECBinaryPrefixesForDisplay:(BOOL)fp8;
- (BOOL)usesIECBinaryPrefixesForDisplay;
- (void)setUsesIECBinaryPrefixesForCalculation:(BOOL)fp8;
- (BOOL)usesIECBinaryPrefixesForCalculation;
- (void)setDisplaysInTermsOfBytes:(BOOL)fp8;
- (BOOL)displaysInTermsOfBytes;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)getObjectValue:(out id *)fp8 forString:(id)fp12 errorDescription:(out id *)fp16;
- (id)stringForObjectValue:(id)fp8;
- (id)stringFromNumber:(id)fp8 ofUnit:(unsigned int)fp12 withPrefix:(unsigned int)fp16;
- (id)stringFromNumber:(id)fp8 ofUnit:(unsigned int)fp12;
- (id)stringFromNumberOfBits:(id)fp8;
- (unsigned int)prefixForInteger:(unsigned long long)fp8;
- (double)scaleFactorForPrefix:(unsigned int)fp8;
- (id)init;

@end

