/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABCreateStringWithAddressDictionary.h"

@class NSString, NSURL;

@interface UICKeyChainStore : _ABCreateStringWithAddressDictionary
{
    BOOL _synchronizable;
    int _itemClass;
    NSString *_service;
    NSString *_accessGroup;
    NSURL *_server;
    int _protocolType;
    int _authenticationType;
    int _accessibility;
    int _authenticationPolicy;
    NSString *_authenticationPrompt;
}

+ (id)unexpectedError:(id)fp8;
+ (id)securityError:(long)fp8;
+ (id)conversionError:(id)fp8;
+ (id)argumentError:(id)fp8;
+ (id)generatePassword;
+ (void)requestSharedWebCredentialForDomain:(id)fp8 account:(id)fp12 completion:(id)fp(null);
+ (void)requestSharedWebCredentialWithCompletion:(id)fp(null);
+ (id)prettify:(void *)fp8 items:(id)fp12;
+ (id)allItemsWithItemClass:(int)fp8;
+ (id)allKeysWithItemClass:(int)fp8;
+ (BOOL)removeAllItemsForService:(id)fp8 accessGroup:(id)fp12 error:(id *)fp16;
+ (BOOL)removeAllItemsForService:(id)fp8 accessGroup:(id)fp12;
+ (BOOL)removeAllItemsForService:(id)fp8 error:(id *)fp12;
+ (BOOL)removeAllItemsForService:(id)fp8;
+ (BOOL)removeAllItemsWithError:(id *)fp8;
+ (BOOL)removeAllItems;
+ (BOOL)removeItemForKey:(id)fp8 service:(id)fp12 accessGroup:(id)fp16 error:(id *)fp20;
+ (BOOL)removeItemForKey:(id)fp8 service:(id)fp12 accessGroup:(id)fp16;
+ (BOOL)removeItemForKey:(id)fp8 service:(id)fp12 error:(id *)fp16;
+ (BOOL)removeItemForKey:(id)fp8 service:(id)fp12;
+ (BOOL)removeItemForKey:(id)fp8 error:(id *)fp12;
+ (BOOL)removeItemForKey:(id)fp8;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 service:(id)fp16 accessGroup:(id)fp20 genericAttribute:(id)fp24 error:(id *)fp28;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 service:(id)fp16 accessGroup:(id)fp20 genericAttribute:(id)fp24;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 service:(id)fp16 accessGroup:(id)fp20 error:(id *)fp24;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 service:(id)fp16 accessGroup:(id)fp20;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 service:(id)fp16 genericAttribute:(id)fp20 error:(id *)fp24;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 service:(id)fp16 genericAttribute:(id)fp20;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 service:(id)fp16 error:(id *)fp20;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 service:(id)fp16;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16 error:(id *)fp20;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12 error:(id *)fp16;
+ (BOOL)setData:(id)fp8 forKey:(id)fp12;
+ (id)dataForKey:(id)fp8 service:(id)fp12 accessGroup:(id)fp16 error:(id *)fp20;
+ (id)dataForKey:(id)fp8 service:(id)fp12 accessGroup:(id)fp16;
+ (id)dataForKey:(id)fp8 service:(id)fp12 error:(id *)fp16;
+ (id)dataForKey:(id)fp8 service:(id)fp12;
+ (id)dataForKey:(id)fp8 error:(id *)fp12;
+ (id)dataForKey:(id)fp8;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 service:(id)fp16 accessGroup:(id)fp20 genericAttribute:(id)fp24 error:(id *)fp28;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 service:(id)fp16 accessGroup:(id)fp20 genericAttribute:(id)fp24;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 service:(id)fp16 accessGroup:(id)fp20 error:(id *)fp24;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 service:(id)fp16 accessGroup:(id)fp20;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 service:(id)fp16 genericAttribute:(id)fp20 error:(id *)fp24;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 service:(id)fp16 genericAttribute:(id)fp20;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 service:(id)fp16 error:(id *)fp20;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 service:(id)fp16;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16 error:(id *)fp20;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12 error:(id *)fp16;
+ (BOOL)setString:(id)fp8 forKey:(id)fp12;
+ (id)stringForKey:(id)fp8 service:(id)fp12 accessGroup:(id)fp16 error:(id *)fp20;
+ (id)stringForKey:(id)fp8 service:(id)fp12 accessGroup:(id)fp16;
+ (id)stringForKey:(id)fp8 service:(id)fp12 error:(id *)fp16;
+ (id)stringForKey:(id)fp8 service:(id)fp12;
+ (id)stringForKey:(id)fp8 error:(id *)fp12;
+ (id)stringForKey:(id)fp8;
+ (id)keyChainStoreWithServer:(id)fp8 protocolType:(int)fp12 authenticationType:(int)fp16;
+ (id)keyChainStoreWithServer:(id)fp8 protocolType:(int)fp12;
+ (id)keyChainStoreWithService:(id)fp8 accessGroup:(id)fp12;
+ (id)keyChainStoreWithService:(id)fp8;
+ (id)keyChainStore;
+ (void)setDefaultService:(id)fp8;
+ (id)defaultService;
- (void)setAuthenticationPrompt:(id)fp8;
- (id)authenticationPrompt;
- (BOOL)synchronizable;
- (int)authenticationPolicy;
- (void)setAccessibility:(int)fp8;
- (int)accessibility;
- (int)authenticationType;
- (int)protocolType;
- (id)server;
- (id)accessGroup;
- (id)service;
- (int)itemClass;
- (void).cxx_destruct;
- (void *)accessibilityObject;
- (void *)authenticationTypeObject;
- (void *)protocolTypeObject;
- (void *)itemClassObject;
- (id)attributesWithKey:(id)fp8 value:(id)fp12 error:(id *)fp16;
- (id)query;
- (id)debugDescription;
- (id)description;
- (BOOL)synchronizeWithError:(id *)fp8;
- (void)synchronize;
- (void)removeSharedPasswordForAccount:(id)fp8 completion:(id)fp(null);
- (void)setSharedPassword:(id)fp8 forAccount:(id)fp12 completion:(id)fp(null);
- (void)sharedPasswordForAccount:(id)fp8 completion:(id)fp(null);
- (void)sharedPasswordWithCompletion:(id)fp(null);
- (void)setAccessibility:(int)fp8 authenticationPolicy:(int)fp12;
- (void)setSynchronizable:(BOOL)fp8;
- (id)items;
- (id)allItems;
- (id)allKeys;
- (void)setObject:(id)fp8 forKeyedSubscript:(id)fp12;
- (id)objectForKeyedSubscript:(id)fp8;
- (BOOL)removeAllItemsWithError:(id *)fp8;
- (BOOL)removeAllItems;
- (BOOL)removeItemForKey:(id)fp8 error:(id *)fp12;
- (BOOL)removeItemForKey:(id)fp8;
- (BOOL)setData:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16 label:(id)fp20 comment:(id)fp24 error:(id *)fp28;
- (BOOL)setData:(id)fp8 forKey:(id)fp12 label:(id)fp16 comment:(id)fp20 error:(id *)fp24;
- (BOOL)setData:(id)fp8 forKey:(id)fp12 label:(id)fp16 comment:(id)fp20;
- (BOOL)setData:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16 error:(id *)fp20;
- (BOOL)setData:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16;
- (BOOL)setData:(id)fp8 forKey:(id)fp12 error:(id *)fp16;
- (BOOL)setData:(id)fp8 forKey:(id)fp12;
- (id)dataForKey:(id)fp8 error:(id *)fp12;
- (id)dataForKey:(id)fp8;
- (BOOL)setString:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16 label:(id)fp20 comment:(id)fp24 error:(id *)fp28;
- (BOOL)setString:(id)fp8 forKey:(id)fp12 label:(id)fp16 comment:(id)fp20 error:(id *)fp24;
- (BOOL)setString:(id)fp8 forKey:(id)fp12 label:(id)fp16 comment:(id)fp20;
- (BOOL)setString:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16 error:(id *)fp20;
- (BOOL)setString:(id)fp8 forKey:(id)fp12 genericAttribute:(id)fp16;
- (BOOL)setString:(id)fp8 forKey:(id)fp12 error:(id *)fp16;
- (BOOL)setString:(id)fp8 forKey:(id)fp12;
- (id)stringForKey:(id)fp8 error:(id *)fp12;
- (id)stringForKey:(id)fp8;
- (BOOL)contains:(id)fp8;
- (void)commonInit;
- (id)initWithServer:(id)fp8 protocolType:(int)fp12 authenticationType:(int)fp16;
- (id)initWithServer:(id)fp8 protocolType:(int)fp12;
- (id)initWithService:(id)fp8 accessGroup:(id)fp12;
- (id)initWithService:(id)fp8;
- (id)init;

@end

